/* Work Center V5. One server snapshot drives all queues, counts and drilldowns. */
let wcV5 = {user:null,data:null,request:0,detailRequest:0,metric:'',employee:'',decision:'all',view:'list',channel:null,poll:null,refreshTimer:null,drawerFocus:null,busy:false};
const wcSections = {
 overview:['نظرة عامة','Overview','جميع أعمال الدورة الحالية وتوزيع المسؤوليات.','Current cycle and team responsibilities.'],
 execution:['قائمة التنفيذ','Execution queue','الأعمال الجاهزة للبدء والجاري تنفيذها.','Assigned work ready to start or in progress.'],
 reviews:['المراجعات والاعتمادات','Reviews & approvals','نتائج المهام وطلبات التمديد والاعتمادات المالية.','Submitted results, extension requests and financial approvals.'],
 attention:['التعثر والتصعيد','Blockers & escalation','الأعمال المتوقفة والمعادة والتأخير الذي يحتاج تدخلًا.','Blocked, paused, returned or overdue work.'],
 completed:['سجل الإنجاز','Completion history','الإنجازات المعتمدة في الفترة المختارة ضمن الدورة الحالية.','Approved completions in the selected period within this cycle.']
};
function wcText(ar,en){return currentLang==='en'?en:ar}
function workCenterActionLabel(action){const labels={ACKNOWLEDGE:['استلام العمل','Acknowledge'],START:['بدء التنفيذ','Start work'],PAUSE:['إيقاف مؤقت','Pause'],RESUME:['استئناف التنفيذ','Resume'],COMMENT:['إضافة تعليق','Add comment'],PROGRESS_UPDATE:['تحديث التقدم','Update progress'],REQUEST_CLARIFICATION:['طلب توضيح','Request clarification'],REPORT_BLOCKER:['تسجيل تعثر','Report blocker'],RESOLVE_BLOCKER:['إنهاء التعثر','Resolve blocker'],REQUEST_EXTENSION:['طلب تمديد','Request extension'],COMPLETE:['تسليم النتيجة للمراجعة','Submit result'],SUBMIT_FOR_REVIEW:['إرسال للمراجعة','Submit for review'],APPROVE_EXTENSION:['اعتماد التمديد','Approve extension'],REJECT_EXTENSION:['رفض التمديد','Reject extension'],REQUEST_EXTENSION_INFO:['طلب معلومات إضافية','Request more information'],APPROVE_COMPLETION:['مراجعة واعتماد النتيجة','Review & approve'],RETURN_REWORK:['إعادة للتصحيح','Return for correction'],REASSIGN:['إعادة الإسناد','Reassign'],CHANGE_DUE:['تعديل الموعد','Change deadline'],CHANGE_PRIORITY:['تعديل الأولوية','Change priority'],CHANGE_REVIEWER:['تغيير المراجع','Change reviewer'],REQUEST_JUSTIFICATION:['طلب تبرير','Request justification'],APPROVE_PAYMENT_SUPERVISOR:['اعتماد المشرف','Supervisor approval'],APPROVE_PAYMENT_CFO:['اعتماد المدير المالي','CFO approval'],EXECUTE_PAYMENT:['تنفيذ الدفعة','Execute payment'],REGISTER_ACCOUNTING:['تسجيل محاسبي','Register accounting'],FINALIZE_POSTING:['ترحيل وإقفال','Post & finalize']};return labels[action]?wcText(...labels[action]):displayText(action)}
function workflowTypeLabel(type){const names={MANUAL_TASK:['مهمة تشغيلية','Operational task'],PAYMENT_SUPERVISOR_APPROVAL:['اعتماد المشرف','Supervisor approval'],PAYMENT_CFO_APPROVAL:['اعتماد المدير المالي','CFO approval'],PAYMENT_BANK_EXECUTION:['التنفيذ البنكي','Bank execution'],PAYMENT_ACCOUNTING_REGISTRATION:['التسجيل المحاسبي','Accounting registration'],PAYMENT_POSTING_FINALIZATION:['الترحيل والإقفال','Posting & close']};return names[type]?wcText(...names[type]):type;}
function wcEl(id){return document.getElementById(id)}
function wcManager(){return ['CFO','Supervisor'].includes(profile?.role)}
function wcReadonly(){return typeof isReadonlyViewer==='function'&&isReadonlyViewer()}
function wcNumber(value){return latinDigits(value??0)}
function wcPercent(value){return value===null||value===undefined?wcText('لا توجد بيانات كافية','Insufficient data'):`${Number(value).toFixed(1)}%`}
function wcStatus(w){const labels={Ready:['جاهز للبدء','Ready'],Assigned:['مسند','Assigned'],'In Progress':['قيد التنفيذ','In progress'],Started:['قيد التنفيذ','In progress'],Paused:['متوقف مؤقتًا','Paused'],Blocked:['متعثر','Blocked'],'Pending Review':['بانتظار المراجعة','Pending review'],'Extension Requested':['طلب تمديد','Extension request'],'Returned for Rework':['معاد للتصحيح','Returned for rework'],Completed:['منجز معتمد','Approved completion']};const l=labels[w.status]||[w.status,w.status];return `<span class="wc-pill ${w.status==='Completed'?'green':w.is_attention?'amber':''}">${esc(wcText(...l))}</span>`}
function wcSetup(){
 if(wcV5.user===profile?.id)return;
 if(wcV5.channel)sb.removeChannel(wcV5.channel);
 if(wcV5.poll)clearInterval(wcV5.poll);
 wcV5.user=profile.id;wcV5.data=null;wcV5.metric='';wcV5.employee='';wcV5.decision='all';
 workcenterItems=[];workcenterSummary={};teamOperationsMonitor=[];closeWorkCenterDetail();
 workcenterTab='overview';workcenterScope=wcReadonly()?'team':(wcManager()?'team':'mine');
 const refresh=()=>{clearTimeout(wcV5.refreshTimer);wcV5.refreshTimer=setTimeout(()=>{if(!document.hidden&&wcEl('workcenter')?.classList.contains('active')&&!wcV5.busy)loadWorkCenter(true)},600)};
 wcV5.channel=sb.channel(`workcenter-v5-${profile.id}`).on('postgres_changes',{event:'*',schema:'public',table:'work_items'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'tasks'},refresh).subscribe();
 wcV5.poll=setInterval(refresh,30000);
}
function wcBuildShell(){
 const root=wcEl('workcenter');if(!root||root.dataset.v5==='ready')return;root.dataset.v5='ready';
 root.innerHTML=`<div class="wc-hero"><div><div class="wc-kicker">SANAM · ${wcText('عمليات الإدارة المالية','FINANCE OPERATIONS')}</div><h2>${wcText('مركز العمل','Work Center')}</h2><p>${wcText('مسؤوليات واضحة، قرارات في وقتها، وإنجاز موثق.','Clear ownership, timely decisions and documented results.')}</p><div class="wc-meta"><span class="wc-cycle" id="wcCycleLabel"></span><span id="wcSyncStatus" role="status" aria-live="polite"></span></div><div id="wcWorkdayStatus" class="workday-status"></div></div><div class="wc-hero-actions"><button id="wcWorkdayBtn" class="btn" onclick="toggleWorkday()">${wcText('بدء يوم العمل','Start workday')}</button><button id="wcNotificationsBtn" class="btn" onclick="openTaskNotifications()">${wcText('التنبيهات','Notifications')}</button><button id="wcAdhocTaskBtn" class="btn primary" onclick="openAdhocActivityModal()">${wcText('+ تسجيل مهمة إضافية','+ Log Extra Task')}</button><button id="wcDailyPlanBtn" class="btn" onclick="openDailyPlan()">${wcText('إعداد خطة اليوم','Plan today')}</button><button id="wcAddTaskBtn" class="btn primary" onclick="openTaskModal()">${wcText('+ إسناد مهمة','+ Assign task')}</button></div></div>
 <div class="wc-shell"><div class="wc-scope"><div class="wc-segment" id="wcScopeWrap"><button id="wcMineBtn" onclick="setWorkCenterScope('mine')">${wcText('أعمالي','My work')}</button><button id="wcTeamBtn" onclick="setWorkCenterScope('team')">${wcText('أعمال الفريق','Team work')}</button></div><div><button class="wc-history-link" id="wcHistoricalReport" onclick="openEmployeePerformanceReport()">${wcText('التقارير التاريخية المحفوظة','Retained historical reports')}</button> <button class="btn" onclick="loadWorkCenter()">${wcText('تحديث','Refresh')}</button></div></div>
 <div class="wc-tabs" role="tablist" aria-label="${wcText('أقسام مركز العمل','Work Center sections')}">${Object.entries(wcSections).map(([k,v])=>`<button type="button" class="wc-tab" role="tab" data-wctab="${k}" aria-controls="wcResults" onclick="setWorkCenterTab('${k}')"><span>${wcText(v[0],v[1])}</span><span class="wc-count" data-wccount="${k}">0</span></button>`).join('')}</div>
 <div class="wc-filters"><label class="wc-search">${wcText('البحث عن عمل','Find work')}<input id="wcSearch" type="search" placeholder="${wcText('اسم المهمة أو المعاملة…','Task or transaction…')}" oninput="wcSearchChanged()"></label><label id="wcEmployeeLabel">${wcText('الموظف','Employee')}<select id="wcEmployeeFilter" onchange="wcV5.employee=this.value;renderWorkCenter()"></select></label><label>${wcText('نوع العمل','Work type')}<select id="wcTypeFilter" onchange="loadWorkCenter()"><option value="">${wcText('جميع الأنواع','All types')}</option>${['MANUAL_TASK','PAYMENT_SUPERVISOR_APPROVAL','PAYMENT_CFO_APPROVAL','PAYMENT_BANK_EXECUTION','PAYMENT_ACCOUNTING_REGISTRATION','PAYMENT_POSTING_FINALIZATION'].map(t=>`<option value="${t}">${esc(displayText(workflowTypeLabel(t)))}</option>`).join('')}</select></label><label>${wcText('الأولوية','Priority')}<select id="wcPriorityFilter" onchange="loadWorkCenter()"><option value="">${wcText('جميع الأولويات','All priorities')}</option>${['حرج','عالي','عادي','منخفض'].map(t=>`<option value="${t}">${esc(displayText(t))}</option>`).join('')}</select></label><button class="btn" onclick="clearWorkCenterFilters()">${wcText('مسح الفلاتر','Clear filters')}</button></div>
 <div id="wcCompletionDates" class="wc-filters hidden"><label>${wcText('الإنجاز من','Completed from')}<input id="wcFrom" type="date" onchange="loadWorkCenter()"></label><label>${wcText('إلى','To')}<input id="wcTo" type="date" onchange="loadWorkCenter()"></label><span class="wc-section-note">${wcText('الفترة تخص سجل الإنجاز؛ الأعمال المفتوحة تبقى ظاهرة.','Dates apply to completions; open work remains visible.')}</span></div></div>
 <div id="wcError" class="wc-error hidden" role="alert"></div><div id="workcenterSummary" class="wc-metrics"></div>
 <div id="teamOperationsMonitorWrap" class="wc-shell hidden"><div class="wc-panel-heading"><div><h4>${wcText('مراقبة الفريق','Team monitor')}</h4><p>${wcText('الدورة الحالية فقط · اضغط أي عدد لعرض الأعمال التي تكوّنه.','Current cycle only · Select a count to see the underlying work.')}</p></div></div><div class="wc-table-scroll"><table class="wc-list-table"><thead><tr>${[wcText('الموظف','Employee'),wcText('جاهز','Ready'),wcText('قيد التنفيذ','In progress'),wcText('مراجعات','Reviews'),wcText('يحتاج تدخلًا','Needs attention'),wcText('متأخر','Overdue'),wcText('منجز','Completed'),wcText('جودة النتائج','Result quality'),wcText('الالتزام بالموعد','On-time delivery')].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="teamOperationsMonitorBody"></tbody></table></div></div>
 <div class="wc-shell" id="wcResults" role="tabpanel"><div class="wc-panel-heading"><div><h3 id="wcSectionTitle"></h3><p id="wcSectionDescription"></p></div><div class="wc-segment"><button id="wcListBtn" onclick="wcV5.view='list';renderWorkCenter()">${wcText('قائمة','List')}</button><button id="wcBoardBtn" onclick="wcV5.view='board';renderWorkCenter()">${wcText('لوحة المراحل','Stage board')}</button></div></div><div class="wc-scope"><div id="wcDecisionWrap" class="wc-segment hidden"><button id="wcAllDecisions" onclick="wcV5.decision='all';renderWorkCenter()">${wcText('جميع المراجعات','All reviews')}</button><button id="wcMyDecisions" onclick="wcV5.decision='mine';renderWorkCenter()">${wcText('تتطلب قراري','My decisions')}</button></div><span class="wc-section-note" id="wcResultCount" aria-live="polite"></span><button id="wcClearMetric" class="btn hidden" onclick="wcV5.metric='';renderWorkCenter()">${wcText('إلغاء تخصيص القائمة','Clear drilldown')}</button></div><div id="wcRows"></div></div><p class="wc-section-note">${wcText('الأعمال السابقة محفوظة في التقارير التاريخية. التأخير علامة إضافية وقد يتداخل مع حالة التنفيذ أو المراجعة.','Previous work is retained in historical reports. Overdue is an additional flag and may overlap execution or review.')}</p>`;
 root.querySelectorAll('[role=tab]').forEach((b,i,all)=>b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let j=e.key==='Home'?0:e.key==='End'?all.length-1:(i+(e.key==='ArrowRight'?1:-1)+all.length)%all.length;all[j].focus();setWorkCenterTab(all[j].dataset.wctab)}));
 wcEl('wcDailyPlanBtn').classList.toggle('hidden',!wcManager());wcEl('wcAddTaskBtn').classList.toggle('hidden',!wcManager());wcEl('wcHistoricalReport').classList.toggle('hidden',!wcManager());wcEl('wcAdhocTaskBtn')?.classList.toggle('hidden',wcReadonly());wcEl('wcWorkdayBtn')?.classList.toggle('hidden',wcReadonly());wcEl('wcNotificationsBtn')?.classList.toggle('hidden',wcReadonly());
 populateWorkCenterEmployeeFilter();renderTaskUtilityState();
}
function populateWorkCenterEmployeeFilter(){const el=wcEl('wcEmployeeFilter');if(!el)return;el.innerHTML=`<option value="">${wcText('جميع الموظفين','All employees')}</option>`+(profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.full_name)}</option>`).join('');el.value=wcV5.employee;}
function workCenterFilters(){const f={};for(const [id,key] of [['wcSearch','search'],['wcTypeFilter','item_type'],['wcPriorityFilter','priority'],['wcFrom','from'],['wcTo','to']]){if(wcEl(id)?.value)f[key]=wcEl(id).value;}return f;}
let wcSearchTimer;
function wcSearchChanged(){clearTimeout(wcSearchTimer);wcSearchTimer=setTimeout(()=>loadWorkCenter(),300)}
function clearWorkCenterFilters(){['wcSearch','wcTypeFilter','wcPriorityFilter','wcFrom','wcTo'].forEach(id=>{if(wcEl(id))wcEl(id).value=''});wcV5.employee='';wcV5.metric='';wcV5.decision='all';populateWorkCenterEmployeeFilter();return loadWorkCenter()}
function setWorkCenterTab(tab){if(!wcSections[tab])return;workcenterTab=tab;wcV5.metric='';wcV5.decision='all';renderWorkCenter()}
function setWorkCenterScope(scope){workcenterScope=scope==='team'&&wcManager()?'team':'mine';wcV5.employee='';wcV5.metric='';populateWorkCenterEmployeeFilter();return loadWorkCenter()}
async function loadWorkCenter(quiet=false){
 if(!profile||!canPage('workcenter'))return;wcSetup();wcBuildShell();const request=++wcV5.request;
 wcEl('wcSyncStatus').textContent=wcText('جارٍ التحديث…','Updating…');wcEl('wcError').classList.add('hidden');
 if(!quiet)wcEl('wcResults').classList.add('wc-loading');
 try{const requestCall=wcReadonly()?sb.rpc('get_readonly_workcenter_dashboard_v1',{p_filters:workCenterFilters()}):sb.rpc('get_workcenter_dashboard_v5',{p_scope:workcenterScope,p_filters:workCenterFilters()});const {data,error}=await requestCall;if(request!==wcV5.request)return;if(error)throw error;if(!data?.cycle)throw new Error(wcText('لم تبدأ دورة التشغيل الجديدة بعد.','The new operating cycle has not started yet.'));
 wcV5.data=data;workcenterItems=data.items||[];workcenterSummary=data.summary||{};teamOperationsMonitor=data.team||[];if(wcReadonly()){profiles=(data.team||[]).map(x=>({id:x.user_id,full_name:x.full_name,role:x.role,finance_team:true,active:true}));populateWorkCenterEmployeeFilter()}
 wcEl('wcCycleLabel').textContent=`${wcText('بداية الدورة','Cycle started')} · ${fmt(data.cycle.started_at)}`;
 wcEl('wcSyncStatus').textContent=`${wcText('آخر تحديث','Updated')} ${fmt(data.as_of)}`;renderWorkCenter();
 }catch(error){if(request!==wcV5.request)return;wcEl('wcError').textContent=wcText('تعذر تحميل مركز العمل. اضغط تحديث للمحاولة مجددًا. التفاصيل: ','Work Center could not be loaded. Refresh to retry. Details: ')+(error.message||String(error));wcEl('wcError').classList.remove('hidden');wcEl('wcSyncStatus').textContent=wcText('التحديث غير مكتمل','Update failed');if(!wcV5.data){workcenterItems=[];renderWorkCenter()} }
 finally{if(request===wcV5.request)wcEl('wcResults').classList.remove('wc-loading')}
}
function wcMetricMatch(w,metric){switch(metric){case'ready':return w.bucket==='execution'&&['Ready','Assigned'].includes(w.status);case'in_progress':return w.bucket==='execution'&&['Started','In Progress'].includes(w.status);case'reviews':return w.is_review;case'attention':return w.is_attention;case'overdue':return w.is_overdue;case'completed':return w.bucket==='completed';default:return true}}
function wcDrill(metric,employee=''){wcV5.metric=metric;wcV5.employee=employee;workcenterTab='overview';populateWorkCenterEmployeeFilter();renderWorkCenter();wcEl('wcResults').scrollIntoView({behavior:'smooth',block:'start'})}
function wcSelectRows(){return workcenterItems.filter(w=>(!wcV5.employee||w.owner_id===wcV5.employee)&&(!wcV5.metric||wcMetricMatch(w,wcV5.metric))&&(workcenterTab==='overview'||(workcenterTab==='attention'?w.is_attention:w.bucket===workcenterTab))&&(workcenterTab!=='reviews'||wcV5.decision!=='mine'||w.requires_my_decision))}
function renderWorkCenter(){
 if(!wcEl('wcRows'))return;const base=workcenterItems.filter(w=>!wcV5.employee||w.owner_id===wcV5.employee);const section=wcSections[workcenterTab]||wcSections.overview;
 if(wcV5.data?.cycle){wcEl('wcCycleLabel').textContent=`${wcText('بداية الدورة','Cycle started')} · ${fmt(wcV5.data.cycle.started_at)}`;if(wcEl('wcError').classList.contains('hidden'))wcEl('wcSyncStatus').textContent=`${wcText('آخر تحديث','Updated')} ${fmt(wcV5.data.as_of)}`;}
 ['wcDailyPlanBtn','wcAddTaskBtn','wcHistoricalReport'].forEach(id=>wcEl(id)?.classList.toggle('hidden',!wcManager()));wcEl('wcAdhocTaskBtn')?.classList.toggle('hidden',wcReadonly());wcEl('wcWorkdayBtn')?.classList.toggle('hidden',wcReadonly());wcEl('wcNotificationsBtn')?.classList.toggle('hidden',wcReadonly());
 wcEl('wcScopeWrap').classList.toggle('hidden',!wcManager());wcEl('wcEmployeeLabel').classList.toggle('hidden',workcenterScope!=='team');
 wcEl('wcMineBtn').setAttribute('aria-pressed',workcenterScope==='mine');wcEl('wcTeamBtn').setAttribute('aria-pressed',workcenterScope==='team');
 document.querySelectorAll('[data-wctab]').forEach(b=>{const selected=b.dataset.wctab===workcenterTab;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;const k=b.dataset.wctab;const count=k==='overview'?base.length:base.filter(w=>k==='attention'?w.is_attention:w.bucket===k).length;b.querySelector('[data-wccount]').textContent=wcNumber(count)});
 wcEl('wcSectionTitle').textContent=wcText(section[0],section[1]);wcEl('wcSectionDescription').textContent=wcText(section[2],section[3]);wcEl('wcCompletionDates').classList.toggle('hidden',workcenterTab!=='completed');
 wcEl('wcDecisionWrap').classList.toggle('hidden',workcenterTab!=='reviews');wcEl('wcAllDecisions').setAttribute('aria-pressed',wcV5.decision==='all');wcEl('wcMyDecisions').setAttribute('aria-pressed',wcV5.decision==='mine');
 wcEl('wcListBtn').setAttribute('aria-pressed',wcV5.view==='list');wcEl('wcBoardBtn').setAttribute('aria-pressed',wcV5.view==='board');
 const metrics=[['ready','جاهز للبدء','Ready to start'],['in_progress','قيد التنفيذ','In progress'],['reviews','مراجعات واعتمادات','Reviews'],['attention','يحتاج تدخلًا','Needs attention'],['overdue','متأخر','Overdue'],['completed','منجز معتمد','Approved completions']];
 wcEl('workcenterSummary').innerHTML=metrics.map(([k,ar,en])=>`<button class="wc-metric ${['attention','overdue'].includes(k)?'wc-alert':''}" aria-pressed="${wcV5.metric===k}" onclick="wcDrill('${k}','${esc(wcV5.employee)}')"><span>${wcText(ar,en)}</span><strong>${wcNumber(base.filter(w=>wcMetricMatch(w,k)).length)}</strong></button>`).join('');
 const rows=wcSelectRows();wcEl('wcResultCount').textContent=`${wcNumber(rows.length)} ${wcText('عمل','items')}${wcV5.metric?' · '+wcText(...metrics.find(x=>x[0]===wcV5.metric).slice(1)):''}${wcV5.employee?' · '+(profiles.find(p=>p.id===wcV5.employee)?.full_name||''):''}`;wcEl('wcClearMetric').classList.toggle('hidden',!wcV5.metric);
 renderTeamOperationsMonitor();
 if(!rows.length){wcEl('wcRows').innerHTML=`<div class="wc-empty"><span class="wc-empty-mark">✓</span><strong>${wcText('لا توجد أعمال في هذا القسم','No work in this section')}</strong><p>${wcV5.data?wcText('القائمة تخص الدورة الجديدة والفلاتر المختارة. السجل السابق محفوظ.','This list reflects the new cycle and selected filters. Previous history is retained.'):wcText('سيظهر العمل بعد اكتمال تحميل البيانات.','Work will appear after data is loaded.')}</p>${wcManager()&&workcenterTab==='overview'?`<button class="btn primary" onclick="openDailyPlan()">${wcText('إعداد خطة اليوم','Plan today')}</button>`:''}</div>`;return;}
 wcEl('wcRows').innerHTML=wcV5.view==='board'?wcBoard(rows):wcTable(rows);
}
function wcTime(w){if(w.status==='Completed')return `<div>${w.completed_at?fmt(w.completed_at):'—'}</div><div class="wc-sub">${wcText('وقت الاعتماد','Approved at')}</div>`;if(!w.due_at)return `<span class="muted">${wcText('لم يحدد موعد','No deadline set')}</span>`;return `<div>${fmt(w.due_at)}</div><div class="wc-sub ${w.is_overdue?'time-negative':''}">${minutesLabel(w.remaining_minutes)}</div>`}
function wcPrimary(w){const priority=['APPROVE_COMPLETION','APPROVE_EXTENSION','APPROVE_PAYMENT_SUPERVISOR','APPROVE_PAYMENT_CFO','EXECUTE_PAYMENT','REGISTER_ACCOUNTING','FINALIZE_POSTING','START','RESUME','COMPLETE','SUBMIT_FOR_REVIEW','RESOLVE_BLOCKER'];return priority.find(a=>(w.available_actions||[]).some(x=>x.action===a))}
function wcActionButtons(w){if(wcReadonly())return `<span class="muted">${wcText('عرض فقط','View only')}</span>`;const a=wcPrimary(w);return `${a?`<button class="btn workcenter-action-primary" data-wc-action="${a}" onclick="openWorkCenterAction('${w.work_item_id}','${a}')">${esc(workCenterActionLabel(a))}</button>`:''}<button class="btn" onclick="openWorkCenterDetail('${w.work_item_id}')">${wcText('التفاصيل','Details')}</button>`}
function wcTable(rows){return `<div class="wc-table-scroll"><table class="wc-list-table" id="workcenterTable"><thead><tr>${[wcText('العمل / المرحلة','Work / stage'),wcText('المسؤول','Owner'),wcText('الحالة','Status'),wcText('الأولوية','Priority'),wcText('الموعد / الإنجاز','Deadline / completion'),wcText('الإجراء التالي','Next action')].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="workcenterBody">${rows.map(w=>`<tr data-work-item="${w.work_item_id}" class="${w.is_overdue?'wc-overdue-row':''}"><td><button class="wc-title-link" onclick="openWorkCenterDetail('${w.work_item_id}')">${esc(w.title)}</button><div class="wc-sub">${esc(displayText(workflowTypeLabel(w.item_type)))}</div></td><td>${esc(w.assignee_name||'—')}<div class="wc-sub">${wcText('المراجع:','Reviewer:')} ${esc(w.reviewer_name||'—')}</div></td><td>${wcStatus(w)}${w.is_overdue?`<div class="wc-sub time-negative">${wcText('تجاوز الموعد','Overdue')}</div>`:''}</td><td>${esc(displayText(w.priority||'عادي'))}</td><td>${wcTime(w)}</td><td><div class="workcenter-actions">${wcActionButtons(w)}</div></td></tr>`).join('')}</tbody></table></div>`}
function wcBoard(rows){return `<div class="wc-board">${['execution','reviews','attention','completed'].map(k=>`<div class="wc-board-col"><h4>${wcText(wcSections[k][0],wcSections[k][1])} · ${wcNumber(rows.filter(w=>w.bucket===k).length)}</h4>${rows.filter(w=>w.bucket===k).map(w=>`<article class="wc-board-card"><button class="wc-title-link" onclick="openWorkCenterDetail('${w.work_item_id}')">${esc(w.title)}</button><p>${esc(w.assignee_name||'—')}</p>${wcStatus(w)}<p>${wcTime(w)}</p><div class="workcenter-actions">${wcActionButtons(w)}</div></article>`).join('')}</div>`).join('')}</div>`}
function renderTeamOperationsMonitor(){const wrap=wcEl('teamOperationsMonitorWrap');if(!wrap)return;wrap.classList.toggle('hidden',!wcManager()||workcenterScope!=='team'||workcenterTab!=='overview'||!!wcV5.metric);wcEl('teamOperationsMonitorBody').innerHTML=teamOperationsMonitor.filter(p=>!wcV5.employee||p.user_id===wcV5.employee).map(p=>`<tr><td><b>${esc(p.full_name)}</b><div class="wc-sub">${esc(displayText(ROLE_LABEL[p.role]||p.role))}</div></td>${['ready','in_progress','reviews','attention','overdue','completed'].map(k=>`<td><button class="wc-metric-link" onclick="wcDrill('${k}','${p.user_id}')">${wcNumber(p[k])}</button></td>`).join('')}<td>${wcPercent(p.quality_avg)}<div class="wc-sub">${wcNumber(p.quality_count)} ${wcText('عمل مقيّم','rated items')}</div></td><td>${wcPercent(p.on_time_rate)}<div class="wc-sub">${wcNumber(p.timed_count)} ${wcText('عمل له موعد','items with deadlines')}</div></td></tr>`).join('')}
function workCenterItemById(id){return workcenterItems.find(w=>w.work_item_id===id)}
async function openWorkCenterDetail(id){
 const w=workCenterItemById(id);if(!w)return;closeWorkCenterDetail();wcV5.drawerFocus=document.activeElement;const token=++wcV5.detailRequest;
 const shell=document.createElement('div');shell.id='wcDetailShell';shell.innerHTML=`<div class="wc-drawer-backdrop" onclick="closeWorkCenterDetail()"></div><aside class="wc-drawer" role="dialog" aria-modal="true" aria-labelledby="wcDetailTitle" tabindex="-1"><div class="wc-drawer-header"><div><div class="wc-kicker">${esc(displayText(workflowTypeLabel(w.item_type)))}</div><h3 id="wcDetailTitle">${esc(w.title)}</h3>${wcStatus(w)}</div><button class="btn" onclick="closeWorkCenterDetail()" aria-label="${wcText('إغلاق','Close')}">✕</button></div><div class="wc-detail-actions">${(w.available_actions||[]).map(a=>`<button class="btn" onclick="closeWorkCenterDetail();openWorkCenterAction('${id}','${esc(a.action)}')">${esc(workCenterActionLabel(a.action))}</button>`).join('')}</div><dl class="wc-detail-grid">${[[wcText('المسؤول','Owner'),w.assignee_name],[wcText('المراجع','Reviewer'),w.reviewer_name],[wcText('وقت الإسناد','Assigned'),w.assigned_at?fmt(w.assigned_at):null],[wcText('موعد التسليم','Deadline'),w.due_at?fmt(w.due_at):null],[wcText('وقت البدء','Started'),w.started_at?fmt(w.started_at):null],[wcText('جودة النتيجة','Quality'),wcPercent(w.quality_score)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v||'—')}</dd></div>`).join('')}</dl>${w.task_description?`<h4>${wcText('المطلوب','Expected output')}</h4><div class="wc-detail-text">${esc(w.task_description)}</div>`:''}${w.blocker_note?`<h4>${wcText('سبب التعثر','Blocker')}</h4><div class="wc-detail-text">${esc(w.blocker_note)}</div>`:''}${w.result_description?`<h4>${wcText('النتيجة المسلّمة','Submitted result')}</h4><div class="wc-detail-text">${esc(w.result_description)}</div>`:''}<div id="wcDetailActivity" aria-live="polite">${wcText('جارٍ تحميل السجل…','Loading history…')}</div></aside>`;
 if(profile?.role==='CFO'&&w.source_type==='task'&&typeof cfoDeleteTaskButton==='function')shell.querySelector('.wc-detail-actions').insertAdjacentHTML('beforeend',cfoDeleteTaskButton(w.source_id));document.body.appendChild(shell);shell.querySelector('aside').focus();shell.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeWorkCenterDetail()}if(e.key==='Tab'){const f=[...shell.querySelectorAll('button,input,select,textarea,a[href]')].filter(x=>!x.disabled);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===shell.querySelector('aside'))){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 try{const {data,error}=await sb.rpc('get_workcenter_detail_v5',{p_work_item_id:id});if(token!==wcV5.detailRequest||!wcEl('wcDetailActivity'))return;if(error)throw error;wcEl('wcDetailActivity').innerHTML=wcDetailActivity(data||{});}catch(e){if(token===wcV5.detailRequest&&wcEl('wcDetailActivity'))wcEl('wcDetailActivity').textContent=wcText('تعذر تحميل التفاصيل: ','Could not load details: ')+e.message;}
}
function closeWorkCenterDetail(){wcV5.detailRequest++;wcEl('wcDetailShell')?.remove();wcV5.drawerFocus?.focus();wcV5.drawerFocus=null;}
function wcDetailActivity(d){const eventNames={STATUS_CHANGED:['تغيرت الحالة','Status changed'],TASK_STARTED:['بدء التنفيذ','Work started'],TASK_SUBMITTED_FOR_REVIEW:['إرسال النتيجة للمراجعة','Submitted for review'],TASK_APPROVED_SCORED:['اعتماد النتيجة وتقييمها','Result approved and scored'],TASK_RETURNED_FOR_REWORK:['إعادة للتصحيح','Returned for rework'],WORK_RETURNED_FOR_REWORK:['إعادة العمل للموظف','Returned to owner'],EXTENSION_REQUESTED:['طلب تمديد','Extension requested'],EXTENSION_APPROVED:['اعتماد التمديد','Extension approved'],EXTENSION_REJECTED:['رفض التمديد','Extension rejected']};return `<h4>${wcText('التعليقات','Comments')}</h4>${(d.comments||[]).map(x=>`<div class="wc-timeline-item"><b>${esc(x.author||'')}</b><div class="wc-detail-text">${esc(x.body)}</div><time>${fmt(x.created_at)}</time></div>`).join('')||`<p class="muted">${wcText('لا توجد تعليقات بعد.','No comments yet.')}</p>`}<h4>${wcText('طلبات التمديد','Extension requests')}</h4>${(d.extensions||[]).map(x=>`<div class="wc-timeline-item"><b>${esc(displayText(x.status))}</b> · ${esc(x.due_date)} ${esc(x.due_time||'')}<div>${esc(x.reason||'')}</div><div>${esc(x.note||'')}</div><time>${fmt(x.created_at)}</time></div>`).join('')||'—'}<h4>${wcText('سجل الإجراءات','Activity history')}</h4>${(d.events||[]).map(x=>{const n=eventNames[x.event_type];const info=x.details||{};return `<div class="wc-timeline-item"><b>${esc(n?wcText(...n):displayText(x.event_type))}</b> · ${esc(x.actor_name||wcText('النظام','System'))}<div>${esc(info.reason||info.note||info.result_description||'')}${info.to?` · ${esc(displayText(info.to))}`:''}${info.quality_score!=null?` · ${Number(info.quality_score)}%`:''}</div><time>${fmt(x.created_at)}</time></div>`}).join('')||'—'}`}
async function submitWorkCenterAction(id,action,payload){if(wcV5.busy)return;wcV5.busy=true;try{const {data,error}=await sb.rpc('try_perform_work_item_action_v5',{p_work_item_id:id,p_action:action,p_payload:payload||{}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||wcText('تعذر تنفيذ الإجراء','Action failed'));closeModal();closeWorkCenterDetail();await reloadAll();await loadWorkCenter();}catch(e){alert(e.message)}finally{wcV5.busy=false}}
const wcOriginalToggleLanguage=toggleLanguage;
toggleLanguage=function(){const filters=workCenterFilters();wcOriginalToggleLanguage();if(wcEl('workcenter')?.dataset.v5==='ready'){wcEl('workcenter').dataset.v5='';wcBuildShell();for(const [id,key] of [['wcSearch','search'],['wcTypeFilter','item_type'],['wcPriorityFilter','priority'],['wcFrom','from'],['wcTo','to']])if(filters[key])wcEl(id).value=filters[key];renderWorkCenter();}};

