// Local browser tests only. The test server substitutes the Supabase CDN with this file.
window.fixtureRole='CFO';window.fixtureError=false;window.fixtureCalls=[];
const fixturePeople=[{id:'00000000-0000-0000-0000-000000000001',full_name:'المدير المالي',role:'CFO'},{id:'00000000-0000-0000-0000-000000000002',full_name:'مشرف الحسابات',role:'Supervisor'},{id:'00000000-0000-0000-0000-000000000003',full_name:'موظف البنوك',role:'BankAccountant'}];
const fixtureNow=new Date().toISOString();
window.fixtureItems=[
 ['1','مطابقة الحساب البنكي','Ready','execution',false,false],
 ['2','مراجعة المستندات','In Progress','execution',false,false],
 ['3','تسوية شهرية للمراجعة','Pending Review','reviews',true,false],
 ['4','استكمال بيانات المورد','Blocked','attention',false,true],
 ['5','تقرير السيولة المعتمد','Completed','completed',false,false],
 ['6','مراجعة حركة الحساب المتأخرة','In Progress','execution',false,true]
].map(([n,title,status,bucket,is_review,is_attention])=>({work_item_id:'10000000-0000-0000-0000-'+n.padStart(12,'0'),source_id:'20000000-0000-0000-0000-'+n.padStart(12,'0'),source_type:'task',title,status,bucket,is_review,is_attention,is_overdue:n==='6',item_type:'MANUAL_TASK',assignee_id:fixturePeople[2].id,owner_id:fixturePeople[2].id,assignee_name:fixturePeople[2].full_name,reviewer_id:fixturePeople[1].id,reviewer_name:fixturePeople[1].full_name,priority:n==='6'?'عالي':'عادي',assigned_at:fixtureNow,started_at:n!=='1'?fixtureNow:null,completed_at:n==='5'?fixtureNow:null,due_at:fixtureNow,remaining_minutes:n==='6'?-90:120,quality_score:n==='5'?92:null,on_time:n==='5'?true:null,requires_my_decision:is_review,task_description:'مطابقة المستندات وتوثيق الفروقات.',result_description:n==='3'?'تمت مطابقة الأرصدة وإرفاق ملخص النتيجة.':null,available_actions:[]}));
function fixtureSnapshot(scope,filters){let items=structuredClone(window.fixtureItems);if(scope==='mine'&&window.fixtureRole==='CFO')items=[];if(filters.search)items=items.filter(x=>x.title.includes(filters.search));if(filters.priority)items=items.filter(x=>x.priority===filters.priority);items.forEach(w=>{const manager=['CFO','Supervisor'].includes(window.fixtureRole);w.available_actions=manager?(w.status==='Pending Review'?[{action:'APPROVE_COMPLETION'},{action:'RETURN_REWORK'}]:[{action:'COMMENT'}]):w.status==='Ready'?[{action:'START'}]:w.status==='In Progress'?[{action:'COMPLETE'},{action:'COMMENT'},{action:'REQUEST_EXTENSION'},{action:'REPORT_BLOCKER'}]:[];});return {cycle:{id:'cycle-test',started_at:fixtureNow,label:'Test'},as_of:fixtureNow,items,summary:{},team:fixturePeople.map(p=>{const r=items.filter(x=>x.owner_id===p.id);return {user_id:p.id,full_name:p.full_name,role:p.role,ready:r.filter(w=>w.status==='Ready').length,in_progress:r.filter(w=>w.status==='In Progress').length,reviews:r.filter(w=>w.is_review).length,attention:r.filter(w=>w.is_attention).length,overdue:r.filter(w=>w.is_overdue).length,completed:r.filter(w=>w.status==='Completed').length,quality_avg:r.some(w=>w.status==='Completed')?92:null,quality_count:r.filter(w=>w.quality_score!=null).length,timed_count:r.filter(w=>w.on_time!=null).length,on_time_rate:r.some(w=>w.on_time)?100:null}})};}
const fixtureClient={
 auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},
 channel:()=>({on(){return this},subscribe(){return this}}),removeChannel(){},
 from(table){const q={select(){return this},eq(){return this},order(){return this},maybeSingle(){return Promise.resolve({data:null})},then(resolve){resolve({data:table==='profiles'?fixturePeople:[],error:null})}};return q},
 async rpc(name,p={}){window.fixtureCalls.push({name,p});if(name==='get_workcenter_dashboard_v5'){if(window.fixtureError)return {error:{message:'Fixture connection error'}};return {data:fixtureSnapshot(p.p_scope,p.p_filters||{})};}if(name==='get_workcenter_detail_v5')return {data:{comments:[{body:'تمت المراجعة الأولية',author:'مشرف الحسابات',created_at:fixtureNow}],extensions:[],events:[{event_type:'TASK_STARTED',actor_name:'موظف البنوك',created_at:fixtureNow,details:{}}]}};if(name==='delete_finance_task_cfo_v7'){if(window.fixtureDeleteError)return {error:{message:'Fixture deletion denied'}};const before=fixtureItems.length;window.fixtureItems=fixtureItems.filter(x=>x.source_id!==p.p_task_id);return {data:{ok:fixtureItems.length<before,task_id:p.p_task_id}};}if(name==='try_perform_work_item_action_v5'){const w=window.fixtureItems.find(x=>x.work_item_id===p.p_work_item_id);if(p.p_action==='START'){w.status='In Progress';w.bucket='execution';}if(['COMPLETE','SUBMIT_FOR_REVIEW'].includes(p.p_action)){w.status='Pending Review';w.bucket='reviews';w.is_review=true;w.result_description=p.p_payload.result_description;}if(p.p_action==='APPROVE_COMPLETION'){w.status='Completed';w.bucket='completed';w.is_review=false;w.quality_score=p.p_payload.quality_score;w.completed_at=fixtureNow;}return {data:{ok:true}};}if(name==='get_task_operational_start_date')return {data:'2026-09-17'};return {data:[],error:null};}
};
window.supabase={createClient:()=>fixtureClient};
window.fixtureNotifications=Array.from({length:35},(_,i)=>({id:'30000000-0000-0000-0000-'+String(i+1).padStart(12,'0'),task_id:'20000000-0000-0000-0000-000000000001',title:i===0?'تعليق جديد على المهمة':'تنبيه تجريبي '+(i+1),message:'يرجى مراجعة التحديث المسجل على المهمة.',notification_type:'TASK_COMMENT',created_at:fixtureNow,read_at:null,scope:'current'}));
window.fixtureNotifications.push({id:'40000000-0000-0000-0000-000000000001',task_id:null,title:'تنبيه تاريخي محفوظ',notification_type:'TASK_ASSIGNED',created_at:fixtureNow,read_at:null,scope:'history'});
const fixtureBaseRpc=fixtureClient.rpc.bind(fixtureClient);
const fixtureBaseFrom=fixtureClient.from.bind(fixtureClient);
fixtureClient.from=function(table){if(table==='tasks'&&window.fixtureTaskVisible){return {select(){return this},eq(){return this},maybeSingle:async()=>({data:{id:fixtureItems[0].source_id,name:'المهمة المرتبطة بالتنبيه',owner_id:fixturePeople[2].id,reviewer_id:fixturePeople[1].id,status:'لم يبدأ',due_date:'2026-09-18',due_time:'17:00',priority:'عادي'}})};}return fixtureBaseFrom(table);};
fixtureClient.rpc=async function(name,p={}){if(name==='get_notification_inbox_v6'){if(window.fixtureInboxError)return {error:{message:'Fixture inbox offline'}};const scoped=window.fixtureNotifications.filter(n=>n.scope===p.p_scope),filtered=scoped.filter(n=>!p.p_unread_only||!n.read_at);return {data:{items:structuredClone(filtered.slice(p.p_offset,p.p_offset+p.p_limit)),total:filtered.length,unread:scoped.filter(n=>!n.read_at).length}};}if(name==='mark_task_notification_read'){if(window.fixtureMarkError)return {error:{message:'Fixture mark denied'}};const n=window.fixtureNotifications.find(n=>n.id===p.p_notification_id);if(n)n.read_at=fixtureNow;return {data:null};}if(name==='get_task_thread')return {data:{comments:[],extensions:[],activity:[]}};return fixtureBaseRpc(name,p);};
window.addEventListener('DOMContentLoaded',async()=>{await window.fixtureSetRole('CFO')});
window.fixtureSetRole=async function(role){window.fixtureRole=role;profile=fixturePeople.find(p=>p.role===role);profiles=fixturePeople;permissionMap={};session={user:{id:profile.id}};authScreen.classList.add('hidden');app.classList.remove('hidden');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById('workcenter').classList.add('active');wcV5.user=null;await loadWorkCenter();};

