from pathlib import Path
import re

p=Path('index.html')
s=p.read_text()
marker='/* FINANCE_OPS_CONTROL_2026_09_14 */'
if marker in s:
    print('already patched')
    raise SystemExit(0)

s=s.replace('.filters>*{width:auto;min-width:160px}', '.filters>*{width:auto;min-width:160px}.column-filter-row th{padding:5px;background:#fff}.column-filter{min-width:105px;width:100%;padding:6px 7px;font-size:11px;border-radius:5px}.task-overdue{background:#fff8f8}.task-control-note{white-space:normal;min-width:180px}.mini-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.mini-kpis .card{padding:11px}.mini-kpis b{font-size:18px;display:block}.plan-table input[type=time]{min-width:120px}@media(max-width:900px){.mini-kpis{grid-template-columns:1fr 1fr}}')

old='<section id="banks" class="section"><div class="row" style="margin-bottom:12px"><h3>السيولة والبنوك</h3><button id="addBankBtn" class="btn primary" type="button" onclick="openBankModal()">+ إضافة حساب</button></div><div class="note" style="margin-bottom:12px">الرصيد المحجوز يُحتسب تلقائياً من المدفوعات غير المنفذة المرتبطة بالحساب البنكي ولا يمكن إدخاله يدويًا.</div><div class="table-wrap"><table><thead><tr><th>الشركة</th><th>البنك</th><th>الحساب</th><th>الرصيد</th><th>المحجوز</th><th>المتاح</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody id="banksBody"></tbody></table></div></section>'
new='<section id="banks" class="section"><div class="row" style="margin-bottom:12px"><h3>السيولة والبنوك</h3><button id="addBankBtn" class="btn primary" type="button" onclick="openBankModal()">+ إضافة حساب</button></div><div class="note" style="margin-bottom:12px">الرصيد المحجوز يُحتسب تلقائياً من المدفوعات غير المنفذة المرتبطة بالحساب البنكي ولا يمكن إدخاله يدويًا.</div><div class="table-wrap"><table><thead><tr><th>الشركة</th><th>البنك</th><th>الحساب</th><th>آخر 4 أرقام</th><th>الرصيد</th><th>المحجوز</th><th>المتاح</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody id="banksBody"></tbody></table></div></section>'
if old not in s: raise SystemExit('banks section anchor missing')
s=s.replace(old,new,1)

old='<section id="tasks" class="section"><div class="row" style="margin-bottom:12px"><h3>المهام</h3><button id="addTaskBtn" class="btn primary" type="button" onclick="openTaskModal()">+ إضافة مهمة</button></div><div class="table-wrap"><table><thead><tr><th>المهمة</th><th>المسؤول</th><th>المراجع</th><th>الموعد</th><th>الأولوية</th><th>الحالة</th></tr></thead><tbody id="tasksBody"></tbody></table></div></section>'
new='<section id="tasks" class="section"><div class="row" style="margin-bottom:12px"><h3>المهام</h3><div class="lang-actions"><button id="dailyPlanBtn" class="btn success" type="button" onclick="openDailyPlan()">خطة اليوم / فتح المهام</button><button id="addTaskBtn" class="btn primary" type="button" onclick="openTaskModal()">+ إضافة مهمة</button></div></div><div id="taskKpis" class="mini-kpis"></div><div class="table-wrap"><table><thead><tr><th>المهمة</th><th>المسؤول</th><th>المراجع</th><th>التاريخ</th><th>الوقت</th><th>الأولوية</th><th>الحالة</th><th>التبرير / التعثر</th><th>إجراء</th></tr></thead><tbody id="tasksBody"></tbody></table></div></section>'
if old not in s: raise SystemExit('tasks section anchor missing')
s=s.replace(old,new,1)

old='<section id="close" class="section"><div class="row" style="margin-bottom:12px"><h3>الإقفال الشهري</h3><button id="addCloseBtn" class="btn primary" type="button" onclick="openCloseModal()">+ إضافة بند إقفال</button></div><div class="table-wrap"><table><thead><tr><th>المسار</th><th>الرمز</th><th>البند</th><th>المسؤول</th><th>الإنجاز</th><th>الحالة</th></tr></thead><tbody id="closeBody"></tbody></table></div></section>'
new='<section id="close" class="section"><div class="row" style="margin-bottom:12px"><h3>الإقفال الشهري</h3><button id="addCloseBtn" class="btn primary" type="button" onclick="openCloseModal()">+ إضافة بند إقفال</button></div><div class="table-wrap"><table><thead><tr><th>المسار</th><th>الرمز</th><th>البند</th><th>المسؤول</th><th>تاريخ الاستحقاق</th><th>الأولوية</th><th>المخرج</th><th>الإنجاز</th><th>الحالة</th></tr></thead><tbody id="closeBody"></tbody></table></div></section>'
if old not in s: raise SystemExit('close section anchor missing')
s=s.replace(old,new,1)

old='<section id="performance" class="section"><div class="row" style="margin-bottom:12px"><h3>أداء الفريق</h3></div><div id="performanceGrid" class="grid g2"></div></section>'
new='<section id="performance" class="section"><div class="row" style="margin-bottom:12px"><h3>أداء الفريق</h3></div><div class="note" style="margin-bottom:12px">المؤشرات أدناه تُحتسب مباشرة من المهام الفعلية ودورة الإقفال، ولا تعتمد على تقييم يدوي أو درجة تقديرية.</div><div class="table-wrap"><table><thead><tr><th>الموظف</th><th>الدور</th><th>مهام اليوم</th><th>مكتمل اليوم</th><th>متأخر الآن</th><th>تبريرات معلقة</th><th>إنجاز الشهر</th><th>الإنجاز في الموعد</th><th>إنجاز الإقفال</th></tr></thead><tbody id="performanceBody"></tbody></table></div></section>'
if old not in s: raise SystemExit('performance section anchor missing')
s=s.replace(old,new,1)

anchor='const I18N_EN_AR=Object.fromEntries(Object.entries(I18N_AR_EN).map(([a,e])=>[e,a]));'
additions='''I18N_AR_EN["آخر 4 أرقام"]="Last 4 Digits";\nI18N_AR_EN["خطة اليوم / فتح المهام"]="Daily Plan / Release Tasks";\nI18N_AR_EN["الوقت"]="Time";\nI18N_AR_EN["التبرير / التعثر"]="Justification / Blocker";\nI18N_AR_EN["طلب تبرير"]="Request Justification";\nI18N_AR_EN["إضافة تبرير"]="Add Justification";\nI18N_AR_EN["بدء"]="Start";\nI18N_AR_EN["إكمال"]="Complete";\nI18N_AR_EN["مفتوحة"]="Released";\nI18N_AR_EN["تبرير مطلوب"]="Justification Required";\nI18N_AR_EN["مهام اليوم"]="Today Tasks";\nI18N_AR_EN["مكتمل اليوم"]="Completed Today";\nI18N_AR_EN["متأخر الآن"]="Overdue Now";\nI18N_AR_EN["تبريرات معلقة"]="Pending Justifications";\nI18N_AR_EN["إنجاز الشهر"]="Month Completion";\nI18N_AR_EN["الإنجاز في الموعد"]="On-time Completion";\nI18N_AR_EN["إنجاز الإقفال"]="Close Completion";\nI18N_AR_EN["الموظف"]="Employee";\nI18N_AR_EN["فلترة"]="Filter";\nI18N_AR_EN["لا توجد عهد مسجلة حتى الآن."]="No imprest records have been registered yet.";\nI18N_AR_EN["لا توجد بيانات في مصفوفة المسؤوليات."]="No ownership matrix records are available.";\nI18N_AR_EN["لا توجد مهام إقفال للدورة الحالية."]="No monthly close tasks are available for the current cycle.";\nI18N_AR_EN["المؤشرات أدناه تُحتسب مباشرة من المهام الفعلية ودورة الإقفال، ولا تعتمد على تقييم يدوي أو درجة تقديرية."]="These indicators are calculated directly from actual tasks and the close cycle; they do not use manual or estimated scores.";\n'''
if anchor not in s: raise SystemExit('i18n anchor missing')
s=s.replace(anchor,additions+anchor,1)

old='addTaskBtn.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));addExceptionBtn.classList.toggle("hidden",profile.role!=="CFO")'
new='addTaskBtn.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));dailyPlanBtn.classList.toggle("hidden",profile.role!=="Supervisor");addExceptionBtn.classList.toggle("hidden",profile.role!=="CFO")'
if old not in s: raise SystemExit('access anchor missing')
s=s.replace(old,new,1)

reload_re=r'async function reloadAll\(\)\{const \[pr,bk,py,tk,ex,cl,im,pf,ow\]=await Promise\.all\(\[.*?\]\);profiles=pr\.data\|\|\[\];banks=bk\.data\|\|\[\];payments=py\.data\|\|\[\];tasks=tk\.data\|\|\[\];exceptions=ex\.data\|\|\[\];closeTasks=cl\.data\|\|\[\];imprest=im\.data\|\|\[\];performance=pf\.data\|\|\[\];ownership=ow\.data\|\|\[\];renderAll\(\)\}'
reload_new='''async function reloadAll(){const [pr,bk,py,tk,ex,cl,im,pf,ow]=await Promise.all([sb.from("profiles").select("id,email,full_name,role").eq("active",true),sb.from("bank_liquidity").select("*").order("company"),sb.from("payments").select("*,bank_accounts(company,bank_name,account_name)").order("created_at",{ascending:false}),sb.from("tasks").select("*,owner:profiles!tasks_owner_id_fkey(full_name),reviewer:profiles!tasks_reviewer_id_fkey(full_name)").order("due_date",{ascending:false}).order("created_at",{ascending:false}),sb.from("exceptions").select("*,owner:profiles!exceptions_owner_id_fkey(full_name),leave_delegations(*,absent:profiles!leave_delegations_absent_user_id_fkey(full_name),substitute:profiles!leave_delegations_substitute_user_id_fkey(full_name))").order("created_at",{ascending:false}),sb.from("monthly_close_tasks").select("*,owner:profiles!monthly_close_tasks_owner_id_fkey(full_name)").order("due_date").order("code"),sb.from("imprest_funds").select("*,custodian:profiles!imprest_funds_custodian_id_fkey(full_name)").order("created_at",{ascending:false}),sb.rpc("get_finance_team_performance"),sb.from("ownership_matrix").select("*").order("sort_order")]);profiles=pr.data||[];banks=bk.data||[];payments=py.data||[];tasks=tk.data||[];exceptions=ex.data||[];closeTasks=cl.data||[];imprest=im.data||[];performance=pf.data||[];ownership=ow.data||[];renderAll()}'''
s,n=re.subn(reload_re,reload_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'reload patch failed {n}')

s=s.replace('function renderAll(){renderBanks();renderPayments();renderTasks();renderClose();renderImprest();renderPerformance();renderOwnership();renderExceptions();renderDashboard();applyLanguage()}', 'function renderAll(){renderBanks();renderPayments();renderTasks();renderClose();renderImprest();renderPerformance();renderOwnership();renderExceptions();renderDashboard();installTableFilters();applyLanguage()}')

old='function renderDashboard(){const bal=banks.reduce((s,b)=>s+Number(b.balance||0),0),res=banks.reduce((s,b)=>s+Number(b.reserved_balance||0),0);kpiBalance.textContent=money(bal);kpiReserved.textContent=money(res);kpiAvailable.textContent=money(bal-res);kpiCfo.textContent=payments.filter(p=>p.supervisor_status==="موافق"&&p.cfo_status==="معلق").length;dashboardAlerts.textContent="لا توجد تنبيهات حالية."}'
new='''function renderDashboard(){const bal=banks.reduce((s,b)=>s+Number(b.balance||0),0),res=banks.reduce((s,b)=>s+Number(b.reserved_balance||0),0);kpiBalance.textContent=money(bal);kpiReserved.textContent=money(res);kpiAvailable.textContent=money(bal-res);kpiCfo.textContent=payments.filter(p=>p.supervisor_status==="موافق"&&p.cfo_status==="معلق").length;const overdue=tasks.filter(isTaskOverdue).filter(t=>t.status!=="مكتمل").length,justify=tasks.filter(taskJustificationRequired).length;dashboardAlerts.innerHTML=overdue||justify?`${displayText('متأخر الآن')}: <b>${overdue}</b> &nbsp; | &nbsp; ${displayText('تبريرات معلقة')}: <b>${justify}</b>`:displayText('لا توجد تنبيهات حالية.')}'''
if old not in s: raise SystemExit('dashboard anchor missing')
s=s.replace(old,new,1)

bank_re=r'function renderBanks\(\)\{.*?\}\nfunction openBankModal'
bank_new='''function maskAccountNo(v){const x=String(v||'').replace(/\\s+/g,'');return x?`•••• ${esc(x.slice(-4))}`:'—'}\nfunction renderBanks(){const canDelete=["CFO","Supervisor","BankAccountant"].includes(profile.role);banksBody.innerHTML=banks.map(b=>`<tr><td>${esc(b.company)}</td><td>${esc(b.bank_name)}</td><td>${esc(b.account_name)}</td><td>${maskAccountNo(b.account_no)}</td><td>${moneyHtml(b.balance)}</td><td>${moneyHtml(b.reserved_balance)}</td><td>${moneyHtml(b.available_balance)}</td><td>${fmt(b.updated_at)}</td><td><button class="btn" onclick="openBankModal('${b.id}')">${displayText('تعديل')}</button>${canDelete?` <button class="btn danger" onclick="deleteBankAccount('${b.id}')">${displayText('حذف')}</button>`:''}</td></tr>`).join("")||`<tr><td colspan="9" class="muted">—</td></tr>`}\nfunction openBankModal'''
s,n=re.subn(bank_re,bank_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'bank patch failed {n}')

task_re=r'function renderTasks\(\)\{.*?\}\nfunction openTaskModal'
task_new=r'''function riyadhToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function taskDeadline(t){if(!t.due_date)return null;return new Date(`${t.due_date}T${t.due_time||'23:59:59'}+03:00`)}
function isTaskOverdue(t){const d=taskDeadline(t);return !!d&&new Date()>d&&t.status!=="مكتمل"&&!t.completed_at}
function taskJustificationRequired(t){return (isTaskOverdue(t)||!!t.justification_requested_at)&&!String(t.delay_justification||'').trim()&&t.status!=="مكتمل"}
function taskActionHtml(t){const a=[],mine=t.owner_id===profile.id;if(mine&&t.opened_at&&t.status!=="مكتمل"){if(t.status!=="قيد التنفيذ")a.push(`<button class="btn" onclick="startTask('${t.id}')">${displayText('بدء')}</button>`);a.push(`<button class="btn success" onclick="completeTask('${t.id}')">${displayText('إكمال')}</button>`)}if(mine&&taskJustificationRequired(t))a.push(`<button class="btn danger" onclick="submitTaskJustification('${t.id}')">${displayText('إضافة تبرير')}</button>`);if(profile.role==="Supervisor"&&t.status!=="مكتمل"&&(isTaskOverdue(t)||t.opened_at))a.push(`<button class="btn danger" onclick="requestTaskJustification('${t.id}')">${displayText('طلب تبرير')}</button>`);return a.join(' ')||'—'}
function renderTasks(){const today=riyadhToday(),todayRows=tasks.filter(t=>t.due_date===today),done=todayRows.filter(t=>t.status==="مكتمل"||t.completed_at).length,over=todayRows.filter(isTaskOverdue).length,just=todayRows.filter(taskJustificationRequired).length;taskKpis.innerHTML=`<div class="card"><span class="muted">${displayText('مهام اليوم')}</span><b>${todayRows.length}</b></div><div class="card"><span class="muted">${displayText('مكتمل اليوم')}</span><b>${done}</b></div><div class="card"><span class="muted">${displayText('متأخر الآن')}</span><b>${over}</b></div><div class="card"><span class="muted">${displayText('تبريرات معلقة')}</span><b>${just}</b></div>`;tasksBody.innerHTML=tasks.map(t=>{const note=taskJustificationRequired(t)?displayText('تبرير مطلوب'):(t.delay_justification||t.justification_request_note||'—');return `<tr class="${isTaskOverdue(t)?'task-overdue':''}"><td>${esc(t.name)}</td><td>${esc(t.owner?.full_name||"—")}</td><td>${esc(t.reviewer?.full_name||"—")}</td><td>${esc(t.due_date||"—")}</td><td>${esc(t.due_time?String(t.due_time).slice(0,5):"—")}</td><td>${badge(t.priority||"عادي")}</td><td>${badge(t.status||"لم يبدأ")}${t.opened_at&&t.status==="لم يبدأ"?` ${badge('مفتوحة')}`:''}</td><td class="task-control-note">${esc(note)}</td><td>${taskActionHtml(t)}</td></tr>`}).join("")||`<tr><td colspan="9" class="muted">—</td></tr>`}
function openDailyPlan(){if(profile.role!=="Supervisor")return;const today=riyadhToday(),rows=tasks.filter(t=>t.frequency==='يومي'&&t.due_date===today&&t.status!=="مكتمل");if(!rows.length){alert(currentLang==='en'?'No daily tasks are available for today.':'لا توجد مهام يومية متاحة لليوم.');return}const html=rows.map(t=>`<tr><td><input type="checkbox" class="plan-check" data-id="${t.id}" checked></td><td>${esc(t.owner?.full_name||'—')}</td><td style="white-space:normal">${esc(t.name)}</td><td>${badge(t.priority||'عادي')}</td><td><input type="time" class="plan-time" data-id="${t.id}" value="${t.due_time?String(t.due_time).slice(0,5):''}"></td></tr>`).join('');showModal(displayText('خطة اليوم / فتح المهام'),`<div class="note" style="margin-bottom:10px">${currentLang==='en'?'Select the tasks to release and set a due time for each selected task.':'حدد المهام التي سيتم فتحها اليوم وضع موعد الاستحقاق لكل مهمة قبل توجيه الفريق.'}</div><div class="table-wrap"><table class="plan-table"><thead><tr><th>✓</th><th>${displayText('المسؤول')}</th><th>${displayText('المهمة')}</th><th>${displayText('الأولوية')}</th><th>${displayText('الوقت')}</th></tr></thead><tbody>${html}</tbody></table></div><div class="row" style="margin-top:14px"><button class="btn success" onclick="saveDailyPlan()">${currentLang==='en'?'Release selected tasks':'فتح المهام المحددة'}</button></div>`)}
async function saveDailyPlan(){const items=[];document.querySelectorAll('.plan-check:checked').forEach(c=>{const id=c.dataset.id,time=document.querySelector(`.plan-time[data-id="${id}"]`)?.value||'';items.push({id,due_time:time})});if(!items.length)return alert(currentLang==='en'?'Select at least one task.':'حدد مهمة واحدة على الأقل.');if(items.some(x=>!x.due_time))return alert(currentLang==='en'?'Due time is required for every selected task.':'يجب تحديد وقت الاستحقاق لكل مهمة محددة.');const {data,error}=await sb.rpc('supervisor_open_daily_plan',{p_items:items});if(error)return alert(error.message);closeModal();await reloadAll();alert(currentLang==='en'?`${data} tasks released.`:`تم فتح ${data} مهمة وتوجيهها للفريق.`)}
async function startTask(id){const {error}=await sb.rpc('start_finance_task',{p_task_id:id});if(error)return alert(error.message);await reloadAll()}
async function submitTaskJustification(id){const text=prompt(currentLang==='en'?'Enter the required justification:':'اكتب التبرير المطلوب للتأخير أو التعثر:');if(!text||!text.trim())return;const {error}=await sb.rpc('submit_task_justification',{p_task_id:id,p_justification:text.trim()});if(error)return alert(error.message);await reloadAll()}
async function requestTaskJustification(id){const note=prompt(currentLang==='en'?'Reason/note for requesting justification (optional):':'سبب أو ملاحظة طلب التبرير (اختياري):')||'';const {error}=await sb.rpc('request_task_justification',{p_task_id:id,p_note:note});if(error)return alert(error.message);await reloadAll()}
async function completeTask(id){let justification=null;const t=tasks.find(x=>x.id===id);if(t&&taskJustificationRequired(t)){justification=prompt(currentLang==='en'?'This task is overdue or has a justification request. Enter justification before completion:':'هذه المهمة متأخرة أو عليها طلب تبرير. يجب إدخال التبرير قبل الإكمال:');if(!justification||!justification.trim())return}let {error}=await sb.rpc('complete_finance_task',{p_task_id:id,p_justification:justification});if(error&&String(error.message||'').includes('DELAY_JUSTIFICATION_REQUIRED')){justification=prompt(currentLang==='en'?'Justification is mandatory before completion:':'التبرير إلزامي قبل إكمال المهمة:');if(!justification||!justification.trim())return;({error}=await sb.rpc('complete_finance_task',{p_task_id:id,p_justification:justification.trim()}))}if(error)return alert(error.message);await reloadAll()}
function openTaskModal'''
s,n=re.subn(task_re,task_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'task patch failed {n}')

s=s.replace('${input("t_due","الموعد","","date")}${select("t_priority"', '${input("t_due","الموعد","","date")}${input("t_due_time","الوقت","","time")}${select("t_priority"',1)
s=s.replace('due_date:val("t_due")||null,priority:val("t_priority")', 'due_date:val("t_due")||null,due_time:val("t_due_time")||null,priority:val("t_priority")',1)

close_re=r'function renderClose\(\)\{.*?\}\nfunction openCloseModal'
close_new='''function renderClose(){closeBody.innerHTML=closeTasks.map(x=>`<tr><td>${esc(x.track)}</td><td>${esc(x.code||"—")}</td><td>${esc(x.name)}</td><td>${esc(x.owner?.full_name||"—")}</td><td>${esc(x.due_date||"—")}</td><td>${badge(x.priority||"عادي")}</td><td style="white-space:normal">${esc(x.output||"—")}</td><td>${Number(x.progress||0)}%</td><td>${badge(x.status)}</td></tr>`).join("")||`<tr><td colspan="9" class="muted">${displayText('لا توجد مهام إقفال للدورة الحالية.')}</td></tr>`}\nfunction openCloseModal'''
s,n=re.subn(close_re,close_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'close render patch failed {n}')

imprest_re=r'function renderImprest\(\)\{.*?\}\nfunction openImprestModal'
imprest_new='''function renderImprest(){imprestBody.innerHTML=imprest.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.company)}</td><td>${esc(x.name)}</td><td>${esc(x.custodian?.full_name||"—")}</td><td>${moneyHtml(x.balance)}</td><td>${moneyHtml(x.unsettled)}</td><td>${Number(x.aging||0)} يوم</td><td>${badge(x.status)}</td></tr>`).join("")||`<tr><td colspan="8" class="muted">${displayText('لا توجد عهد مسجلة حتى الآن.')}</td></tr>`}\nfunction openImprestModal'''
s,n=re.subn(imprest_re,imprest_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'imprest render patch failed {n}')

perf_re=r'function renderPerformance\(\)\{.*?\}\nfunction renderOwnership'
perf_new='''function renderPerformance(){performanceBody.innerHTML=performance.map(x=>`<tr><td>${esc(x.full_name||"—")}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role||""))}</td><td>${Number(x.today_total||0)}</td><td>${Number(x.today_completed||0)}</td><td>${Number(x.today_overdue||0)}</td><td>${Number(x.pending_justifications||0)}</td><td>${Number(x.month_completion_rate||0).toFixed(1)}%</td><td>${Number(x.tracked_on_time_rate||0).toFixed(1)}%</td><td>${Number(x.close_completion_rate||0).toFixed(1)}%</td></tr>`).join("")||`<tr><td colspan="9" class="muted">${displayText('لا توجد بيانات أداء بعد.')}</td></tr>`}\nfunction renderOwnership'''
s,n=re.subn(perf_re,perf_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'performance patch failed {n}')

old='function renderOwnership(){ownershipBody.innerHTML=ownership.map(x=>`<tr><td>${esc(x.process)}</td><td>${esc(x.activity)}</td><td>${esc(x.frequency||"—")}</td><td>${esc(x.owner_name)}</td><td>${esc(x.reviewer_name||"—")}</td><td>${esc(x.approver_name||"—")}</td><td>${esc(x.output||"—")}</td></tr>`).join("")}'
new='function renderOwnership(){ownershipBody.innerHTML=ownership.map(x=>`<tr><td>${esc(x.process)}</td><td>${esc(x.activity)}</td><td>${esc(x.frequency||"—")}</td><td>${esc(x.owner_name)}</td><td>${esc(x.reviewer_name||"—")}</td><td>${esc(x.approver_name||"—")}</td><td style="white-space:normal">${esc(x.output||"—")}</td></tr>`).join("")||`<tr><td colspan="7" class="muted">${displayText(\'لا توجد بيانات في مصفوفة المسؤوليات.\')}</td></tr>`}'
if old not in s: raise SystemExit('ownership anchor missing')
s=s.replace(old,new,1)

filter_code=r'''
const tableFilterState={};
function installTableFilters(){document.querySelectorAll('.table-wrap table').forEach((table,idx)=>{if(!table.id)table.id=`sanamTable${idx}`;const head=table.tHead;if(!head||!head.rows.length)return;if(head.querySelector('.column-filter-row'))return;const row=document.createElement('tr');row.className='column-filter-row';[...head.rows[0].cells].forEach((th,i)=>{const c=document.createElement('th'),inp=document.createElement('input');inp.className='column-filter';inp.type='search';inp.placeholder=currentLang==='en'?'Filter':'فلترة';inp.dataset.col=i;inp.value=(tableFilterState[table.id]||{})[i]||'';inp.addEventListener('input',()=>{tableFilterState[table.id]=tableFilterState[table.id]||{};tableFilterState[table.id][i]=inp.value;applyTableFilters(table)});c.appendChild(inp);row.appendChild(c)});head.appendChild(row);applyTableFilters(table)})}
function applyTableFilters(table){const filters=[...table.querySelectorAll('.column-filter-row input')].map(x=>String(x.value||'').trim().toLowerCase());[...table.tBodies].flatMap(b=>[...b.rows]).forEach(r=>{const ok=filters.every((f,i)=>!f||String(r.cells[i]?.innerText||'').toLowerCase().includes(f));r.style.display=ok?'':'none'})}
'''
init_anchor='async function init(){'
if init_anchor not in s: raise SystemExit('init anchor missing')
s=s.replace(init_anchor,filter_code+'\n'+init_anchor,1)

s=s.replace('</script>',marker+'\n</script>',1)
p.write_text(s)
print('patch complete')
