from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
marker='/* OPS_CONTROL_V2_2026_09_14 */'
if marker in s:
    print('already patched')
    raise SystemExit(0)
s=s.replace('/* DAILY_PLAN_ASSIGNMENT_2026_09_14 */','/* DAILY_PLAN_ASSIGNMENT_2026_09_14 */\n'+marker,1)

# Styles: Business Central-style header filter arrows and operations control widgets.
style_anchor='.column-filter-row th{padding:5px;background:#fff}.column-filter{min-width:105px;width:100%;padding:6px 7px;font-size:11px;border-radius:5px}'
style_new='.filter-head{display:flex;align-items:center;justify-content:space-between;gap:5px}.filter-arrow{border:0;background:transparent;padding:1px 4px;cursor:pointer;color:#667085;font-size:11px}.filter-arrow.active{color:var(--blue);font-weight:700}.filter-popover{position:fixed;z-index:12000;width:260px;max-height:360px;overflow:auto;background:#fff;border:1px solid var(--border);border-radius:8px;box-shadow:0 12px 28px rgba(15,39,64,.18);padding:10px}.filter-popover .option{display:flex;align-items:center;gap:7px;padding:4px 2px;font-size:12px}.filter-popover .option input{width:auto}.filter-actions{display:flex;gap:6px;justify-content:flex-end;margin-top:8px}.saved-views{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 12px}.view-chip{border:1px solid var(--border);background:#fff;padding:6px 9px;border-radius:999px;cursor:pointer;font-size:12px}.view-chip.active{background:var(--nav);color:#fff;border-color:var(--nav)}.util-bar{height:8px;border-radius:99px;background:#eef2f6;overflow:hidden;min-width:110px}.util-bar>span{display:block;height:100%;background:var(--blue)}.ops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.ops-grid .card{padding:11px}.link-metric{border:0;background:transparent;color:var(--blue);cursor:pointer;text-decoration:underline;padding:0;font-weight:700}.severity-critical{font-weight:700;color:var(--red)}.severity-high{font-weight:700;color:var(--amber)}'
if style_anchor not in s: raise SystemExit('style anchor missing')
s=s.replace(style_anchor,style_new,1)

# Navigation.
nav_anchor='<button class="nav" data-page="tasks">المهام</button><button class="nav" data-page="close">'
nav_new='<button class="nav" data-page="tasks">المهام</button><button class="nav" data-page="control">مركز التحكم اليومي</button><button class="nav" data-page="workload">عبء العمل والطاقة</button><button class="nav" data-page="escalations">التعثر والتصعيد</button><button class="nav" data-page="automation">صحة الأتمتة</button><button class="nav" data-page="close">'
if nav_anchor not in s: raise SystemExit('nav anchor missing')
s=s.replace(nav_anchor,nav_new,1)

# Replace tasks section and insert operations sections.
old_tasks=re.search(r'<section id="tasks" class="section">.*?</section>\n<section id="close"',s,re.S)
if not old_tasks: raise SystemExit('tasks section block missing')
new_tasks='''<section id="tasks" class="section"><div class="row" style="margin-bottom:12px"><h3>المهام</h3><div class="lang-actions"><button id="dailyPlanBtn" class="btn success" type="button" onclick="openDailyPlan()">خطة اليوم / فتح المهام</button><button id="addTaskBtn" class="btn primary" type="button" onclick="openTaskModal()">+ إضافة مهمة</button></div></div><div id="savedViews" class="saved-views"></div><div id="taskKpis" class="mini-kpis"></div><div class="table-wrap"><table id="tasksTable"><thead><tr><th>المهمة</th><th>المسؤول</th><th>المراجع</th><th>التاريخ</th><th>التكرار</th><th>الوقت</th><th>الأولوية</th><th>الحالة</th><th>التبرير / التعثر</th><th>إجراء</th></tr></thead><tbody id="tasksBody"></tbody></table></div></section>
<section id="control" class="section"><div class="row" style="margin-bottom:12px"><h3>مركز التحكم اليومي للمشرف</h3><button class="btn" onclick="reloadAll()">تحديث</button></div><div id="controlKpis" class="ops-grid"></div><div class="table-wrap"><table id="controlTable"><thead><tr><th>الموظف</th><th>الدور</th><th>يعمل الآن على</th><th>الحالة</th><th>الموعد التالي</th><th>المتبقي</th><th>مهام اليوم</th><th>المكتمل</th><th>المتأخر</th><th>التعثر</th><th>بانتظار المراجعة</th><th>تبرير مطلوب</th></tr></thead><tbody id="controlBody"></tbody></table></div></section>
<section id="workload" class="section"><div class="row" style="margin-bottom:12px"><h3>عبء العمل والطاقة الاستيعابية</h3><button id="capacityBtn" class="btn primary" onclick="openCapacitySettings()">إعداد الطاقة</button></div><div class="note" style="margin-bottom:12px">الطاقة الاستيعابية لا تُفترض تلقائيًا؛ يحددها المدير المالي أو المشرف لكل موظف بعدد المهام اليومية المقبول.</div><div class="table-wrap"><table id="workloadTable"><thead><tr><th>الموظف</th><th>الدور</th><th>الطاقة اليومية</th><th>المهام المفتوحة اليوم</th><th>حرجة</th><th>عالية</th><th>متأخرة</th><th>بانتظار المراجعة</th><th>متعثر</th><th>الاستخدام</th></tr></thead><tbody id="workloadBody"></tbody></table></div></section>
<section id="escalations" class="section"><div class="row" style="margin-bottom:12px"><h3>مركز التعثر والتصعيد</h3><button class="btn" onclick="reloadAll()">تحديث</button></div><div class="note" style="margin-bottom:12px">يظهر هنا فقط ما يحتاج تدخلًا: تعثر، تأخير، طلب تبرير، أو مهمة بانتظار المراجعة.</div><div class="table-wrap"><table id="escalationTable"><thead><tr><th>الخطورة</th><th>النوع</th><th>المهمة</th><th>المسؤول</th><th>الأولوية</th><th>الحالة</th><th>الموعد</th><th>منذ</th><th>التفاصيل</th><th>إجراء</th></tr></thead><tbody id="escalationBody"></tbody></table></div></section>
<section id="automation" class="section"><div class="row" style="margin-bottom:12px"><h3>صحة الأتمتة</h3><button class="btn" onclick="reloadAll()">تحديث</button></div><div class="note" style="margin-bottom:12px">مراقبة تشغيل توليد المهام اليومية والإقفال الشهري، آخر نتيجة، التشغيل القادم، وأي سجلات متوقعة لم يتم توليدها.</div><div class="table-wrap"><table id="automationTable"><thead><tr><th>الأتمتة</th><th>الحالة</th><th>الجدول</th><th>آخر تشغيل</th><th>نتيجة آخر تشغيل</th><th>التشغيل القادم</th><th>مفقود</th><th>التفاصيل</th></tr></thead><tbody id="automationBody"></tbody></table></div></section>
<section id="close"'''
s=s[:old_tasks.start()]+new_tasks+s[old_tasks.end():]

# Performance table includes pending review.
perf_old='<th>متأخر الآن</th><th>تبريرات معلقة</th><th>إنجاز الشهر</th>'
perf_new='<th>متأخر الآن</th><th>تبريرات معلقة</th><th>بانتظار المراجعة</th><th>إنجاز الشهر</th>'
if perf_old not in s: raise SystemExit('performance header anchor missing')
s=s.replace(perf_old,perf_new,1)

# State arrays.
state_old='let session=null,profile=null,profiles=[],banks=[],payments=[],tasks=[],exceptions=[],closeTasks=[],imprest=[],performance=[],ownership=[];'
state_new='let session=null,profile=null,profiles=[],banks=[],payments=[],tasks=[],exceptions=[],closeTasks=[],imprest=[],performance=[],ownership=[],controlCenter=[],workload=[],escalations=[],automationHealth=[];let activeTaskView=localStorage.getItem("sanam_task_view")||"all",closeQuickView=false;'
if state_old not in s: raise SystemExit('state anchor missing')
s=s.replace(state_old,state_new,1)

# Page access.
access_re=r'const PAGE_ACCESS=\{CFO:\[.*?\],Supervisor:\[.*?\],BankAccountant:\[.*?\],GLAccountant:\[.*?\],ARAccountant:\[.*?\],APAccountant:\[.*?\]\};'
access_new='const PAGE_ACCESS={CFO:["dashboard","banks","payments","posted","tasks","control","workload","escalations","automation","close","imprest","performance","ownership","exceptions","audit"],Supervisor:["dashboard","banks","payments","posted","tasks","control","workload","escalations","automation","close","imprest","performance","ownership","exceptions"],BankAccountant:["dashboard","banks","payments","posted","tasks","close","imprest","exceptions"],GLAccountant:["dashboard","payments","posted","tasks","close","exceptions"],ARAccountant:["dashboard","tasks","close","performance","exceptions"],APAccountant:["dashboard","payments","posted","tasks","close","imprest","performance","exceptions"]};'
s,n=re.subn(access_re,access_new,s,count=1)
if n!=1: raise SystemExit('page access patch failed')

# Translations.
i18n_anchor='const I18N_EN_AR=Object.fromEntries(Object.entries(I18N_AR_EN).map(([a,e])=>[e,a]));'
adds='''I18N_AR_EN["مركز التحكم اليومي"]="Daily Control Center";I18N_AR_EN["مركز التحكم اليومي للمشرف"]="Supervisor Daily Control Center";I18N_AR_EN["عبء العمل والطاقة"]="Workload & Capacity";I18N_AR_EN["عبء العمل والطاقة الاستيعابية"]="Workload & Capacity";I18N_AR_EN["التعثر والتصعيد"]="Blockers & Escalations";I18N_AR_EN["مركز التعثر والتصعيد"]="Blocker & Escalation Center";I18N_AR_EN["صحة الأتمتة"]="Automation Health";I18N_AR_EN["يعمل الآن على"]="Working Now";I18N_AR_EN["الموعد التالي"]="Next Due";I18N_AR_EN["المتبقي"]="Remaining";I18N_AR_EN["التعثر"]="Blockers";I18N_AR_EN["بانتظار المراجعة"]="Awaiting Review";I18N_AR_EN["تبرير مطلوب"]="Justification Required";I18N_AR_EN["الطاقة اليومية"]="Daily Capacity";I18N_AR_EN["المهام المفتوحة اليوم"]="Open Today";I18N_AR_EN["حرجة"]="Critical";I18N_AR_EN["عالية"]="High";I18N_AR_EN["متعثر"]="Blocked";I18N_AR_EN["الاستخدام"]="Utilization";I18N_AR_EN["إعداد الطاقة"]="Set Capacity";I18N_AR_EN["الخطورة"]="Severity";I18N_AR_EN["منذ"]="Age";I18N_AR_EN["التفاصيل"]="Details";I18N_AR_EN["الأتمتة"]="Automation";I18N_AR_EN["الجدول"]="Schedule";I18N_AR_EN["آخر تشغيل"]="Last Run";I18N_AR_EN["نتيجة آخر تشغيل"]="Last Result";I18N_AR_EN["التشغيل القادم"]="Next Run";I18N_AR_EN["مفقود"]="Missing";I18N_AR_EN["كل المهام"]="All Tasks";I18N_AR_EN["متأخر"]="Overdue";I18N_AR_EN["ينتظر مراجعة المشرف"]="Awaiting Supervisor Review";I18N_AR_EN["عاجل"]="Urgent";I18N_AR_EN["إقفال D+"]="Close D+";I18N_AR_EN["مهامي فقط"]="My Tasks";I18N_AR_EN["إرسال للمراجعة"]="Submit for Review";I18N_AR_EN["اعتماد المهمة"]="Approve Task";I18N_AR_EN["إعادة للعمل"]="Return to Work";I18N_AR_EN["تسجيل تعثر"]="Mark Blocker";I18N_AR_EN["إزالة التعثر"]="Clear Blocker";I18N_AR_EN["قيد المراجعة"]="Under Review";'''
if i18n_anchor not in s: raise SystemExit('i18n anchor missing')
s=s.replace(i18n_anchor,adds+i18n_anchor,1)

# Replace old input-row table filtering with header dropdown arrows.
filt_re=r'const tableFilterState=\{\};.*?async function init\(\)'
filt_new=r'''const tableFilterState={};let filterPopover=null;
function installTableFilters(){document.querySelectorAll('.table-wrap table').forEach((table,idx)=>{if(!table.id)table.id=`sanamTable${idx}`;const head=table.tHead;if(!head||!head.rows.length)return;[...head.rows[0].cells].forEach((th,i)=>{if(!th.querySelector('.filter-arrow')){const label=document.createElement('span');while(th.firstChild)label.appendChild(th.firstChild);const wrap=document.createElement('div');wrap.className='filter-head';const btn=document.createElement('button');btn.type='button';btn.className='filter-arrow';btn.textContent='▾';btn.title=currentLang==='en'?'Filter':'فلترة';btn.onclick=e=>{e.stopPropagation();openHeaderFilter(table,i,btn)};wrap.appendChild(label);wrap.appendChild(btn);th.appendChild(wrap)}});applyTableFilters(table)})}
function closeHeaderFilter(){if(filterPopover){filterPopover.remove();filterPopover=null}}
function openHeaderFilter(table,col,btn){closeHeaderFilter();const all=[...table.tBodies].flatMap(b=>[...b.rows]).map(r=>String(r.cells[col]?.innerText||'').trim()).filter(Boolean);const vals=[...new Set(all)].sort((a,b)=>a.localeCompare(b,currentLang==='en'?'en':'ar'));const st=(tableFilterState[table.id]||{})[col]||{text:'',values:[]};const pop=document.createElement('div');pop.className='filter-popover';const search=document.createElement('input');search.type='search';search.placeholder=currentLang==='en'?'Search values':'بحث في القيم';search.value=st.text||'';pop.appendChild(search);const list=document.createElement('div');list.style.marginTop='7px';vals.slice(0,150).forEach(v=>{const lab=document.createElement('label');lab.className='option';const cb=document.createElement('input');cb.type='checkbox';cb.dataset.value=v;cb.checked=(st.values||[]).includes(v);const sp=document.createElement('span');sp.textContent=v;lab.append(cb,sp);list.appendChild(lab)});pop.appendChild(list);const actions=document.createElement('div');actions.className='filter-actions';const clear=document.createElement('button');clear.className='btn';clear.textContent=currentLang==='en'?'Clear':'مسح';clear.onclick=()=>{tableFilterState[table.id]=tableFilterState[table.id]||{};delete tableFilterState[table.id][col];closeHeaderFilter();applyTableFilters(table)};const apply=document.createElement('button');apply.className='btn primary';apply.textContent=currentLang==='en'?'Apply':'تطبيق';apply.onclick=()=>{tableFilterState[table.id]=tableFilterState[table.id]||{};tableFilterState[table.id][col]={text:search.value.trim(),values:[...list.querySelectorAll('input:checked')].map(x=>x.dataset.value)};closeHeaderFilter();applyTableFilters(table)};actions.append(clear,apply);pop.appendChild(actions);search.oninput=()=>{const q=search.value.toLowerCase();list.querySelectorAll('.option').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q)?'':'none')};document.body.appendChild(pop);const r=btn.getBoundingClientRect();pop.style.top=`${Math.min(r.bottom+4,window.innerHeight-370)}px`;pop.style.left=`${Math.max(8,Math.min(r.left,window.innerWidth-270))}px`;filterPopover=pop;setTimeout(()=>search.focus(),0)}
function applyTableFilters(table){const fs=tableFilterState[table.id]||{};[...table.tBodies].flatMap(b=>[...b.rows]).forEach(r=>{const ok=Object.entries(fs).every(([k,f])=>{const txt=String(r.cells[Number(k)]?.innerText||'').trim();const textOk=!f.text||txt.toLowerCase().includes(String(f.text).toLowerCase());const valuesOk=!f.values?.length||f.values.includes(txt);return textOk&&valuesOk});r.style.display=ok?'':'none'});[...table.tHead.rows[0].cells].forEach((th,i)=>th.querySelector('.filter-arrow')?.classList.toggle('active',!!fs[i]&&(!!fs[i].text||!!fs[i].values?.length)))}
document.addEventListener('click',e=>{if(filterPopover&&!filterPopover.contains(e.target)&&!e.target.closest('.filter-arrow'))closeHeaderFilter()});

async function init()'''
s,n=re.subn(filt_re,lambda m:filt_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('filter function patch failed')

# Access: capacity button only control roles.
access_anchor='dailyPlanBtn.classList.toggle("hidden",profile.role!=="Supervisor");addExceptionBtn.classList.toggle("hidden",profile.role!=="CFO")'
access_replace='dailyPlanBtn.classList.toggle("hidden",profile.role!=="Supervisor");capacityBtn?.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));addExceptionBtn.classList.toggle("hidden",profile.role!=="CFO")'
if access_anchor not in s: raise SystemExit('applyAccess anchor missing')
s=s.replace(access_anchor,access_replace,1)

# Reload data and render all.
reload_re=r'async function reloadAll\(\)\{.*?\}\nfunction renderAll\(\)\{.*?\}'
reload_new='''async function reloadAll(){const [pr,bk,py,tk,ex,cl,im,pf,ow]=await Promise.all([sb.from("profiles").select("id,email,full_name,role").eq("active",true),sb.from("bank_liquidity").select("*").order("company"),sb.from("payments").select("*,bank_accounts(company,bank_name,account_name)").order("created_at",{ascending:false}),sb.from("tasks").select("*,owner:profiles!tasks_owner_id_fkey(full_name),reviewer:profiles!tasks_reviewer_id_fkey(full_name)").order("due_date",{ascending:false}).order("created_at",{ascending:false}),sb.from("exceptions").select("*,owner:profiles!exceptions_owner_id_fkey(full_name),leave_delegations(*,absent:profiles!leave_delegations_absent_user_id_fkey(full_name),substitute:profiles!leave_delegations_substitute_user_id_fkey(full_name))").order("created_at",{ascending:false}),sb.from("monthly_close_tasks").select("*,owner:profiles!monthly_close_tasks_owner_id_fkey(full_name)").order("due_date").order("code"),sb.from("imprest_funds").select("*,custodian:profiles!imprest_funds_custodian_id_fkey(full_name)").order("created_at",{ascending:false}),sb.rpc("get_finance_team_performance"),sb.from("ownership_matrix").select("*").order("sort_order")]);profiles=pr.data||[];banks=bk.data||[];payments=py.data||[];tasks=tk.data||[];exceptions=ex.data||[];closeTasks=cl.data||[];imprest=im.data||[];performance=pf.data||[];ownership=ow.data||[];if(["CFO","Supervisor"].includes(profile.role)){const [cc,wl,es,ah]=await Promise.all([sb.rpc("get_supervisor_control_center"),sb.rpc("get_workload_capacity"),sb.rpc("get_escalation_center"),sb.rpc("get_automation_health")]);controlCenter=cc.data||[];workload=wl.data||[];escalations=es.data||[];automationHealth=ah.data||[]}else{controlCenter=[];workload=[];escalations=[];automationHealth=[]}renderAll()}
function renderAll(){renderBanks();renderPayments();renderSavedViews();renderTasks();renderControlCenter();renderWorkload();renderEscalations();renderAutomationHealth();renderClose();renderImprest();renderPerformance();renderOwnership();renderExceptions();renderDashboard();installTableFilters();applyLanguage()}'''
s,n=re.subn(reload_re,reload_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('reload/render patch failed')

# Task logic and Saved Views. Replace from riyadhToday through before openTaskModal.
task_re=r'function riyadhToday\(\).*?function openTaskModal\(\)\{'
task_new=r'''function riyadhToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function taskDeadline(t){if(!t.due_date)return null;return new Date(`${t.due_date}T${t.due_time||'23:59:59'}+03:00`)}
function isTaskOverdue(t){const d=taskDeadline(t);return !!d&&new Date()>d&&!['مكتمل','بانتظار المراجعة'].includes(t.status)&&!t.completed_at}
function taskJustificationRequired(t){return (isTaskOverdue(t)||!!t.justification_requested_at)&&!String(t.delay_justification||'').trim()&&!['مكتمل','بانتظار المراجعة'].includes(t.status)}
const SAVED_VIEWS=[['all','كل المهام'],['today','مهام اليوم'],['overdue','متأخر'],['justification','تبرير مطلوب'],['review','ينتظر مراجعة المشرف'],['urgent','عاجل'],['close','إقفال D+'],['mine','مهامي فقط']];
function renderSavedViews(){if(!document.getElementById('savedViews'))return;savedViews.innerHTML=SAVED_VIEWS.map(([k,l])=>`<button class="view-chip ${activeTaskView===k?'active':''}" onclick="setTaskView('${k}')">${displayText(l)}</button>`).join('')}
function setTaskView(v){if(v==='close'){closeQuickView=true;renderClose();installTableFilters();openPage('close',displayText('الإقفال الشهري'));return}activeTaskView=v;localStorage.setItem('sanam_task_view',v);renderSavedViews();renderTasks();installTableFilters();applyLanguage()}
function taskViewMatches(t){const today=riyadhToday();if(activeTaskView==='today')return t.due_date===today;if(activeTaskView==='overdue')return isTaskOverdue(t);if(activeTaskView==='justification')return taskJustificationRequired(t);if(activeTaskView==='review')return t.status==='بانتظار المراجعة';if(activeTaskView==='urgent')return ['حرج','عالي','عاجل'].includes(t.priority);if(activeTaskView==='mine')return t.owner_id===profile.id;return true}
function taskActionHtml(t){const a=[],mine=t.owner_id===profile.id,reviewer=t.reviewer_id===profile.id||profile.role==='CFO'||(profile.role==='Supervisor'&&t.owner_id!==profile.id);if(mine&&t.opened_at&&!['مكتمل','بانتظار المراجعة'].includes(t.status)){if(t.status!=="قيد التنفيذ")a.push(`<button class="btn" onclick="startTask('${t.id}')">${displayText('بدء')}</button>`);if(t.blocker_note)a.push(`<button class="btn" onclick="clearTaskBlocker('${t.id}')">${displayText('إزالة التعثر')}</button>`);else{a.push(`<button class="btn" onclick="markTaskBlocker('${t.id}')">${displayText('تسجيل تعثر')}</button>`);a.push(`<button class="btn success" onclick="completeTask('${t.id}')">${displayText('إرسال للمراجعة')}</button>`)}}if(mine&&taskJustificationRequired(t))a.push(`<button class="btn danger" onclick="submitTaskJustification('${t.id}')">${displayText('إضافة تبرير')}</button>`);if(profile.role==="Supervisor"&&!['مكتمل','بانتظار المراجعة'].includes(t.status)&&(isTaskOverdue(t)||t.opened_at))a.push(`<button class="btn danger" onclick="requestTaskJustification('${t.id}')">${displayText('طلب تبرير')}</button>`);if(t.status==='بانتظار المراجعة'&&reviewer){a.push(`<button class="btn success" onclick="reviewTask('${t.id}',true)">${displayText('اعتماد المهمة')}</button>`);a.push(`<button class="btn" onclick="reviewTask('${t.id}',false)">${displayText('إعادة للعمل')}</button>`)}return a.join(' ')||'—'}
function renderTasks(){const today=riyadhToday(),todayRows=tasks.filter(t=>t.due_date===today),done=todayRows.filter(t=>t.status==="مكتمل").length,over=todayRows.filter(isTaskOverdue).length,just=todayRows.filter(taskJustificationRequired).length;taskKpis.innerHTML=`<div class="card"><span class="muted">${displayText('مهام اليوم')}</span><b>${todayRows.length}</b></div><div class="card"><span class="muted">${displayText('مكتمل اليوم')}</span><b>${done}</b></div><div class="card"><span class="muted">${displayText('متأخر الآن')}</span><b>${over}</b></div><div class="card"><span class="muted">${displayText('تبريرات معلقة')}</span><b>${just}</b></div>`;const rows=tasks.filter(taskViewMatches);tasksBody.innerHTML=rows.map(t=>{const note=t.blocker_note|| (taskJustificationRequired(t)?displayText('تبرير مطلوب'):(t.delay_justification||t.justification_request_note||t.review_note||'—'));return `<tr class="${isTaskOverdue(t)?'task-overdue':''}"><td>${esc(t.name)}</td><td>${esc(t.owner?.full_name||"—")}</td><td>${esc(t.reviewer?.full_name||"—")}</td><td>${esc(t.due_date||"—")}</td><td>${esc(t.frequency||"—")}</td><td>${esc(t.due_time?String(t.due_time).slice(0,5):"—")}</td><td>${badge(t.priority||"عادي")}</td><td>${badge(t.status||"لم يبدأ")}${t.opened_at&&t.status==="لم يبدأ"?` ${badge('مفتوحة')}`:''}</td><td class="task-control-note">${esc(note)}</td><td>${taskActionHtml(t)}</td></tr>`}).join("")||`<tr><td colspan="10" class="muted">—</td></tr>`;applyTableFilters(document.getElementById('tasksTable'))}
function openDailyPlan(){if(profile.role!=="Supervisor")return;const today=riyadhToday(),rows=tasks.filter(t=>t.frequency==='يومي'&&t.due_date===today&&t.status!=="مكتمل");if(!rows.length){alert(currentLang==='en'?'No daily tasks are available for today.':'لا توجد مهام يومية متاحة لليوم.');return}const html=rows.map(t=>`<tr><td><input type="checkbox" class="plan-check" data-id="${t.id}" checked></td><td>${esc(t.owner?.full_name||'—')}</td><td style="white-space:normal">${esc(t.name)}</td><td>${badge(t.priority||'عادي')}</td><td><input type="time" class="plan-time" data-id="${t.id}" value="${t.due_time?String(t.due_time).slice(0,5):''}"></td></tr>`).join('');showModal(displayText('خطة اليوم / فتح المهام'),`<div class="note" style="margin-bottom:10px">${currentLang==='en'?'Select the tasks to release and set a due time for each selected task.':'حدد المهام التي سيتم فتحها اليوم وضع موعد الاستحقاق لكل مهمة قبل توجيه الفريق.'}</div><div class="table-wrap"><table class="plan-table"><thead><tr><th>✓</th><th>${displayText('المسؤول')}</th><th>${displayText('المهمة')}</th><th>${displayText('الأولوية')}</th><th>${displayText('الوقت')}</th></tr></thead><tbody>${html}</tbody></table></div><div class="row" style="margin-top:14px"><button class="btn success" onclick="saveDailyPlan()">${currentLang==='en'?'Release selected tasks':'فتح المهام المحددة'}</button></div>`)}
async function saveDailyPlan(){const items=[];document.querySelectorAll('.plan-check:checked').forEach(c=>{const id=c.dataset.id,time=document.querySelector(`.plan-time[data-id="${id}"]`)?.value||'';items.push({id,due_time:time})});if(!items.length)return alert(currentLang==='en'?'Select at least one task.':'حدد مهمة واحدة على الأقل.');if(items.some(x=>!x.due_time))return alert(currentLang==='en'?'Due time is required for every selected task.':'يجب تحديد وقت الاستحقاق لكل مهمة محددة.');const {data,error}=await sb.rpc('supervisor_open_daily_plan',{p_items:items});if(error)return alert(error.message);closeModal();await reloadAll();alert(currentLang==='en'?`${data} tasks released.`:`تم فتح ${data} مهمة وتوجيهها للفريق.`)}
async function startTask(id){const {error}=await sb.rpc('start_finance_task',{p_task_id:id});if(error)return alert(error.message);await reloadAll()}
async function markTaskBlocker(id){const note=prompt(currentLang==='en'?'Describe the blocker:':'اكتب سبب التعثر بوضوح:');if(!note||!note.trim())return;const {error}=await sb.rpc('mark_task_blocker',{p_task_id:id,p_note:note.trim()});if(error)return alert(error.message);await reloadAll()}
async function clearTaskBlocker(id){const {error}=await sb.rpc('clear_task_blocker',{p_task_id:id});if(error)return alert(error.message);await reloadAll()}
async function submitTaskJustification(id){const text=prompt(currentLang==='en'?'Enter the required justification:':'اكتب التبرير المطلوب للتأخير أو التعثر:');if(!text||!text.trim())return;const {error}=await sb.rpc('submit_task_justification',{p_task_id:id,p_justification:text.trim()});if(error)return alert(error.message);await reloadAll()}
async function requestTaskJustification(id){const note=prompt(currentLang==='en'?'Reason/note for requesting justification (optional):':'سبب أو ملاحظة طلب التبرير (اختياري):')||'';const {error}=await sb.rpc('request_task_justification',{p_task_id:id,p_note:note});if(error)return alert(error.message);await reloadAll()}
async function completeTask(id){let justification=null;const t=tasks.find(x=>x.id===id);if(t?.blocker_note)return alert(currentLang==='en'?'Clear the blocker before submitting for review.':'يجب إزالة التعثر قبل إرسال المهمة للمراجعة.');if(t&&taskJustificationRequired(t)){justification=prompt(currentLang==='en'?'This task is overdue or has a justification request. Enter justification before submission:':'هذه المهمة متأخرة أو عليها طلب تبرير. يجب إدخال التبرير قبل إرسالها للمراجعة:');if(!justification||!justification.trim())return}let {error}=await sb.rpc('complete_finance_task',{p_task_id:id,p_justification:justification});if(error&&String(error.message||'').includes('DELAY_JUSTIFICATION_REQUIRED')){justification=prompt(currentLang==='en'?'Justification is mandatory before submission:':'التبرير إلزامي قبل إرسال المهمة للمراجعة:');if(!justification||!justification.trim())return;({error}=await sb.rpc('complete_finance_task',{p_task_id:id,p_justification:justification.trim()}))}if(error)return alert(error.message);await reloadAll();alert(currentLang==='en'?'Task submitted for review.':'تم إرسال المهمة للمراجعة.')}
async function reviewTask(id,approve){const note=prompt(approve?(currentLang==='en'?'Review note (optional):':'ملاحظة المراجعة (اختياري):'):(currentLang==='en'?'Reason for returning the task:':'سبب إعادة المهمة للعمل:'))||'';const {error}=await sb.rpc('review_finance_task',{p_task_id:id,p_approve:approve,p_note:note});if(error)return alert(error.message);await reloadAll()}
function openTaskModal(){'''
s,n=re.subn(task_re,lambda m:task_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('task block patch failed')

# Close quick view.
close_re=r'function renderClose\(\)\{closeBody\.innerHTML=closeTasks\.map\(x=>`.*?\}\nfunction openCloseModal'
close_new=r'''function renderClose(){let rows=closeTasks;if(closeQuickView&&rows.length){const latest=[...rows].map(x=>x.close_period).filter(Boolean).sort().pop();rows=rows.filter(x=>x.close_period===latest&&x.status!=='مكتمل'&&Number(x.progress||0)<100)}closeBody.innerHTML=rows.map(x=>`<tr><td>${esc(x.track)}</td><td>${esc(x.code||"—")}</td><td>${esc(x.name)}</td><td>${esc(x.owner?.full_name||"—")}</td><td>${esc(x.due_date||"—")}</td><td>${badge(x.priority||"عادي")}</td><td style="white-space:normal">${esc(x.output||"—")}</td><td>${Number(x.progress||0)}%</td><td>${badge(x.status)}</td></tr>`).join("")||`<tr><td colspan="9" class="muted">${displayText('لا توجد مهام إقفال للدورة الحالية.')}</td></tr>`}
function openCloseModal'''
s,n=re.subn(close_re,lambda m:close_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('close render patch failed')

# Replace performance renderer and inject operations renderers before ownership renderer.
perf_re=r'function renderPerformance\(\)\{.*?\}\nfunction renderOwnership'
perf_new=r'''function renderPerformance(){performanceBody.innerHTML=performance.map(x=>`<tr><td>${esc(x.full_name||"—")}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role||""))}</td><td>${Number(x.today_total||0)}</td><td>${Number(x.today_completed||0)}</td><td>${Number(x.today_overdue||0)}</td><td>${Number(x.pending_justifications||0)}</td><td>${Number(x.pending_review||0)}</td><td><button class="link-metric" onclick="openPerformanceDrilldown('${x.user_id}','month')">${Number(x.month_completion_rate||0).toFixed(1)}%</button></td><td><button class="link-metric" onclick="openPerformanceDrilldown('${x.user_id}','ontime')">${Number(x.tracked_on_time_rate||0).toFixed(1)}%</button></td><td><button class="link-metric" onclick="openPerformanceDrilldown('${x.user_id}','close')">${Number(x.close_completion_rate||0).toFixed(1)}%</button></td></tr>`).join("")||`<tr><td colspan="10" class="muted">${displayText('لا توجد بيانات أداء بعد.')}</td></tr>`}
function remainingText(m){if(m===null||m===undefined)return '—';const n=Number(m);if(n<0)return `${currentLang==='en'?'Overdue':'متأخر'} ${Math.abs(n)} ${currentLang==='en'?'min':'د'}`;const h=Math.floor(n/60),mm=n%60;return h?`${h}${currentLang==='en'?'h':'س'} ${mm}${currentLang==='en'?'m':'د'}`:`${mm}${currentLang==='en'?'m':'د'}`}
function renderControlCenter(){if(!document.getElementById('controlBody'))return;const total=controlCenter.reduce((a,x)=>a+Number(x.today_total||0),0),done=controlCenter.reduce((a,x)=>a+Number(x.today_completed||0),0),over=controlCenter.reduce((a,x)=>a+Number(x.overdue_count||0),0),block=controlCenter.reduce((a,x)=>a+Number(x.blocker_count||0),0);controlKpis.innerHTML=`<div class="card"><span class="muted">${displayText('مهام اليوم')}</span><b>${total}</b></div><div class="card"><span class="muted">${displayText('مكتمل اليوم')}</span><b>${done}</b></div><div class="card"><span class="muted">${displayText('متأخر الآن')}</span><b>${over}</b></div><div class="card"><span class="muted">${displayText('التعثر')}</span><b>${block}</b></div>`;controlBody.innerHTML=controlCenter.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role))}</td><td style="white-space:normal">${esc(x.current_task||'—')}</td><td>${badge(x.current_status||'—')}</td><td>${x.next_due_at?fmt(x.next_due_at):'—'}</td><td>${esc(remainingText(x.remaining_minutes))}</td><td>${x.today_total}</td><td>${x.today_completed}</td><td>${x.overdue_count}</td><td>${x.blocker_count}</td><td>${x.pending_review_count}</td><td>${x.pending_justifications}</td></tr>`).join('')||`<tr><td colspan="12">—</td></tr>`}
function renderWorkload(){if(!document.getElementById('workloadBody'))return;workloadBody.innerHTML=workload.map(x=>{const pct=x.utilization_percent===null?null:Number(x.utilization_percent);return `<tr><td>${esc(x.full_name)}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role))}</td><td>${x.capacity_tasks??'—'}</td><td>${x.planned_open}</td><td>${x.critical_open}</td><td>${x.high_open}</td><td>${x.overdue_open}</td><td>${x.pending_review}</td><td>${x.blockers}</td><td>${pct===null?'—':`<div>${pct.toFixed(1)}%</div><div class="util-bar"><span style="width:${Math.min(100,pct)}%"></span></div>`}</td></tr>`}).join('')||`<tr><td colspan="10">—</td></tr>`}
function openCapacitySettings(){if(!['CFO','Supervisor'].includes(profile.role))return;const body=workload.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role))}</td><td><input type="number" min="1" max="50" class="capacity-input" data-id="${x.user_id}" value="${x.capacity_tasks??''}" placeholder="—"></td></tr>`).join('');showModal(displayText('إعداد الطاقة'),`<div class="note" style="margin-bottom:10px">${currentLang==='en'?'Set the normal maximum number of daily tasks for each employee. Leave blank if not defined.':'حدد الحد الطبيعي لعدد المهام اليومية لكل موظف. اتركه فارغًا إذا لم يتم اعتماده بعد.'}</div><div class="table-wrap"><table><thead><tr><th>${displayText('الموظف')}</th><th>${displayText('الدور')}</th><th>${displayText('الطاقة اليومية')}</th></tr></thead><tbody>${body}</tbody></table></div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="saveCapacitySettings()">${displayText('حفظ')}</button></div>`);installTableFilters()}
async function saveCapacitySettings(){const rows=[...document.querySelectorAll('.capacity-input')];for(const r of rows){const n=r.value.trim()===''?null:Number(r.value);const {error}=await sb.rpc('set_team_capacity',{p_user_id:r.dataset.id,p_capacity_tasks:n});if(error)return alert(error.message)}closeModal();await reloadAll()}
function escalationActions(x){const a=[];const t=tasks.find(t=>t.id===x.task_id);if(!t)return '—';if(t.status==='بانتظار المراجعة')a.push(`<button class="btn success" onclick="reviewTask('${t.id}',true)">${displayText('اعتماد المهمة')}</button>`,`<button class="btn" onclick="reviewTask('${t.id}',false)">${displayText('إعادة للعمل')}</button>`);if(t.blocker_note)a.push(`<button class="btn" onclick="clearTaskBlocker('${t.id}')">${displayText('إزالة التعثر')}</button>`);if(!t.delay_justification&&t.status!=='بانتظار المراجعة')a.push(`<button class="btn danger" onclick="requestTaskJustification('${t.id}')">${displayText('طلب تبرير')}</button>`);return a.join(' ')||'—'}
function renderEscalations(){if(!document.getElementById('escalationBody'))return;escalationBody.innerHTML=escalations.map(x=>`<tr><td class="${x.severity==='حرج'?'severity-critical':x.severity==='عالي'?'severity-high':''}">${esc(displayText(x.severity))}</td><td>${esc(displayText(x.issue))}</td><td style="white-space:normal">${esc(x.task_name)}</td><td>${esc(x.owner_name)}</td><td>${badge(x.priority)}</td><td>${badge(x.status)}</td><td>${x.due_at?fmt(x.due_at):'—'}</td><td>${Number(x.age_minutes||0)} ${currentLang==='en'?'min':'د'}</td><td style="white-space:normal">${esc(x.blocker_note||x.justification_note||'—')}</td><td>${escalationActions(x)}</td></tr>`).join('')||`<tr><td colspan="10" class="muted">${currentLang==='en'?'No escalations requiring action.':'لا توجد حالات تستلزم تصعيدًا حاليًا.'}</td></tr>`}
function renderAutomationHealth(){if(!document.getElementById('automationBody'))return;automationBody.innerHTML=automationHealth.map(x=>`<tr><td>${esc(displayText(x.system_name))}</td><td>${badge(x.active?'Active':'Inactive')}</td><td>${esc(x.schedule)}</td><td>${x.last_run_at?fmt(x.last_run_at):'—'}</td><td>${esc(x.last_status||'—')}</td><td>${x.next_run_at?fmt(x.next_run_at):'—'}</td><td>${Number(x.missing_count||0)}</td><td style="white-space:normal">${esc(x.detail||'—')}</td></tr>`).join('')||`<tr><td colspan="8">—</td></tr>`}
function openPerformanceDrilldown(userId,metric){const person=profiles.find(x=>x.id===userId),today=riyadhToday(),month=today.slice(0,7),rows=tasks.filter(t=>t.owner_id===userId&&String(t.due_date||'').startsWith(month));if(metric==='close'){const cr=closeTasks.filter(x=>x.owner_id===userId);showModal(`${person?.full_name||''} — ${displayText('إنجاز الإقفال')}`,`<div class="table-wrap"><table><thead><tr><th>${displayText('البند')}</th><th>${displayText('الموعد')}</th><th>${displayText('الإنجاز')}</th><th>${displayText('الحالة')}</th></tr></thead><tbody>${cr.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.due_date||'—')}</td><td>${Number(x.progress||0)}%</td><td>${badge(x.status)}</td></tr>`).join('')||'<tr><td colspan="4">—</td></tr>'}</tbody></table></div>`);installTableFilters();return}const list=metric==='ontime'?rows.filter(x=>x.status==='مكتمل'&&x.review_requested_at):rows;showModal(`${person?.full_name||''} — ${metric==='ontime'?displayText('الإنجاز في الموعد'):displayText('إنجاز الشهر')}`,`<div class="table-wrap"><table><thead><tr><th>${displayText('المهمة')}</th><th>${displayText('الموعد')}</th><th>${displayText('الحالة')}</th><th>${metric==='ontime'?(currentLang==='en'?'Submitted':'وقت الإرسال'):displayText('الأولوية')}</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.due_date||'—')} ${esc(x.due_time?String(x.due_time).slice(0,5):'')}</td><td>${badge(x.status)}</td><td>${metric==='ontime'?(x.review_requested_at?fmt(x.review_requested_at):'—'):badge(x.priority||'عادي')}</td></tr>`).join('')||'<tr><td colspan="4">—</td></tr>'}</tbody></table></div>`);installTableFilters()}
function renderOwnership'''
s,n=re.subn(perf_re,lambda m:perf_new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('performance/ops render patch failed')

p.write_text(s)
print('ops control v2 patch complete')
