from pathlib import Path
p=Path('index.html')
s=p.read_text()
marker='/* RESERVE_TARGET_PAYMENT_EDIT_2026_09_15 */'
if marker in s:
    print('already patched'); raise SystemExit(0)
s=s.replace('/* CFO_MONITOR_RESERVES_2026_09_15 */','/* CFO_MONITOR_RESERVES_2026_09_15 */\n'+marker,1)
old='''<section id="banks" class="section"><div class="row" style="margin-bottom:12px"><h3>السيولة والبنوك</h3><button id="addBankBtn" class="btn primary" type="button" onclick="openBankModal()">+ إضافة حساب</button></div><div class="note" style="margin-bottom:12px">حدد نوع الحساب من إعداد الحساب. الحسابات الاحتياطية تظل ضمن إجمالي النقد ولكن تُستبعد من السيولة التشغيلية، واستخدامها في المدفوعات يولد تحذيرًا ومراقبة فقط.</div><div class="table-wrap"><table><thead><tr><th>الشركة</th><th>البنك</th><th>الحساب</th><th>نوع الحساب</th><th>آخر 4 أرقام</th><th>الرصيد</th><th>المحجوز</th><th>المتاح</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody id="banksBody"></tbody></table></div></section>'''
new='''<section id="banks" class="section"><div class="row" style="margin-bottom:12px"><h3>السيولة والبنوك</h3><div class="lang-actions"><button id="reserveReportBtn" class="btn" type="button" onclick="openReserveReports()">تقارير الحسابات الاحتياطية</button><button id="addBankBtn" class="btn primary" type="button" onclick="openBankModal()">+ إضافة حساب</button></div></div><div class="note" style="margin-bottom:12px">حدد نوع الحساب من إعداد الحساب. الحسابات الاحتياطية تظل ضمن إجمالي النقد ولكن تُستبعد من السيولة التشغيلية، واستخدامها في المدفوعات يولد تحذيرًا ومراقبة فقط.</div><div class="table-wrap"><table><thead><tr><th>الشركة</th><th>البنك</th><th>الحساب</th><th>نوع الحساب</th><th>آخر 4 أرقام</th><th>الرصيد المستهدف</th><th>الرصيد</th><th>المحجوز</th><th>المتاح</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody id="banksBody"></tbody></table></div></section>'''
assert old in s
s=s.replace(old,new,1)
old='''function renderBanks(){const canDelete=["CFO","Supervisor","BankAccountant"].includes(profile.role);banksBody.innerHTML=banks.map(b=>`<tr><td>${esc(b.company)}</td><td>${esc(b.bank_name)}</td><td>${esc(b.account_name)}</td><td>${badge(accountTypeLabel(b.account_type))}</td><td>${maskAccountNo(b.account_no)}</td><td>${moneyHtml(b.balance)}</td><td>${moneyHtml(b.reserved_balance)}</td><td>${moneyHtml(b.available_balance)}</td><td>${fmt(b.updated_at)}</td><td><button class="btn" onclick="openBankModal('${b.id}')">${displayText('تعديل')}</button>${canDelete?` <button class="btn danger" onclick="deleteBankAccount('${b.id}')">${displayText('حذف')}</button>`:''}</td></tr>`).join("")||`<tr><td colspan="10" class="muted">—</td></tr>`}'''
new='''function reserveInfoForBank(id){return reserveAccounts.find(r=>r.bank_account_id===id)||null}
function renderBanks(){const canDelete=["CFO","Supervisor","BankAccountant"].includes(profile.role);banksBody.innerHTML=banks.map(b=>{const ri=reserveInfoForBank(b.id);return `<tr><td>${esc(b.company)}</td><td>${esc(b.bank_name)}</td><td>${esc(b.account_name)}</td><td>${badge(accountTypeLabel(b.account_type))}</td><td>${maskAccountNo(b.account_no)}</td><td>${ri&&ri.reference_balance!=null?moneyHtml(ri.reference_balance):'—'}</td><td>${moneyHtml(b.balance)}</td><td>${moneyHtml(b.reserved_balance)}</td><td>${moneyHtml(b.available_balance)}</td><td>${fmt(b.updated_at)}</td><td><button class="btn" onclick="openBankModal('${b.id}')">${displayText('تعديل')}</button>${canDelete?` <button class="btn danger" onclick="deleteBankAccount('${b.id}')">${displayText('حذف')}</button>`:''}</td></tr>`}).join("")||`<tr><td colspan="11" class="muted">—</td></tr>`}'''
assert old in s
s=s.replace(old,new,1)
old=''' const b=banks.find(x=>x.id===id)||{};
 showModal(id?"تعديل حساب بنكي":"إضافة حساب بنكي",`<div class="modal-grid">${input("b_company","الشركة",b.company||"")}${input("b_bank","البنك",b.bank_name||"")}${input("b_name","اسم الحساب",b.account_name||"")}${input("b_no","رقم الحساب / IBAN",b.account_no||"")}${select("b_type","نوع الحساب البنكي",ACCOUNT_TYPES.map(x=>({value:x.value,label:x.label})))}${input("b_balance","الرصيد",b.balance||0,"number")}</div><div class="note" style="margin-top:12px">الحساب الاحتياطي يظل ضمن إجمالي النقد، لكنه يُستبعد من السيولة التشغيلية. الاختيار يولد مراقبة وتحذيرًا فقط ولا يمنع الدفع.</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="saveBank('${id}')">حفظ</button></div>`);setTimeout(()=>{const el=document.getElementById('b_type');if(el)el.value=b.account_type||'Operational'},0)
}
async function saveBank(id=""){const payload={company:val("b_company"),bank_name:val("b_bank"),account_name:val("b_name"),account_no:val("b_no")||null,account_type:val("b_type")||'Operational',balance:Number(val("b_balance")||0),created_by:profile.id,updated_at:new Date().toISOString()};'''
new=''' const b=banks.find(x=>x.id===id)||{};const ri=id?reserveInfoForBank(id):null;
 showModal(id?"تعديل حساب بنكي":"إضافة حساب بنكي",`<div class="modal-grid">${input("b_company","الشركة",b.company||"")}${input("b_bank","البنك",b.bank_name||"")}${input("b_name","اسم الحساب",b.account_name||"")}${input("b_no","رقم الحساب / IBAN",b.account_no||"")}${select("b_type","نوع الحساب البنكي",ACCOUNT_TYPES.map(x=>({value:x.value,label:x.label})))}${input("b_target","الرصيد المستهدف",ri?.reference_balance??"","number")}${input("b_balance","الرصيد",b.balance||0,"number")}</div><div class="note" style="margin-top:12px">الرصيد المستهدف قيمة رقابية يحددها الفريق للحسابات الاحتياطية، وهو مستقل عن الرصيد البنكي الحالي. الحساب الاحتياطي يظل ضمن إجمالي النقد لكنه يُستبعد من السيولة التشغيلية.</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="saveBank('${id}')">حفظ</button></div>`);setTimeout(()=>{const el=document.getElementById('b_type');if(el)el.value=b.account_type||'Operational'},0)
}
async function saveBank(id=""){const payload={company:val("b_company"),bank_name:val("b_bank"),account_name:val("b_name"),account_no:val("b_no")||null,account_type:val("b_type")||'Operational',reference_balance:val("b_target")===""?null:Number(val("b_target")),balance:Number(val("b_balance")||0),created_by:profile.id,updated_at:new Date().toISOString()};'''
assert old in s
s=s.replace(old,new,1)
old='''function paymentActions(p){let a=[];if(profile.role==="Supervisor"&&p.supervisor_status==="معلق")'''
new='''function paymentActions(p){let a=[];if(["CFO","Supervisor","BankAccountant"].includes(profile.role)&&p.cfo_status!=="موافق"&&!p.executed_at&&!p.posted_at&&p.status!=="مرحّل")a.push(`<button class="btn" onclick="openPaymentModal('${p.id}')">${displayText('تعديل')}</button>`);if(profile.role==="Supervisor"&&p.supervisor_status==="معلق")'''
assert old in s
s=s.replace(old,new,1)
old='''function openPaymentModal(){
 if(!["CFO","Supervisor","BankAccountant","APAccountant"].includes(profile.role))return;
 if(!banks.length){alert("أضف حسابًا بنكيًا أولًا.");return}
 const bankOpts=banks.map(b=>({value:b.id,label:`${isProtectedBank(b)?"⚠ ":""}${b.bank_name} — ${b.account_name} (${b.company})${isProtectedBank(b)?` — ${accountTypeLabel(b.account_type)}`:""}`}));
 showModal("إضافة دفعة",`<div class="modal-grid">${input("p_due","تاريخ الاستحقاق","","date")}${input("p_company","الشركة")}${input("p_beneficiary","المستفيد")}${input("p_amount","المبلغ",0,"number")}${select("p_bank","حساب البنك",bankOpts)}${select("p_priority","الأولوية",["عادي","عاجل","حرج"])}${select("p_docs","المستندات",["مكتملة","ناقصة"])}${input("p_purpose","الغرض")}</div><div class="warning-box">عند اختيار حساب احتياطي سيظهر تحذير قبل الحفظ. التحذير للمراقبة ولا يمنع إنشاء الدفعة.</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="savePayment()">حفظ</button></div>`)
}
async function savePayment(){const bank=banks.find(b=>b.id===val("p_bank"));if(isProtectedBank(bank)){const msg=currentLang==='en'?`WARNING: This is a protected ${bank.account_type} account. Use should be exceptional and monitored. Continue creating this payment?`:`تحذير: الحساب المختار من نوع «${accountTypeLabel(bank.account_type)}» وهو حساب محمي للاستخدام الاستثنائي وتتم مراقبة السحب منه. هل تريد الاستمرار في إنشاء الدفعة؟`;if(!confirm(msg))return}const payload={due_date:val("p_due"),company:val("p_company"),beneficiary:val("p_beneficiary"),amount:Number(val("p_amount")||0),bank_account_id:val("p_bank"),priority:val("p_priority"),documents_status:val("p_docs"),purpose:val("p_purpose")||null,requested_by:profile.id};const {error}=await sb.from("payments").insert(payload);if(error)return alert(error.message);closeModal();await reloadAll()}'''
new='''function openPaymentModal(id=""){
 const editing=!!id,p=editing?payments.find(x=>x.id===id):null;
 if(editing){if(!["CFO","Supervisor","BankAccountant"].includes(profile.role))return;if(!p||p.cfo_status==="موافق"||p.executed_at||p.posted_at||p.status==="مرحّل")return alert("لا يمكن تعديل دفعة بعد الاعتماد النهائي أو التنفيذ.")}else if(!["CFO","Supervisor","BankAccountant","APAccountant"].includes(profile.role))return;
 if(!banks.length){alert("أضف حسابًا بنكيًا أولًا.");return}
 const bankOpts=banks.map(b=>({value:b.id,label:`${isProtectedBank(b)?"⚠ ":""}${b.bank_name} — ${b.account_name} (${b.company})${isProtectedBank(b)?` — ${accountTypeLabel(b.account_type)}`:""}`}));
 showModal(editing?"تعديل دفعة غير معتمدة نهائيًا":"إضافة دفعة",`<div class="modal-grid">${input("p_due","تاريخ الاستحقاق",p?.due_date||"","date")}${input("p_company","الشركة",p?.company||"")}${input("p_beneficiary","المستفيد",p?.beneficiary||"")}${input("p_amount","المبلغ",p?.amount||0,"number")}${select("p_bank","حساب البنك",bankOpts)}${select("p_priority","الأولوية",["عادي","عاجل","حرج"])}${select("p_docs","المستندات",["مكتملة","ناقصة"])}${input("p_purpose","الغرض",p?.purpose||"")}</div><div class="warning-box">${editing?'أي تعديل يعيد اعتماد المشرف وCFO إلى «معلق» حفاظًا على سلامة دورة الاعتماد. ':''}عند اختيار حساب احتياطي سيظهر تحذير قبل الحفظ.</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="savePayment('${id}')">حفظ</button></div>`);setTimeout(()=>{if(p){document.getElementById('p_bank').value=p.bank_account_id||'';document.getElementById('p_priority').value=p.priority||'عادي';document.getElementById('p_docs').value=p.documents_status||'مكتملة'}},0)
}
async function savePayment(id=""){const bank=banks.find(b=>b.id===val("p_bank"));if(isProtectedBank(bank)){const msg=currentLang==='en'?`WARNING: This is a protected ${bank.account_type} account. Use should be exceptional and monitored. Continue?`:`تحذير: الحساب المختار من نوع «${accountTypeLabel(bank.account_type)}» وهو حساب محمي للاستخدام الاستثنائي وتتم مراقبة السحب منه. هل تريد الاستمرار؟`;if(!confirm(msg))return}const payload={due_date:val("p_due"),company:val("p_company"),beneficiary:val("p_beneficiary"),amount:Number(val("p_amount")||0),bank_account_id:val("p_bank"),priority:val("p_priority"),documents_status:val("p_docs"),purpose:val("p_purpose")||null};let error;if(id){({error}=await sb.rpc('update_unapproved_payment',{p_payment_id:id,p_due_date:payload.due_date,p_company:payload.company,p_beneficiary:payload.beneficiary,p_amount:payload.amount,p_bank_account_id:payload.bank_account_id,p_priority:payload.priority,p_documents_status:payload.documents_status,p_purpose:payload.purpose}))}else{({error}=await sb.from("payments").insert({...payload,requested_by:profile.id}))}if(error)return alert(error.message);closeModal();await reloadAll()}'''
assert old in s
s=s.replace(old,new,1)
anchor='const PAYMENT_REPORT_COLUMNS='
assert anchor in s
report='''let reserveReportRows=[];
function openReserveReports(){if(!["CFO","Supervisor","BankAccountant"].includes(profile.role))return;const opts=reserveAccounts.map(r=>({value:r.bank_account_id,label:`${accountTypeLabel(r.account_type)} — ${r.bank_name} — ${r.account_name} — •••• ${r.account_no_last4||'—'}`}));showModal("تقارير الحسابات الاحتياطية",`<div class="modal-grid">${select('rr_type','نوع التقرير',[{value:'position',label:'تقرير موقف الأرصدة'},{value:'movements',label:'تقرير حركة الحسابات'}])}${select('rr_bank','الحساب',[{value:'',label:'كل الحسابات الاحتياطية'},...opts])}${input('rr_from','الفترة من','','date')}${input('rr_to','الفترة إلى','','date')}</div><div class="report-toolbar" style="margin-top:14px"><button class="btn primary" onclick="previewReserveReport()">معاينة</button><button class="btn" onclick="printReserveReport()">طباعة / PDF</button><button class="btn" onclick="exportReserveReportCsv()">تصدير CSV</button></div><div id="reserveReportOutput"></div>`);previewReserveReport()}
async function previewReserveReport(){const type=val('rr_type')||'position',bank=val('rr_bank')||null,out=document.getElementById('reserveReportOutput');if(type==='position'){reserveReportRows=reserveAccounts.filter(r=>!bank||r.bank_account_id===bank);out.innerHTML=`<div class="table-wrap"><table><thead><tr><th>الحساب</th><th>النوع</th><th>الرصيد المستهدف</th><th>الرصيد الحالي</th><th>المسحوبات</th><th>المسترد</th><th>المطلوب استرداده</th><th>الفرق عن المستهدف</th></tr></thead><tbody>${reserveReportRows.map(r=>`<tr><td>${esc(r.bank_name)} — ${esc(r.account_name)} — •••• ${esc(r.account_no_last4||'—')}</td><td>${esc(accountTypeLabel(r.account_type))}</td><td>${r.reference_balance==null?'—':moneyHtml(r.reference_balance)}</td><td>${moneyHtml(r.balance)}</td><td>${moneyHtml(Number(r.executed_outflows||0)+Number(r.manual_support_draws||0))}</td><td>${moneyHtml(r.restorations)}</td><td>${moneyHtml(r.outstanding_restoration)}</td><td>${r.variance_to_reference==null?'—':moneyHtml(r.variance_to_reference)}</td></tr>`).join('')||'<tr><td colspan="8">—</td></tr>'}</tbody></table></div>`}else{const {data,error}=await sb.rpc('get_reserve_account_movement_report',{p_bank_account_id:bank,p_from:val('rr_from')||null,p_to:val('rr_to')||null});if(error){out.innerHTML=`<div class="warning-box">${esc(error.message)}</div>`;return}reserveReportRows=data||[];out.innerHTML=`<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>الحساب</th><th>الحركة</th><th>المصدر</th><th>المبلغ</th><th>البيان</th></tr></thead><tbody>${reserveReportRows.map(r=>`<tr><td>${esc(r.movement_date||'—')}</td><td>${esc(r.bank_name)} — ${esc(r.account_name)}</td><td>${esc(r.movement_type)}</td><td>${esc(r.source)}</td><td>${moneyHtml(r.amount)}</td><td>${esc(r.note||'—')}</td></tr>`).join('')||'<tr><td colspan="6">—</td></tr>'}</tbody></table></div>`}applyLanguage(out)}
function reserveReportCsvRows(){const type=val('rr_type')||'position';if(type==='position')return [['Account','Type','Target Balance','Current Balance','Withdrawals','Restorations','Outstanding Restoration','Variance to Target'],...reserveReportRows.map(r=>[`${r.bank_name} - ${r.account_name} - ${r.account_no_last4||''}`,r.account_type,r.reference_balance??'',r.balance,Number(r.executed_outflows||0)+Number(r.manual_support_draws||0),r.restorations,r.outstanding_restoration,r.variance_to_reference??''])];return [['Date','Account','Movement','Source','Amount','Note'],...reserveReportRows.map(r=>[r.movement_date,`${r.bank_name} - ${r.account_name}`,r.movement_type,r.source,r.amount,r.note||''])]}
async function exportReserveReportCsv(){await previewReserveReport();const lines=reserveReportCsvRows().map(row=>row.map(csvCell).join(',')).join('\r\n'),blob=new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Sanam_Reserve_${val('rr_type')||'position'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)}
async function printReserveReport(){await previewReserveReport();const type=val('rr_type')||'position',rows=reserveReportCsvRows(),title=type==='position'?'تقرير موقف الحسابات الاحتياطية':'تقرير حركة الحسابات الاحتياطية',w=window.open('','_blank');if(!w)return alert('تم حظر النافذة المنبثقة.');w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>@page{size:A4 landscape;margin:10mm}body{font-family:Segoe UI,Tahoma,Arial,sans-serif;color:#172033}h2{margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #d7dde5;padding:6px;text-align:right}th{background:#eef2f6}</style></head><body><h2>Sanam Finance Portal — ${title}</h2><table><thead><tr>${rows[0].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`);w.document.close();setTimeout(()=>w.print(),250)}

'''
s=s.replace(anchor,report+anchor,1)
# dashboard cards: show target and target gap
old='''<div class="reserve-meta"><div><span class="muted">الرصيد الحالي</span><b>${moneyHtml(r.balance)}</b></div><div><span class="muted">المتاح بالحساب</span><b>${moneyHtml(r.available_balance)}</b></div>'''
new='''<div class="reserve-meta"><div><span class="muted">الرصيد المستهدف</span><b>${r.reference_balance==null?'—':moneyHtml(r.reference_balance)}</b></div><div><span class="muted">الرصيد الحالي</span><b>${moneyHtml(r.balance)}</b></div><div><span class="muted">المطلوب للوصول للمستهدف</span><b class="${Number(r.amount_to_restore_reference)>0?'negative-amount':''}">${moneyHtml(r.amount_to_restore_reference)}</b></div><div><span class="muted">المتاح بالحساب</span><b>${moneyHtml(r.available_balance)}</b></div>'''
assert old in s
s=s.replace(old,new,1)
p.write_text(s)
print('patched')
