from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
marker='/* GOVERNED_UX_PLANNING_SLA_2026_09_16 */'
if marker in s:
    print('already patched'); raise SystemExit(0)
s=s.replace('/* AUDIT_REFRESH_FIX_2026_09_16 */','/* AUDIT_REFRESH_FIX_2026_09_16 */\n'+marker,1)

# UX styles: grouped sidebar, reserve cards, SLA and permission matrix.
s=s.replace('.nav{width:100%;text-align:right;background:transparent;color:#fff;border:0;padding:11px 12px;border-radius:6px;cursor:pointer;margin:2px 0}.nav:hover,.nav.active{background:var(--nav2)}',
'''.nav{width:100%;text-align:right;background:transparent;color:#fff;border:0;padding:9px 12px;border-radius:6px;cursor:pointer;margin:1px 0}.nav:hover,.nav.active{background:var(--nav2)}.nav-group{border-bottom:1px solid rgba(255,255,255,.10);padding:5px 0}.nav-group summary{cursor:pointer;list-style:none;padding:8px 10px;font-size:12px;font-weight:700;color:#c9d7e5;display:flex;align-items:center;justify-content:space-between}.nav-group summary::-webkit-details-marker{display:none}.nav-group summary:after{content:'⌄';opacity:.7}.nav-group[open] summary:after{content:'⌃'}.nav-group .nav{padding-inline-start:18px}.reserve-pro-card{border:1px solid var(--border);border-radius:12px;padding:15px;background:#fff;box-shadow:0 4px 14px rgba(15,39,64,.05)}.reserve-pro-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.reserve-pro-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.reserve-stat{border:1px solid #e7ebf0;border-radius:8px;padding:9px;background:#fafbfc}.reserve-stat span{display:block;font-size:11px;color:var(--muted);margin-bottom:4px}.reserve-stat b{font-size:14px}.reserve-progress{height:8px;background:#edf1f5;border-radius:999px;overflow:hidden;margin-top:8px}.reserve-progress>span{display:block;height:100%;background:var(--green)}.sla-overdue{background:#fdecec;color:#922f2f}.sla-due{background:#fff4df;color:#8a570d}.sla-ok{background:#eaf5ef;color:#176545}.permission-table input[type=checkbox]{width:auto}.permission-lock{opacity:.55}.group-label{font-size:11px;color:#98adc1;padding:8px 10px 3px}@media(max-width:900px){.reserve-pro-grid{grid-template-columns:1fr 1fr}}''',1)

# Group sidebar and restore Permissions page.
new_side='''<aside class="side"><div class="brand"><b>مركز التحكم المالي</b><small>Sanam Finance Portal</small></div>
<details class="nav-group" open><summary>الرئيسية</summary><button class="nav active" data-page="dashboard">لوحة المعلومات</button></details>
<details class="nav-group" open><summary>البنوك</summary><button class="nav" data-page="banks">السيولة</button></details>
<details class="nav-group" open><summary>المدفوعات</summary><button class="nav" data-page="payments">الاعتمادات</button><button class="nav" data-page="pending">المعلقة</button><button class="nav" data-page="posted">المرحلة</button></details>
<details class="nav-group" open><summary>التشغيل</summary><button class="nav" data-page="tasks">المهام</button><button class="nav" data-page="control">التحكم اليومي</button><button class="nav" data-page="workload">عبء العمل</button><button class="nav" data-page="escalations">التعثر</button></details>
<details class="nav-group"><summary>الرقابة</summary><button class="nav" data-page="close">الإقفال</button><button class="nav" data-page="imprest">العهد</button><button class="nav" data-page="performance">الأداء</button><button class="nav" data-page="ownership">المسؤوليات</button><button class="nav" data-page="exceptions">الاستثناءات والسياسات</button></details>
<details class="nav-group"><summary>الإدارة</summary><button class="nav" data-page="permissions">الصلاحيات</button><button class="nav" data-page="automation">الأتمتة</button><button class="nav" data-page="audit">السجل</button></details></aside>'''
s,n=re.subn(r'<aside class="side">.*?</aside>',new_side,s,count=1,flags=re.S)
assert n==1,'sidebar not found'

permissions_section='''<section id="permissions" class="section"><div class="row" style="margin-bottom:12px"><div><h3 style="margin:0">إدارة الصلاحيات والظهور</h3><div class="muted">يتحكم المدير المالي في الصفحات المتاحة لكل موظف. لوحة الأرصدة والسيولة مقيدة دائمًا للمدير المالي والمشرف ومحاسب البنوك.</div></div><button class="btn" onclick="loadPermissionsAdmin()">تحديث</button></div><div id="permissionsMatrix" class="table-wrap permission-table"></div></section>'''
s=s.replace('<section id="audit" class="section">',permissions_section+'<section id="audit" class="section">',1)

# Add payment accounting queue and performance report action.
pay_close='</tbody></table></div></section>\n<section id="posted"'
pay_add='''</tbody></table></div><div id="accountingQueuePanel" class="card monitor-section hidden"><div class="row"><div><h3 style="margin:0">متابعة التسجيل والترحيل — 48 ساعة</h3><div class="muted">يبدأ احتساب المهلة من وقت تحول الدفعة إلى «منفذ». بعد 48 ساعة تظهر كمتأخرة حتى يتم ترحيلها أو تعليقها بتبرير.</div></div></div><div id="accountingQueueSummary" class="mini-kpis" style="margin-top:10px"></div><div class="table-wrap"><table id="accountingQueueTable"><thead><tr><th>التنفيذ</th><th>الشركة</th><th>المستفيد</th><th>المبلغ</th><th>الحالة</th><th>SLA</th><th>الوقت المتبقي</th><th>إجراء</th></tr></thead><tbody id="accountingQueueBody"></tbody></table></div></div></section>\n<section id="posted"'''
assert pay_close in s
s=s.replace(pay_close,pay_add,1)
old_perf='<section id="performance" class="section"><div class="row" style="margin-bottom:12px"><h3>أداء الفريق</h3></div>'
new_perf='<section id="performance" class="section"><div class="row" style="margin-bottom:12px"><h3>أداء الفريق</h3><button class="btn primary" onclick="openKpiReport()">تقرير KPI / الأداء</button></div>'
assert old_perf in s
s=s.replace(old_perf,new_perf,1)
# Expand performance table with operational activity / SLA columns.
s=s.replace('<th>إنجاز الإقفال</th></tr></thead><tbody id="performanceBody">','<th>إنجاز الإقفال</th><th>نشاط اليوم</th><th>نشاط الشهر</th><th>تجاوز SLA</th></tr></thead><tbody id="performanceBody">',1)

# Runtime variables and fallback page access.
s=s.replace('let session=null,profile=null,profiles=[],banks=[],payments=[],tasks=[],exceptions=[],closeTasks=[],imprest=[],performance=[],ownership=[],controlCenter=[],workload=[],escalations=[],automationHealth=[],reserveAccounts=[],financePolicies=[];',
'let session=null,profile=null,profiles=[],banks=[],bankDirectory=[],payments=[],paymentQueue=[],tasks=[],exceptions=[],closeTasks=[],imprest=[],performance=[],ownership=[],controlCenter=[],workload=[],escalations=[],automationHealth=[],reserveAccounts=[],financePolicies=[],permissionMap={};',1)
s=s.replace('CFO:["dashboard","banks","payments","posted","pending","tasks","control","workload","escalations","automation","close","imprest","performance","ownership","exceptions","audit"]',
'CFO:["dashboard","banks","payments","posted","pending","tasks","control","workload","escalations","automation","close","imprest","performance","ownership","exceptions","permissions","audit"]',1)

# Translation coverage for new/reworked UI and reserve cards.
translate='''\nObject.assign(I18N_AR_EN,{"الرئيسية":"Home","البنوك":"Banking","المدفوعات":"Payments","التشغيل":"Operations","الرقابة":"Control","الإدارة":"Administration","السيولة":"Liquidity","الاعتمادات":"Approvals","المعلقة":"Pending","المرحلة":"Posted","التحكم اليومي":"Daily Control","عبء العمل":"Workload","التعثر":"Escalations","الإقفال":"Close","الأداء":"Performance","المسؤوليات":"Ownership","الاستثناءات والسياسات":"Exceptions & Policies","الصلاحيات":"Permissions","الأتمتة":"Automation","السجل":"Audit Log","إدارة الصلاحيات والظهور":"Access & Visibility Management","لوحة الأرصدة والسيولة مقيدة دائمًا للمدير المالي والمشرف ومحاسب البنوك.":"Balance and liquidity views are always restricted to the CFO, Supervisor and Bank Accountant.","متابعة التسجيل والترحيل — 48 ساعة":"Accounting Registration & Posting — 48 Hours","يبدأ احتساب المهلة من وقت تحول الدفعة إلى «منفذ». بعد 48 ساعة تظهر كمتأخرة حتى يتم ترحيلها أو تعليقها بتبرير.":"The SLA starts when the payment becomes Executed. After 48 hours it is overdue until posted or placed on hold with justification.","داخل المهلة":"Within SLA","قرب انتهاء المهلة":"Due Soon","متجاوز المهلة":"Overdue","الوقت المتبقي":"Time Remaining","تجاوز SLA":"SLA Breaches","نشاط اليوم":"Today's Activity","نشاط الشهر":"Monthly Activity","تقرير KPI / الأداء":"KPI / Performance Report","من":"From","إلى":"To","معاينة":"Preview","الرصيد المستهدف":"Target Balance","الرصيد الحالي":"Current Balance","الفرق عن المستهدف":"Variance to Target","المتاح بالحساب":"Available Balance","مطلوب الاستعادة":"Recoverable Outstanding","سحب غير مطلوب الاستعادة":"Non-Recoverable Draws","المبالغ المستعادة":"Restored","نسبة التغطية":"Target Coverage","كشف الحركة":"Movement Report","تسجيل سحب دعم خارجي":"Record External Support Draw","تسجيل استعادة":"Record Restoration","حساب محمي":"Protected Account","قالب مهمة":"Task Template","قوالب المهام":"Task Templates","إضافة قالب جديد":"Add New Template","مهمة جديدة لليوم":"New Task for Today","حفظ كقالب":"Save as Template","فتح المهام المحددة":"Open Selected Tasks","تغيير الحالة بواسطة CFO":"CFO Status Override","سبب التغيير":"Change Reason","حالة جديدة":"New Status","المهام الافتراضية لا تفتح تلقائيًا. اختر يدويًا من القوالب أو أضف مهمة جديدة.":"Default tasks are not opened automatically. Select templates manually or add a new task."});\n'''
pos=s.index('function displayText(v){return tr(v)}')
s=s[:pos]+translate+s[pos:]

# Replace static access + unsafe bank loading with dynamic permission-aware flow.
start=s.index('async function init(){')
end=s.index('\nconst UNIVERSAL_COLUMN_PREF_PREFIX',start)
access_block=r'''async function init(){loginBtn.onclick=signInWithPassword;signupBtn.onclick=firstUseSignup;logoutBtn.onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openPage(b.dataset.page,b.textContent));const {data:{session:s}}=await sb.auth.getSession();session=s;sb.auth.onAuthStateChange(async(_e,s2)=>{session=s2;if(s2)await enterApp();else showAuth()});if(session)await enterApp();else showAuth()}
function showAuth(){authScreen.classList.remove("hidden");app.classList.add("hidden")}
async function loadMyPermissions(){const {data,error}=await sb.rpc('get_my_permissions');if(error){console.error(error);permissionMap={};return}permissionMap=Object.fromEntries((data||[]).map(x=>[x.permission_key,!!x.allowed]))}
function canPage(id){const k=`page.${id}`;return Object.prototype.hasOwnProperty.call(permissionMap,k)?permissionMap[k]:(PAGE_ACCESS[profile?.role]||[]).includes(id)}
function canBankBalances(){return Object.prototype.hasOwnProperty.call(permissionMap,'data.bank_balances')?permissionMap['data.bank_balances']:['CFO','Supervisor','BankAccountant'].includes(profile?.role)}
async function enterApp(){const {data:u}=await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(!u){showAuth();loginMsg.textContent=displayText("الحساب غير مصرح أو لم يكتمل إنشاؤه.");return}profile=u;await loadMyPermissions();authScreen.classList.add("hidden");app.classList.remove("hidden");userRole.textContent=`${profile.full_name} — ${displayText(ROLE_LABEL[profile.role]||profile.role)}`;applyAccess();await reloadAll();if(!canPage('dashboard')){const first=[...document.querySelectorAll('.nav')].find(b=>!b.classList.contains('hidden'));if(first)openPage(first.dataset.page,first.textContent)}applyLanguage()}
function applyAccess(){document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("hidden",!canPage(b.dataset.page)));document.querySelectorAll('.nav-group').forEach(g=>{const any=[...g.querySelectorAll('.nav')].some(b=>!b.classList.contains('hidden'));g.classList.toggle('hidden',!any)});addBankBtn.classList.toggle("hidden",!["CFO","Supervisor","BankAccountant"].includes(profile.role)||!canBankBalances());addPaymentBtn.classList.toggle("hidden",!["CFO","Supervisor","BankAccountant","APAccountant"].includes(profile.role));paymentReportBtn.classList.toggle("hidden",!["CFO","Supervisor","BankAccountant"].includes(profile.role));addTaskBtn.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));dailyPlanBtn.classList.toggle("hidden",!["Supervisor","CFO"].includes(profile.role));capacityBtn?.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));addExceptionBtn.classList.toggle("hidden",profile.role!=="CFO");addPolicyBtn?.classList.toggle("hidden",profile.role!=="CFO");addCloseBtn.classList.toggle("hidden",!["CFO","Supervisor"].includes(profile.role));addImprestBtn.classList.toggle("hidden",!["CFO","Supervisor","BankAccountant","APAccountant"].includes(profile.role))}
function openPage(id,title){if(!canPage(id))return;document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.getElementById(id)?.classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelector(`.nav[data-page="${id}"]`)?.classList.add("active");pageTitle.textContent=title;if(id==="audit")loadAudit();if(id==='permissions')loadPermissionsAdmin()}
async function reloadAll(){
 const core=[sb.from("profiles").select("id,email,full_name,role").eq("active",true),sb.rpc('get_bank_account_directory'),sb.from("payments").select("*").order("created_at",{ascending:false}),sb.from("tasks").select("*,owner:profiles!tasks_owner_id_fkey(full_name),reviewer:profiles!tasks_reviewer_id_fkey(full_name)").order("due_date",{ascending:false}).order("created_at",{ascending:false}),sb.from("exceptions").select("*,owner:profiles!exceptions_owner_id_fkey(full_name),leave_delegations(*,absent:profiles!leave_delegations_absent_user_id_fkey(full_name),substitute:profiles!leave_delegations_substitute_user_id_fkey(full_name))").order("created_at",{ascending:false}),sb.from("monthly_close_tasks").select("*,owner:profiles!monthly_close_tasks_owner_id_fkey(full_name)").order("due_date").order("code"),sb.from("imprest_funds").select("*,custodian:profiles!imprest_funds_custodian_id_fkey(full_name)").order("created_at",{ascending:false}),sb.rpc("get_finance_team_performance"),sb.from("ownership_matrix").select("*").order("sort_order")];
 const [pr,dir,py,tk,ex,cl,im,pf,ow]=await Promise.all(core);profiles=pr.data||[];bankDirectory=dir.data||[];payments=(py.data||[]).map(x=>({...x,bank_accounts:bankDirectory.find(b=>b.id===x.bank_account_id)||null}));tasks=tk.data||[];exceptions=ex.data||[];closeTasks=cl.data||[];imprest=im.data||[];performance=pf.data||[];ownership=ow.data||[];
 if(canBankBalances()){const [bk,rr]=await Promise.all([sb.rpc('get_visible_bank_liquidity'),sb.rpc("get_reserve_account_monitor")]);banks=bk.data||[];reserveAccounts=rr.data||[]}else{banks=[];reserveAccounts=[]}
 const pol=await sb.rpc("get_finance_policy_register");financePolicies=pol.data||[];
 if(["CFO","Supervisor"].includes(profile.role)){const req=[sb.rpc("get_supervisor_control_center"),sb.rpc("get_workload_capacity"),sb.rpc("get_escalation_center")];if(canPage('automation'))req.push(sb.rpc("get_automation_health"));const out=await Promise.all(req);controlCenter=out[0].data||[];workload=out[1].data||[];escalations=out[2].data||[];automationHealth=canPage('automation')?(out[3]?.data||[]):[]}else{controlCenter=[];workload=[];escalations=[];automationHealth=[]}
 if(["CFO","Supervisor","GLAccountant"].includes(profile.role)){const q=await sb.rpc('get_payment_accounting_queue');paymentQueue=q.data||[]}else paymentQueue=[];
 renderAll()
}
'''
s=s[:start]+access_block+s[end:]

# Replace manual daily plan: only templates selected explicitly + new ad-hoc task/template.
start=s.index('async function openDailyPlan(){')
end=s.index('\nasync function startTask',start)
manual_plan=r'''async function openDailyPlan(){
 if(!["Supervisor","CFO"].includes(profile.role))return;
 const {data:catalog,error}=await sb.from('finance_task_catalog').select('id,name,default_owner_id,default_priority,output').eq('active',true).order('name');if(error)return alert(error.message);
 const owners=profiles.map(x=>({value:x.id,label:x.full_name}));
 const rows=(catalog||[]).map(t=>`<tr><td><input type="checkbox" class="plan-template-check" data-id="${t.id}"></td><td style="white-space:normal">${esc(t.name)}</td><td>${selectInline('plan-template-owner',t.id,owners,t.default_owner_id||'')}</td><td>${selectInline('plan-template-priority',t.id,['عادي','عالي','حرج'],t.default_priority||'عادي')}</td><td><input type="time" class="plan-template-time" data-id="${t.id}" value="09:00"></td><td style="white-space:normal">${esc(t.output||'—')}</td></tr>`).join('');
 showModal(displayText('خطة اليوم / فتح المهام'),`<div class="note">${displayText('المهام الافتراضية لا تفتح تلقائيًا. اختر يدويًا من القوالب أو أضف مهمة جديدة.')}</div><div class="row" style="margin:12px 0"><h4 style="margin:0">${displayText('قوالب المهام')}</h4><button class="btn" onclick="openTaskTemplateModal()">+ ${displayText('إضافة قالب جديد')}</button></div><div class="table-wrap"><table><thead><tr><th></th><th>${displayText('المهمة')}</th><th>${displayText('المسؤول')}</th><th>${displayText('الأولوية')}</th><th>${displayText('الوقت')}</th><th>${displayText('المخرج')}</th></tr></thead><tbody>${rows||'<tr><td colspan="6">—</td></tr>'}</tbody></table></div><h4>${displayText('مهمة جديدة لليوم')}</h4><div class="modal-grid">${input('plan_new_name','المهمة')}${select('plan_new_owner','المسؤول',[{value:'',label:'—'},...owners])}${select('plan_new_priority','الأولوية',['عادي','عالي','حرج'])}${input('plan_new_time','الوقت','09:00','time')}${input('plan_new_output','المخرج')}</div><label style="margin-top:10px;display:flex;align-items:center;gap:7px"><input id="plan_save_template" type="checkbox" style="width:auto"> ${displayText('حفظ كقالب')}</label><div class="row" style="margin-top:14px"><button class="btn primary" onclick="saveDailyPlan()">${displayText('فتح المهام المحددة')}</button></div>`);installTableFilters();applyLanguage(document.getElementById('modalBody'))
}
async function openTaskTemplateModal(){const name=prompt(currentLang==='en'?'Template name:':'اسم القالب:');if(!name||!name.trim())return;const owner=prompt(currentLang==='en'?'Paste owner ID from the team list shown in Daily Plan.':'أدخل معرف الموظف المسؤول من بيانات الفريق.');if(!owner)return;const {error}=await sb.rpc('create_finance_task_template',{p_name:name.trim(),p_owner_id:owner,p_priority:'عادي',p_output:null});if(error)return alert(error.message);closeModal();await openDailyPlan()}
async function saveDailyPlan(){const items=[];document.querySelectorAll('.plan-template-check:checked').forEach(c=>{const id=c.dataset.id;items.push({catalog_id:id,owner_id:document.querySelector(`.plan-template-owner[data-id="${id}"]`)?.value||'',priority:document.querySelector(`.plan-template-priority[data-id="${id}"]`)?.value||'عادي',due_time:document.querySelector(`.plan-template-time[data-id="${id}"]`)?.value||''})});const name=(val('plan_new_name')||'').trim();if(name)items.push({name,owner_id:val('plan_new_owner'),priority:val('plan_new_priority')||'عادي',due_time:val('plan_new_time'),output:val('plan_new_output')||null,save_as_template:!!document.getElementById('plan_save_template')?.checked});if(!items.length)return alert(currentLang==='en'?'Select a template or add a new task.':'اختر قالبًا أو أضف مهمة جديدة.');if(items.some(x=>!x.owner_id||!x.due_time))return alert(currentLang==='en'?'Owner and due time are required.':'يجب تحديد المسؤول ووقت الاستحقاق.');const {data,error}=await sb.rpc('save_manual_daily_plan',{p_items:items});if(error)return alert(error.message);closeModal();await reloadAll();alert(currentLang==='en'?`${data||0} tasks opened.`:`تم فتح ${data||0} مهمة ضمن خطة اليوم.`)}
'''
s=s[:start]+manual_plan+s[end:]

# Payment action authority: Fahad registration/post/pending; CFO override any stage.
start=s.index('function paymentActions(p){')
end=s.index('\nasync function deleteRequestedPayment',start)
payment_actions=r'''function paymentActions(p){let a=[];if(((profile.role==="CFO")||(["Supervisor","BankAccountant"].includes(profile.role)&&p.cfo_status!=="موافق"))&&!p.executed_at&&!p.posted_at&&p.status!=="مرحّل")a.push(`<button class="btn" onclick="openPaymentModal('${p.id}')">${displayText('تعديل')}</button>`);if(profile.role==="Supervisor"&&p.supervisor_status==="معلق")a.push(`<button class="btn success" onclick="supervisorApprove('${p.id}')">${displayText('اعتماد المشرف')}</button>`);if(profile.role==="CFO"&&p.supervisor_status==="موافق"&&p.cfo_status==="معلق")a.push(`<button class="btn success" onclick="cfoApprove('${p.id}')">${displayText('اعتماد CFO')}</button>`);if(profile.role==="BankAccountant"&&p.cfo_status==="موافق"&&!p.executed_at)a.push(`<button class="btn success" onclick="executePayment('${p.id}')">${displayText('تم التنفيذ')}</button>`);if(profile.role==="GLAccountant"&&p.status==="منفذ"&&p.executed_at&&!p.posted_at)a.push(`<button class="btn success" onclick="registerPaymentAccounting('${p.id}')">${displayText('تم التسجيل')}</button>`);if(["Supervisor","CFO","GLAccountant"].includes(profile.role)&&p.status==="تم التسجيل"&&!p.posted_at){a.push(`<button class="btn success" onclick="finalizeRegisteredPayment('${p.id}','Posted')">${displayText('مرحّل')}</button>`);a.push(`<button class="btn" onclick="openPendingPaymentModal('${p.id}')">${displayText('معلقة')}</button>`)}if(profile.role==='CFO')a.push(`<button class="btn" onclick="openCfoStatusOverride('${p.id}')">${displayText('تغيير الحالة بواسطة CFO')}</button>`);if(["CFO","Supervisor","BankAccountant"].includes(profile.role)&&!p.executed_at&&!p.posted_at&&p.status!=="مرحّل")a.push(`<button class="btn danger" onclick="deleteRequestedPayment('${p.id}')">${displayText('حذف')}</button>`);return a.join(" ")||"—"}
function pendingPaymentActions(p){const a=[];if(["Supervisor","CFO","GLAccountant"].includes(profile.role))a.push(`<button class="btn success" onclick="finalizeRegisteredPayment('${p.id}','Posted')">${displayText('مرحّل')}</button>`);if(profile.role==='CFO')a.push(`<button class="btn" onclick="openCfoStatusOverride('${p.id}')">${displayText('تغيير الحالة بواسطة CFO')}</button>`);return a.join(' ')||'—'}
async function registerPaymentAccounting(id){const {error}=await sb.rpc('register_payment_accounting',{p_payment_id:id});if(error)return alert(error.message);await reloadAll()}
function openPendingPaymentModal(id){if(!["Supervisor","CFO","GLAccountant"].includes(profile.role))return;const p=payments.find(x=>x.id===id);if(!p)return;showModal(displayText('تعليق العملية'),`<div class="note">${esc(p.company)} — ${esc(p.beneficiary)} — ${moneyHtml(p.amount)}</div><label style="margin-top:10px">${displayText('سبب التعليق / التبرير')} *</label><textarea id="pend_reason" rows="4"></textarea><div class="modal-grid" style="margin-top:10px">${input('pend_action','الإجراء المطلوب')}${select('pend_owner','مسؤول المتابعة',[{value:'',label:'—'},...profiles.map(x=>({value:x.id,label:x.full_name}))])}${input('pend_follow','تاريخ المتابعة','','date')}</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="savePendingPayment('${id}')">${displayText('حفظ')}</button></div>`)}
async function savePendingPayment(id){const reason=(val('pend_reason')||'').trim();if(!reason)return alert(displayText('سبب التعليق إلزامي.'));const {error}=await sb.rpc('supervisor_finalize_registered_payment',{p_payment_id:id,p_action:'Pending',p_reason:reason,p_pending_action:val('pend_action')||null,p_pending_owner_id:val('pend_owner')||null,p_follow_up_date:val('pend_follow')||null});if(error)return alert(error.message);closeModal();await reloadAll();openPage('pending',displayText('العمليات المعلقة'))}
async function finalizeRegisteredPayment(id,action){if(!["Supervisor","CFO","GLAccountant"].includes(profile.role))return;const {error}=await sb.rpc('supervisor_finalize_registered_payment',{p_payment_id:id,p_action:action,p_reason:null,p_pending_action:null,p_pending_owner_id:null,p_follow_up_date:null});if(error)return alert(error.message);await reloadAll()}
function openCfoStatusOverride(id){if(profile.role!=='CFO')return;const p=payments.find(x=>x.id===id);if(!p)return;showModal(displayText('تغيير الحالة بواسطة CFO'),`${select('cfo_override_status','حالة جديدة',['بانتظار مراجعة المشرف','بانتظار اعتماد CFO','معتمد للدفع','منفذ','تم التسجيل','معلقة','مرحّل','مرفوض','موقوف'],p.status)}<label style="margin-top:10px">${displayText('سبب التغيير')} *</label><textarea id="cfo_override_reason" rows="3"></textarea><div class="row" style="margin-top:14px"><button class="btn primary" onclick="saveCfoStatusOverride('${id}')">${displayText('حفظ')}</button></div>`)}
async function saveCfoStatusOverride(id){const reason=(val('cfo_override_reason')||'').trim();if(!reason)return alert(currentLang==='en'?'Change reason is required.':'سبب التغيير إلزامي.');const {error}=await sb.rpc('cfo_override_payment_status',{p_payment_id:id,p_status:val('cfo_override_status'),p_reason:reason});if(error)return alert(error.message);closeModal();await reloadAll()}
'''
s=s[:start]+payment_actions+s[end:]

# Performance includes operational activity and report tools.
old="function renderPerformance(){performanceBody.innerHTML=performance.map(x=>`<tr><td>${esc(x.full_name||\"—\")}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role||\"\"))}</td><td>${Number(x.today_total||0)}</td><td>${Number(x.today_completed||0)}</td><td>${Number(x.today_overdue||0)}</td><td>${Number(x.pending_justifications||0)}</td><td>${Number(x.pending_review||0)}</td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','month')\">${Number(x.month_completion_rate||0).toFixed(1)}%</button></td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','ontime')\">${Number(x.tracked_on_time_rate||0).toFixed(1)}%</button></td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','close')\">${Number(x.close_completion_rate||0).toFixed(1)}%</button></td></tr>`).join(\"\")||`<tr><td colspan=\"10\" class=\"muted\">${displayText('لا توجد بيانات أداء بعد.')}</td></tr>`}"
new="function renderPerformance(){performanceBody.innerHTML=performance.map(x=>`<tr><td>${esc(x.full_name||\"—\")}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role||\"\"))}</td><td>${Number(x.today_total||0)}</td><td>${Number(x.today_completed||0)}</td><td>${Number(x.today_overdue||0)}</td><td>${Number(x.pending_justifications||0)}</td><td>${Number(x.pending_review||0)}</td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','month')\">${Number(x.month_completion_rate||0).toFixed(1)}%</button></td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','ontime')\">${Number(x.tracked_on_time_rate||0).toFixed(1)}%</button></td><td><button class=\"link-metric\" onclick=\"openPerformanceDrilldown('${x.user_id}','close')\">${Number(x.close_completion_rate||0).toFixed(1)}%</button></td><td>${Number(x.today_operational_activities||0)}</td><td>${Number(x.month_operational_activities||0)}</td><td>${Number(x.payment_sla_overdue||0)}</td></tr>`).join(\"\")||`<tr><td colspan=\"13\" class=\"muted\">${displayText('لا توجد بيانات أداء بعد.')}</td></tr>`}"
assert old in s,'renderPerformance not found';s=s.replace(old,new,1)

insert_before='function remainingText(m)'
kpi_funcs=r'''let kpiReportRows=[];
function openKpiReport(){if(!['CFO','Supervisor'].includes(profile.role))return;const d=new Date(),to=d.toISOString().slice(0,10),from=new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10);showModal(displayText('تقرير KPI / الأداء'),`<div class="modal-grid">${input('kpi_from','من',from,'date')}${input('kpi_to','إلى',to,'date')}</div><div class="report-toolbar" style="margin-top:12px"><button class="btn primary" onclick="previewKpiReport()">${displayText('معاينة')}</button><button class="btn" onclick="exportKpiCsv()">${displayText('تصدير CSV')}</button><button class="btn" onclick="printKpiReport()">${displayText('طباعة / PDF')}</button></div><div id="kpiReportOutput"></div>`);previewKpiReport()}
async function previewKpiReport(){const {data,error}=await sb.rpc('get_finance_team_kpi_report',{p_from:val('kpi_from')||null,p_to:val('kpi_to')||null});const out=document.getElementById('kpiReportOutput');if(error){out.innerHTML=`<div class="warning-box">${esc(error.message)}</div>`;return}kpiReportRows=data||[];out.innerHTML=`<div class="table-wrap"><table><thead><tr><th>${displayText('الموظف')}</th><th>${displayText('الدور')}</th><th>${displayText('المهام')}</th><th>${displayText('مكتمل')}</th><th>${displayText('الإنجاز')}</th><th>${displayText('الإنجاز في الموعد')}</th><th>${displayText('نشاط الشهر')}</th><th>${displayText('تجاوز SLA')}</th></tr></thead><tbody>${kpiReportRows.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(displayText(ROLE_LABEL[x.role]||x.role))}</td><td>${x.assigned_tasks}</td><td>${x.completed_tasks}</td><td>${Number(x.completion_rate||0).toFixed(1)}%</td><td>${Number(x.on_time_rate||0).toFixed(1)}%</td><td>${x.operational_activities}</td><td>${x.sla_overdue_activities}</td></tr>`).join('')}</tbody></table></div>`;installTableFilters();applyLanguage(out)}
function kpiCsvRows(){return [['Employee','Role','Assigned Tasks','Completed Tasks','Completion Rate','On Time Rate','Operational Activities','SLA Overdue'],...kpiReportRows.map(x=>[x.full_name,x.role,x.assigned_tasks,x.completed_tasks,x.completion_rate,x.on_time_rate,x.operational_activities,x.sla_overdue_activities])]}
async function exportKpiCsv(){await previewKpiReport();const lines=kpiCsvRows().map(r=>r.map(csvCell).join(',')).join('\r\n'),blob=new Blob(['﻿'+lines],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Sanam_Team_KPI.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)}
async function printKpiReport(){await previewKpiReport();const rows=kpiCsvRows(),w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html dir="${currentLang==='en'?'ltr':'rtl'}"><head><meta charset="utf-8"><style>body{font-family:Segoe UI,Tahoma,Arial}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #ddd;padding:6px}</style></head><body><h2>Sanam Finance Portal — ${displayText('تقرير KPI / الأداء')}</h2><table><thead><tr>${rows[0].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`);w.document.close();setTimeout(()=>w.print(),200)}
'''
pos=s.index(insert_before);s=s[:pos]+kpi_funcs+s[pos:]

# Payment accounting SLA queue renderer.
pos=s.index('function renderPayments(){')
queue_func=r'''function renderAccountingQueue(){const panel=document.getElementById('accountingQueuePanel');if(!panel)return;const allowed=['CFO','Supervisor','GLAccountant'].includes(profile.role);panel.classList.toggle('hidden',!allowed);if(!allowed)return;const overdue=paymentQueue.filter(x=>x.sla_status==='Overdue').length,due=paymentQueue.filter(x=>x.sla_status==='Due Soon').length;accountingQueueSummary.innerHTML=`<div class="card"><span class="muted">${displayText('عدد الدفعات')}</span><b>${paymentQueue.length}</b></div><div class="card"><span class="muted">${displayText('متجاوز المهلة')}</span><b>${overdue}</b></div><div class="card"><span class="muted">${displayText('قرب انتهاء المهلة')}</span><b>${due}</b></div>`;accountingQueueBody.innerHTML=paymentQueue.map(q=>{const p=payments.find(x=>x.id===q.payment_id);const cls=q.sla_status==='Overdue'?'sla-overdue':q.sla_status==='Due Soon'?'sla-due':'sla-ok';const label=q.sla_status==='Overdue'?'متجاوز المهلة':q.sla_status==='Due Soon'?'قرب انتهاء المهلة':'داخل المهلة';return `<tr class="${q.sla_status==='Overdue'?'task-overdue':''}"><td>${fmt(q.executed_at)}</td><td>${esc(q.company)}</td><td>${esc(q.beneficiary)}</td><td>${moneyHtml(q.amount)}</td><td>${badge(q.status)}</td><td><span class="badge ${cls}">${displayText(label)}</span></td><td>${q.hours_remaining<0?`${Math.abs(Number(q.hours_remaining)).toFixed(1)}h ${displayText('متأخر')}`:`${Number(q.hours_remaining).toFixed(1)}h`}</td><td>${p?paymentActions(p):'—'}</td></tr>`}).join('')||'<tr><td colspan="8">—</td></tr>';applyTableFilters(document.getElementById('accountingQueueTable'))}
'''
s=s[:pos]+queue_func+s[pos:]

# Render permissions page and helper.
pos=s.index('function renderAll(){')
perm_funcs=r'''const PERMISSION_KEYS=[['page.dashboard','لوحة المعلومات'],['page.banks','السيولة والبنوك'],['page.payments','المدفوعات والاعتمادات'],['page.posted','المدفوعات المرحلة'],['page.pending','العمليات المعلقة'],['page.tasks','المهام'],['page.control','مركز التحكم اليومي'],['page.escalations','التعثر والتصعيد'],['page.automation','صحة الأتمتة'],['page.close','الإقفال الشهري'],['page.imprest','العهد'],['page.performance','أداء الفريق'],['page.ownership','مصفوفة المسؤوليات'],['page.exceptions','الاستثناءات والإجازات'],['page.audit','سجل العمليات'],['data.bank_balances','بيانات الأرصدة البنكية']];
async function loadPermissionsAdmin(){if(profile.role!=='CFO')return;const {data,error}=await sb.from('user_permissions').select('user_id,permission_key,allowed');if(error)return alert(error.message);const m=new Map((data||[]).map(x=>[`${x.user_id}:${x.permission_key}`,!!x.allowed]));permissionsMatrix.innerHTML=`<table><thead><tr><th>${displayText('الموظف')}</th><th>${displayText('الدور')}</th>${PERMISSION_KEYS.map(x=>`<th>${displayText(x[1])}</th>`).join('')}</tr></thead><tbody>${profiles.map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(displayText(ROLE_LABEL[u.role]||u.role))}</td>${PERMISSION_KEYS.map(([k])=>{const locked=['page.dashboard','page.banks','data.bank_balances'].includes(k)&&!['CFO','Supervisor','BankAccountant'].includes(u.role);const checked=locked?false:(m.get(`${u.id}:${k}`)??false);return `<td class="${locked?'permission-lock':''}"><input type="checkbox" ${checked?'checked':''} ${locked?'disabled':''} onchange="setPermissionAdmin('${u.id}','${k}',this.checked)"></td>`}).join('')}</tr>`).join('')}</tbody></table>`;installTableFilters();applyLanguage(permissionsMatrix)}
async function setPermissionAdmin(userId,key,allowed){const {error}=await sb.rpc('set_user_permission',{p_user_id:userId,p_permission_key:key,p_allowed:allowed});if(error){alert(error.message);await loadPermissionsAdmin();return}if(userId===profile.id){await loadMyPermissions();applyAccess()}await loadPermissionsAdmin()}
'''
s=s[:pos]+perm_funcs+s[pos:]

# renderAll includes accounting queue; permissions loads only on page.
s=s.replace('function renderAll(){renderBanks();renderPayments();renderSavedViews();renderTasks();renderControlCenter();renderWorkload();renderEscalations();renderAutomationHealth();renderClose();renderImprest();renderPerformance();renderOwnership();renderExceptions();renderPolicies();renderDashboard();installUniversalColumnCustomizers();installTableFilters();applyLanguage()}',
'function renderAll(){renderBanks();renderPayments();renderAccountingQueue();renderSavedViews();renderTasks();renderControlCenter();renderWorkload();renderEscalations();renderAutomationHealth();renderClose();renderImprest();renderPerformance();renderOwnership();renderExceptions();renderPolicies();if(canBankBalances())renderDashboard();installUniversalColumnCustomizers();installTableFilters();applyLanguage()}',1)

# Redesign protected-account cards with professional hierarchy + translated labels.
start=s.index(" reserveMonitorCards.innerHTML=reserveAccounts.map")
end=s.index(" const active=payments.filter",start)
reserve=r''' const canMove=['CFO','Supervisor','BankAccountant'].includes(profile.role);
 reserveMonitorCards.innerHTML=reserveAccounts.map(r=>{const target=Number(r.reference_balance||0),bal=Number(r.balance||0),pct=target>0?Math.max(0,Math.min(100,bal/target*100)):0;const nonRecover=Math.max(0,Number(r.manual_support_draws||0)-Number(r.outstanding_restoration||0)-Number(r.restorations||0));return `<div class="reserve-pro-card"><div class="reserve-pro-head"><div><div class="muted">${displayText('حساب محمي')}</div><b style="font-size:16px">${esc(accountTypeLabel(r.account_type))}</b><div class="muted">${esc(r.bank_name)} — ${esc(r.account_name)} — •••• ${esc(r.account_no_last4||'—')}</div></div><span class="badge amber">Protected / Monitor</span></div><div class="reserve-pro-grid"><div class="reserve-stat"><span>${displayText('الرصيد المستهدف')}</span><b>${r.reference_balance==null?'—':moneyHtml(r.reference_balance)}</b></div><div class="reserve-stat"><span>${displayText('الرصيد الحالي')}</span><b>${moneyHtml(r.balance)}</b></div><div class="reserve-stat"><span>${displayText('الفرق عن المستهدف')}</span><b class="${Number(r.variance_to_reference)>0?'negative-amount':''}">${r.variance_to_reference==null?'—':moneyHtml(r.variance_to_reference)}</b></div><div class="reserve-stat"><span>${displayText('المتاح بالحساب')}</span><b>${moneyHtml(r.available_balance)}</b></div><div class="reserve-stat"><span>${displayText('مطلوب الاستعادة')}</span><b class="${Number(r.outstanding_restoration)>0?'negative-amount':''}">${moneyHtml(r.outstanding_restoration)}</b></div><div class="reserve-stat"><span>${displayText('سحب غير مطلوب الاستعادة')}</span><b>${moneyHtml(nonRecover)}</b></div><div class="reserve-stat"><span>${displayText('المبالغ المستعادة')}</span><b>${moneyHtml(r.restorations)}</b></div><div class="reserve-stat"><span>${displayText('نسبة التغطية')}</span><b>${target>0?pct.toFixed(1)+'%':'—'}</b><div class="reserve-progress"><span style="width:${pct}%"></span></div></div></div><div class="row" style="margin-top:12px"><button class="btn" onclick="openReserveReports()">${displayText('كشف الحركة')}</button>${canMove?`<div class="lang-actions"><button class="btn" onclick="openReserveMovement('${r.bank_account_id}','Support Draw')">${displayText('تسجيل سحب دعم خارجي')}</button><button class="btn success" onclick="openReserveMovement('${r.bank_account_id}','Restoration')">${displayText('تسجيل استعادة')}</button></div>`:''}</div></div>`}).join('')||`<div class="note">${currentLang==='en'?'No protected accounts are classified yet.':'لم يتم تصنيف أي حساب كحساب احتياطي حتى الآن.'}</div>`;
'''
s=s[:start]+reserve+s[end:]

p.write_text(s)
print('patched',len(s))
