from pathlib import Path
p=Path('index.html')
s=p.read_text()
marker='/* FILTER_RESERVE_PENDING_2026_09_16 */'
if marker in s:
    print('already patched'); raise SystemExit(0)
s=s.replace('/* DAILY_PLAN_POLICIES_2026_09_16 */','/* DAILY_PLAN_POLICIES_2026_09_16 */\n'+marker,1)

# Fixed desktop sidebar and independent main-content scrolling; mobile behavior stays unchanged.
s=s.replace('.app{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{background:var(--nav);color:#fff;padding:18px 12px}',
'''.app{display:grid;grid-template-columns:240px 1fr;height:100vh;min-height:100vh;overflow:hidden}.side{background:var(--nav);color:#fff;padding:18px 12px;height:100vh;overflow-y:auto;overscroll-behavior:contain}''',1)
s=s.replace('.main{min-width:0}.top{height:64px;', '.main{min-width:0;height:100vh;overflow:hidden}.top{height:64px;',1)
s=s.replace('.content{padding:20px}', '.content{padding:20px;height:calc(100vh - 64px);overflow-y:auto;overscroll-behavior:contain}',1)
s=s.replace('@media(max-width:900px){.app{grid-template-columns:1fr}.side{display:none}.g4,.g2{grid-template-columns:1fr 1fr}}',
'@media(max-width:900px){.app{grid-template-columns:1fr;height:auto;min-height:100vh;overflow:visible}.side{display:none}.main{height:auto;overflow:visible}.content{height:auto;overflow:visible}.g4,.g2{grid-template-columns:1fr 1fr}}',1)
s=s.replace('.filter-arrow.active{color:var(--blue);font-weight:700}', '.filter-arrow.active{color:#fff;background:var(--blue);font-weight:800;border-radius:5px;padding:2px 6px}.filter-summary{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin:0 0 8px;padding:7px 9px;background:#eef6ff;border:1px solid #bfd7f0;border-radius:7px;font-size:12px}.filter-chip{display:inline-flex;align-items:center;gap:4px;padding:3px 7px;border-radius:999px;background:#fff;border:1px solid #bfd7f0}',1)

# Add pending page navigation without changing existing page names/order otherwise.
needle='<button class="nav" data-page="posted">المدفوعات المرحلة</button>'
s=s.replace(needle,needle+'<button class="nav" data-page="pending">العمليات المعلقة</button>',1)
posted_section='<section id="posted" class="section"><div class="row" style="margin-bottom:12px"><h3>المدفوعات المرحلة</h3></div><div class="table-wrap"><table><thead><tr><th>تاريخ الترحيل</th><th>الشركة</th><th>المستفيد</th><th>المبلغ</th><th>الحساب</th><th>الغرض</th></tr></thead><tbody id="postedBody"></tbody></table></div></section>'
pending_section='''<section id="pending" class="section"><div class="row" style="margin-bottom:12px"><div><h3 style="margin:0">العمليات المعلقة</h3><div class="muted">عمليات تم تسجيلها محاسبيًا ثم علّقها المشرف مع تبرير إلزامي للمتابعة.</div></div><div class="lang-actions"><button class="btn" onclick="printPendingReport()">طباعة / PDF</button><button class="btn" onclick="exportPendingCsv()">تصدير CSV</button><button class="btn" onclick="copyPendingEmailSummary()">نسخ ملخص للبريد</button></div></div><div id="pendingSummary" class="mini-kpis"></div><div class="table-wrap"><table id="pendingTable"><thead><tr><th>تاريخ التعليق</th><th>الشركة</th><th>المستفيد</th><th>المبلغ</th><th>الحساب</th><th>الغرض</th><th>سبب التعليق</th><th>الإجراء المطلوب</th><th>مسؤول المتابعة</th><th>تاريخ المتابعة</th><th>مدة التعليق</th><th>إجراء</th></tr></thead><tbody id="pendingBody"></tbody></table></div></section>'''
assert posted_section in s
s=s.replace(posted_section,posted_section+pending_section,1)

# Access only for workflow roles; no other page access is changed.
s=s.replace('CFO:["dashboard","banks","payments","posted","tasks"', 'CFO:["dashboard","banks","payments","posted","pending","tasks"',1)
s=s.replace('Supervisor:["dashboard","banks","payments","posted","tasks"', 'Supervisor:["dashboard","banks","payments","posted","pending","tasks"',1)
s=s.replace('BankAccountant:["dashboard","banks","payments","posted","tasks"', 'BankAccountant:["dashboard","banks","payments","posted","pending","tasks"',1)
s=s.replace('GLAccountant:["dashboard","payments","posted","tasks"', 'GLAccountant:["dashboard","payments","posted","pending","tasks"',1)

# Strong filter visibility + per-table summary and global clear for active filters.
start=s.index('const tableFilterState={};let filterPopover=null;')
end=s.index("document.addEventListener('click',e=>{if(filterPopover",start)
end=s.index('\n',end)+1
filter_block=r'''const tableFilterState={};let filterPopover=null;
function installTableFilters(){document.querySelectorAll('.table-wrap table').forEach((table,idx)=>{if(!table.id)table.id=`sanamTable${idx}`;const head=table.tHead;if(!head||!head.rows.length)return;[...head.rows[0].cells].forEach((th,i)=>{if(!th.querySelector('.filter-arrow')){const label=document.createElement('span');while(th.firstChild)label.appendChild(th.firstChild);const wrap=document.createElement('div');wrap.className='filter-head';const btn=document.createElement('button');btn.type='button';btn.className='filter-arrow';btn.textContent='▾';btn.title=currentLang==='en'?'Filter':'فلترة';btn.onclick=e=>{e.stopPropagation();openHeaderFilter(table,i,btn)};wrap.appendChild(label);wrap.appendChild(btn);th.appendChild(wrap)}});applyTableFilters(table)})}
function closeHeaderFilter(){if(filterPopover){filterPopover.remove();filterPopover=null}}
function openHeaderFilter(table,col,btn){closeHeaderFilter();const all=[...table.tBodies].flatMap(b=>[...b.rows]).map(r=>String(r.cells[col]?.innerText||'').trim()).filter(Boolean);const vals=[...new Set(all)].sort((a,b)=>a.localeCompare(b,currentLang==='en'?'en':'ar'));const st=(tableFilterState[table.id]||{})[col]||{text:'',values:[]};const pop=document.createElement('div');pop.className='filter-popover';const search=document.createElement('input');search.type='search';search.placeholder=currentLang==='en'?'Search values':'بحث في القيم';search.value=st.text||'';pop.appendChild(search);const list=document.createElement('div');list.style.marginTop='7px';vals.slice(0,150).forEach(v=>{const lab=document.createElement('label');lab.className='option';const cb=document.createElement('input');cb.type='checkbox';cb.dataset.value=v;cb.checked=(st.values||[]).includes(v);const sp=document.createElement('span');sp.textContent=v;lab.append(cb,sp);list.appendChild(lab)});pop.appendChild(list);const actions=document.createElement('div');actions.className='filter-actions';const clear=document.createElement('button');clear.className='btn';clear.textContent=currentLang==='en'?'Clear':'مسح';clear.onclick=()=>{tableFilterState[table.id]=tableFilterState[table.id]||{};delete tableFilterState[table.id][col];closeHeaderFilter();applyTableFilters(table)};const apply=document.createElement('button');apply.className='btn primary';apply.textContent=currentLang==='en'?'Apply':'تطبيق';apply.onclick=()=>{tableFilterState[table.id]=tableFilterState[table.id]||{};const values=[...list.querySelectorAll('input:checked')].map(x=>x.dataset.value),text=search.value.trim();if(text||values.length)tableFilterState[table.id][col]={text,values};else delete tableFilterState[table.id][col];closeHeaderFilter();applyTableFilters(table)};actions.append(clear,apply);pop.appendChild(actions);search.oninput=()=>{const q=search.value.toLowerCase();list.querySelectorAll('.option').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q)?'':'none')};document.body.appendChild(pop);const r=btn.getBoundingClientRect();pop.style.top=`${Math.min(r.bottom+4,window.innerHeight-370)}px`;pop.style.left=`${Math.max(8,Math.min(r.left,window.innerWidth-270))}px`;filterPopover=pop;setTimeout(()=>search.focus(),0)}
function filterColumnLabel(table,i){const th=table.tHead?.rows?.[0]?.cells?.[i];return String(th?.querySelector('.filter-head>span')?.innerText||th?.innerText||'').trim().replace(/[▾●]+$/,'').trim()}
function updateFilterSummary(table){const fs=tableFilterState[table.id]||{},active=Object.entries(fs).filter(([,f])=>f&&(f.text||f.values?.length));const wrap=table.closest('.table-wrap');if(!wrap)return;let bar=document.getElementById(`${table.id}_filterSummary`);if(!active.length){bar?.remove();return}if(!bar){bar=document.createElement('div');bar.id=`${table.id}_filterSummary`;bar.className='filter-summary';wrap.parentNode.insertBefore(bar,wrap)}bar.innerHTML=`<b>${currentLang==='en'?'Active filters':'الفلاتر النشطة'}:</b>${active.map(([i,f])=>`<span class="filter-chip">${esc(filterColumnLabel(table,Number(i)))}${f.text?`: ${esc(f.text)}`:''}${f.values?.length?` (${f.values.length})`:''}</span>`).join('')}<button class="btn" type="button" onclick="clearAllTableFilters('${table.id}')">${currentLang==='en'?'Clear all filters':'مسح جميع الفلاتر'}</button>`}
function clearAllTableFilters(tableId){tableFilterState[tableId]={};const table=document.getElementById(tableId);if(table)applyTableFilters(table)}
function applyTableFilters(table){const fs=tableFilterState[table.id]||{};[...table.tBodies].flatMap(b=>[...b.rows]).forEach(r=>{const ok=Object.entries(fs).every(([k,f])=>{const txt=String(r.cells[Number(k)]?.innerText||'').trim();const textOk=!f.text||txt.toLowerCase().includes(String(f.text).toLowerCase());const valuesOk=!f.values?.length||f.values.includes(txt);return textOk&&valuesOk});r.style.display=ok?'':'none'});[...table.tHead.rows[0].cells].forEach((th,i)=>{const btn=th.querySelector('.filter-arrow'),active=!!fs[i]&&(!!fs[i].text||!!fs[i].values?.length);if(btn){btn.classList.toggle('active',active);btn.textContent=active?'▾●':'▾';btn.title=active?(currentLang==='en'?'Filter active — click to change or clear':'فلترة نشطة — اضغط للتعديل أو المسح'):(currentLang==='en'?'Filter':'فلترة')}});updateFilterSummary(table)}
document.addEventListener('click',e=>{if(filterPopover&&!filterPopover.contains(e.target)&&!e.target.closest('.filter-arrow'))closeHeaderFilter()});
'''
s=s[:start]+filter_block+s[end:]

# Payment workflow UI: GL registers; Supervisor/CFO posts or places on hold with mandatory justification.
start=s.index('function renderPayments(){')
end=s.index('\nasync function deleteRequestedPayment',start)
payment_block=r'''function renderPayments(){
 const active=payments.filter(p=>p.status!=="مرحّل"&&p.status!=="معلقة"),posted=payments.filter(p=>p.status==="مرحّل"),pending=payments.filter(p=>p.status==="معلقة");
 paymentsBody.innerHTML=active.map(p=>`<tr><td>${esc(p.due_date)}</td><td>${esc(p.company)}</td><td>${esc(p.beneficiary)}</td><td>${moneyHtml(p.amount)}</td><td>${esc(bankLabel(p))}</td><td style="white-space:normal;min-width:220px">${esc(p.purpose||"—")}</td><td>${badge(p.priority||"عادي")}</td><td>${badge(p.documents_status||"—")}</td><td>${badge(p.supervisor_status)}</td><td>${badge(p.cfo_status)}</td><td>${badge(p.status)}</td><td>${paymentActions(p)}</td></tr>`).join("");
 postedBody.innerHTML=posted.map(p=>`<tr><td>${fmt(p.posted_at)}</td><td>${esc(p.company)}</td><td>${esc(p.beneficiary)}</td><td>${moneyHtml(p.amount)}</td><td>${esc(bankLabel(p))}</td><td>${esc(p.purpose||"—")}</td></tr>`).join("");
 if(document.getElementById('pendingBody')){pendingBody.innerHTML=pending.map(p=>{const owner=profiles.find(x=>x.id===p.pending_owner_id);const days=p.pending_at?Math.max(0,Math.floor((Date.now()-new Date(p.pending_at).getTime())/86400000)):0;return `<tr><td>${fmt(p.pending_at)}</td><td>${esc(p.company)}</td><td>${esc(p.beneficiary)}</td><td>${moneyHtml(p.amount)}</td><td>${esc(bankLabel(p))}</td><td style="white-space:normal">${esc(p.purpose||'—')}</td><td style="white-space:normal;min-width:220px">${esc(p.pending_reason||'—')}</td><td style="white-space:normal">${esc(p.pending_action||'—')}</td><td>${esc(owner?.full_name||'—')}</td><td>${esc(p.pending_follow_up_date||'—')}</td><td>${days}</td><td>${pendingPaymentActions(p)}</td></tr>`}).join('')||`<tr><td colspan="12">—</td></tr>`;pendingSummary.innerHTML=`<div class="card"><span class="muted">${displayText('عدد العمليات المعلقة')}</span><b>${pending.length}</b></div><div class="card"><span class="muted">${displayText('إجمالي المبالغ المعلقة')}</span><b>${money(pending.reduce((a,x)=>a+Number(x.amount||0),0))}</b></div>`}
 applyPaymentColumnVisibility();
}
function paymentActions(p){let a=[];if(((profile.role==="CFO")||(["Supervisor","BankAccountant"].includes(profile.role)&&p.cfo_status!=="موافق"))&&!p.executed_at&&!p.posted_at&&p.status!=="مرحّل")a.push(`<button class="btn" onclick="openPaymentModal('${p.id}')">${displayText('تعديل')}</button>`);if(profile.role==="Supervisor"&&p.supervisor_status==="معلق")a.push(`<button class="btn success" onclick="supervisorApprove('${p.id}')">${displayText('اعتماد المشرف')}</button>`);if(profile.role==="CFO"&&p.supervisor_status==="موافق"&&p.cfo_status==="معلق")a.push(`<button class="btn success" onclick="cfoApprove('${p.id}')">${displayText('اعتماد CFO')}</button>`);if(profile.role==="BankAccountant"&&p.cfo_status==="موافق"&&!p.executed_at)a.push(`<button class="btn success" onclick="executePayment('${p.id}')">${displayText('تم التنفيذ')}</button>`);if(profile.role==="GLAccountant"&&p.status==="منفذ"&&p.executed_at&&!p.posted_at)a.push(`<button class="btn success" onclick="registerPaymentAccounting('${p.id}')">${displayText('تم التسجيل')}</button>`);if(["Supervisor","CFO"].includes(profile.role)&&p.status==="تم التسجيل"&&!p.posted_at){a.push(`<button class="btn success" onclick="finalizeRegisteredPayment('${p.id}','Posted')">${displayText('مرحّل')}</button>`);a.push(`<button class="btn" onclick="openPendingPaymentModal('${p.id}')">${displayText('معلقة')}</button>`)}if(["CFO","Supervisor","BankAccountant"].includes(profile.role)&&!p.executed_at&&!p.posted_at&&p.status!=="مرحّل")a.push(`<button class="btn danger" onclick="deleteRequestedPayment('${p.id}')">${displayText('حذف')}</button>`);return a.join(" ")||"—"}
function pendingPaymentActions(p){return ["Supervisor","CFO"].includes(profile.role)?`<button class="btn success" onclick="finalizeRegisteredPayment('${p.id}','Posted')">${displayText('مرحّل')}</button>`:'—'}
async function registerPaymentAccounting(id){const {error}=await sb.rpc('register_payment_accounting',{p_payment_id:id});if(error)return alert(error.message);await reloadAll()}
function openPendingPaymentModal(id){if(!["Supervisor","CFO"].includes(profile.role))return;const p=payments.find(x=>x.id===id);if(!p)return;showModal(displayText('تعليق العملية'),`<div class="note">${esc(p.company)} — ${esc(p.beneficiary)} — ${moneyHtml(p.amount)}</div><label style="margin-top:10px">${displayText('سبب التعليق / التبرير')} *</label><textarea id="pend_reason" rows="4"></textarea><div class="modal-grid" style="margin-top:10px">${input('pend_action','الإجراء المطلوب')}${select('pend_owner','مسؤول المتابعة',[{value:'',label:'—'},...profiles.map(x=>({value:x.id,label:x.full_name}))])}${input('pend_follow','تاريخ المتابعة','','date')}</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="savePendingPayment('${id}')">${displayText('حفظ')}</button></div>`)}
async function savePendingPayment(id){const reason=(val('pend_reason')||'').trim();if(!reason)return alert(displayText('سبب التعليق إلزامي.'));const {error}=await sb.rpc('supervisor_finalize_registered_payment',{p_payment_id:id,p_action:'Pending',p_reason:reason,p_pending_action:val('pend_action')||null,p_pending_owner_id:val('pend_owner')||null,p_follow_up_date:val('pend_follow')||null});if(error)return alert(error.message);closeModal();await reloadAll();openPage('pending',displayText('العمليات المعلقة'))}
async function finalizeRegisteredPayment(id,action){if(!["Supervisor","CFO"].includes(profile.role))return;const {error}=await sb.rpc('supervisor_finalize_registered_payment',{p_payment_id:id,p_action:action,p_reason:null,p_pending_action:null,p_pending_owner_id:null,p_follow_up_date:null});if(error)return alert(error.message);await reloadAll()}
function pendingCsvRows(){const rows=payments.filter(p=>p.status==='معلقة');return [['Pending Date','Company','Beneficiary','Amount','Bank Account','Purpose','Justification','Required Action','Follow-up Owner','Follow-up Date','Days Pending'],...rows.map(p=>{const owner=profiles.find(x=>x.id===p.pending_owner_id),days=p.pending_at?Math.max(0,Math.floor((Date.now()-new Date(p.pending_at).getTime())/86400000)):0;return [p.pending_at||'',p.company,p.beneficiary,p.amount,bankLabel(p),p.purpose||'',p.pending_reason||'',p.pending_action||'',owner?.full_name||'',p.pending_follow_up_date||'',days]})]}
function exportPendingCsv(){const lines=pendingCsvRows().map(r=>r.map(csvCell).join(',')).join(String.fromCharCode(13,10)),blob=new Blob(['﻿'+lines],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Sanam_Pending_Operations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)}
function printPendingReport(){const rows=pendingCsvRows(),w=window.open('','_blank');if(!w)return alert('تم حظر النافذة المنبثقة.');w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>تقرير العمليات المعلقة</title><style>@page{size:A4 landscape;margin:10mm}body{font-family:Segoe UI,Tahoma,Arial,sans-serif}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #d7dde5;padding:6px;text-align:right}th{background:#eef2f6}</style></head><body><h2>Sanam Finance Portal — تقرير العمليات المعلقة</h2><table><thead><tr>${rows[0].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`);w.document.close();setTimeout(()=>w.print(),250)}
async function copyPendingEmailSummary(){const rows=payments.filter(p=>p.status==='معلقة'),total=rows.reduce((a,x)=>a+Number(x.amount||0),0),text=`Sanam Finance Portal — ${displayText('العمليات المعلقة')}\n${displayText('عدد العمليات المعلقة')}: ${rows.length}\n${displayText('إجمالي المبالغ المعلقة')}: ${money(total)}\n\n`+rows.map(p=>`- ${p.company} | ${p.beneficiary} | ${money(p.amount)} | ${p.pending_reason||''}`).join('\n');try{await navigator.clipboard.writeText(text);alert(displayText('تم نسخ الملخص للبريد.'))}catch{prompt(displayText('انسخ الملخص:'),text)}}
'''
s=s[:start]+payment_block+s[end:]

# Reserve movement report: CFO-only reclassification of already-recorded manual support draws.
old='<th>البيان</th></tr></thead><tbody>${reserveReportRows.map(r=>`<tr><td>${esc(r.movement_date||\'—\')}</td><td>${esc(r.bank_name)} — ${esc(r.account_name)}</td><td>${esc(r.movement_type)}</td><td>${esc(r.source)}</td><td>${moneyHtml(r.amount)}</td><td>${r.requires_restoration==null?\'—\':(r.requires_restoration?displayText(\'نعم\'):displayText(\'لا\'))}</td><td>${moneyHtml(r.restored_amount||0)}</td><td>${moneyHtml(r.outstanding_amount||0)}</td><td>${esc(displayText(r.recovery_status||\'—\'))}</td><td style="white-space:normal">${esc(r.note||\'—\')}</td></tr>`).join(\'\')||\'<tr><td colspan="10">—</td></tr>\'}</tbody></table></div>`'
new='<th>البيان</th><th>إجراء</th></tr></thead><tbody>${reserveReportRows.map(r=>`<tr><td>${esc(r.movement_date||\'—\')}</td><td>${esc(r.bank_name)} — ${esc(r.account_name)}</td><td>${esc(r.movement_type)}</td><td>${esc(r.source)}</td><td>${moneyHtml(r.amount)}</td><td>${r.requires_restoration==null?\'—\':(r.requires_restoration?displayText(\'نعم\'):displayText(\'لا\'))}</td><td>${moneyHtml(r.restored_amount||0)}</td><td>${moneyHtml(r.outstanding_amount||0)}</td><td>${esc(displayText(r.recovery_status||\'—\'))}</td><td style="white-space:normal">${esc(r.note||\'—\')}</td><td>${profile.role===\'CFO\'&&r.source===\'Manual\'&&r.movement_type===\'Support Draw\'?`<button class="btn" onclick="reclassifyReserveDraw(\'${r.reference}\',${r.requires_restoration!==false})">${displayText(\'تعديل التصنيف\')}</button>`:\'—\'}</td></tr>`).join(\'\')||\'<tr><td colspan="11">—</td></tr>\'}</tbody></table></div>`'
assert old in s, 'reserve movement table pattern not found'
s=s.replace(old,new,1)
insert=s.index('function reserveReportCsvRows()')
reclass=r'''async function reclassifyReserveDraw(id,current){if(profile.role!=='CFO')return;const target=!current,reason=prompt(displayText('سبب إعادة التصنيف (إلزامي):'));if(!reason||!reason.trim())return;const msg=target?displayText('سيتم تصنيف السحب كمطلوب استعادته. متابعة؟'):displayText('سيتم تصنيف السحب كغير مطلوب استعادته. ستبقى أي استردادات تاريخية محفوظة. متابعة؟');if(!confirm(msg))return;const {error}=await sb.rpc('reclassify_reserve_support_draw',{p_movement_id:id,p_requires_restoration:target,p_reason:reason.trim()});if(error)return alert(error.message);await reloadAll();await previewReserveReport()}
'''
s=s[:insert]+reclass+s[insert:]

# New translations; existing translations remain unchanged.
idx=s.index('function displayText')
i18n='''Object.assign(I18N_AR_EN,{"العمليات المعلقة":"Pending Operations","عدد العمليات المعلقة":"Pending Operations Count","إجمالي المبالغ المعلقة":"Total Pending Amount","سبب التعليق / التبرير":"Pending Justification","سبب التعليق إلزامي.":"Pending justification is required.","الإجراء المطلوب":"Required Action","مسؤول المتابعة":"Follow-up Owner","تاريخ المتابعة":"Follow-up Date","مدة التعليق":"Days Pending","تعليق العملية":"Place Operation on Hold","تم التسجيل":"Accounting Registered","معلقة":"Pending","تعديل التصنيف":"Reclassify","سبب إعادة التصنيف (إلزامي):":"Reclassification reason (required):","سيتم تصنيف السحب كمطلوب استعادته. متابعة؟":"The draw will be classified as recoverable. Continue?","سيتم تصنيف السحب كغير مطلوب استعادته. ستبقى أي استردادات تاريخية محفوظة. متابعة؟":"The draw will be classified as non-recoverable. Historical restorations will remain preserved. Continue?","مسح جميع الفلاتر":"Clear All Filters","الفلاتر النشطة":"Active Filters","تم نسخ الملخص للبريد.":"Email summary copied.","انسخ الملخص:":"Copy summary:"});\n'''
s=s[:idx]+i18n+s[idx:]

p.write_text(s)
print('patched filter indicators, fixed sidebar, reserve reclassification and pending payment workflow UI')
