from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
marker='/* WORK_CENTER_V31_RULE_ACTIONS_2026_09_17 */'
if marker in s:
    raise SystemExit('already patched')
s=s.replace('/* WORKFLOW_ENGINE_V3_UI_2026_09_17 */','/* WORKFLOW_ENGINE_V3_UI_2026_09_17 */\n'+marker,1)
s=s.replace('<h3 style="margin:0">مركز سير العمل</h3>','<h3 style="margin:0">مركز العمل</h3>',1)
s=s.replace('مساحة عمل موحدة للمهام اليدوية ومراحل المدفوعات والتنفيذ البنكي والتسجيل المحاسبي. السجلات الأصلية تظل في وحداتها الحالية.','واجهة العمل اليومية الموحدة. تظهر الإجراءات المتاحة تلقائيًا حسب الدور والحالة والمسؤولية دون الحاجة للتنقل بين الشاشات.',1)
old='<button class="btn" onclick="openWorkflowTimeline(\'${esc(w.source_entity_type)}\',\'${esc(w.source_entity_id)}\',\'${esc(w.title)}\')">${displayText(\'عرض المسار\')}</button><button class="btn" onclick="openWorkflowSource(\'${esc(w.source_entity_type)}\',\'${esc(w.source_entity_id)}\')">${displayText(\'فتح المصدر\')}</button>'
new='<button class="btn primary" onclick="openWorkItemActionPanel(\'${esc(w.id)}\',\'${esc(w.title)}\')">${displayText(\'إجراءات\')}</button><button class="btn" onclick="openWorkflowTimeline(\'${esc(w.source_entity_type)}\',\'${esc(w.source_entity_id)}\',\'${esc(w.title)}\')">${displayText(\'عرض المسار\')}</button><button class="btn" onclick="openWorkflowSource(\'${esc(w.source_entity_type)}\',\'${esc(w.source_entity_id)}\')">${displayText(\'فتح المصدر\')}</button>'
if old not in s:
    raise SystemExit('workflow action cell anchor not found')
s=s.replace(old,new,1)
anchor='function renderWorkflowCenter(){'
if anchor not in s:
    raise SystemExit('renderWorkflowCenter anchor not found')
js=r'''
const WORKCENTER_ACTION_LABELS={
 ACKNOWLEDGE:['استلام','Acknowledge'],START:['بدء','Start'],PAUSE:['إيقاف مؤقت','Pause'],RESUME:['استئناف','Resume'],COMMENT:['تعليق','Comment'],PROGRESS_UPDATE:['تحديث التقدم','Progress update'],REQUEST_CLARIFICATION:['طلب توضيح','Request clarification'],REPORT_BLOCKER:['تسجيل تعثر','Report blocker'],RESOLVE_BLOCKER:['حل التعثر','Resolve blocker'],REQUEST_EXTENSION:['طلب تمديد','Request extension'],COMPLETE:['تم التنفيذ','Complete'],SUBMIT_FOR_REVIEW:['إرسال للمراجعة','Submit for review'],REASSIGN:['إعادة إسناد','Reassign'],CHANGE_DUE:['تغيير الموعد','Change due date'],CHANGE_PRIORITY:['تغيير الأولوية','Change priority'],CHANGE_REVIEWER:['تغيير المراجع','Change reviewer'],APPROVE_EXTENSION:['اعتماد التمديد','Approve extension'],REJECT_EXTENSION:['رفض التمديد','Reject extension'],REQUEST_EXTENSION_INFO:['طلب معلومات إضافية','Request more info'],APPROVE_COMPLETION:['اعتماد الإنجاز','Approve completion'],RETURN_REWORK:['إعادة للعمل','Return for rework'],REQUEST_JUSTIFICATION:['طلب تبرير','Request justification'],APPROVE_PAYMENT_SUPERVISOR:['اعتماد المشرف','Supervisor approve'],APPROVE_PAYMENT_CFO:['اعتماد المدير المالي','CFO approve'],EXECUTE_PAYMENT:['تم التنفيذ البنكي','Execute payment'],REGISTER_ACCOUNTING:['تم التسجيل','Register accounting'],FINALIZE_POSTING:['ترحيل وإقفال','Post / finalize']
};
function workcenterActionLabel(a){const x=WORKCENTER_ACTION_LABELS[a];return x?(currentLang==='en'?x[1]:x[0]):a}
function ensureWorkItemActionModal(){let m=document.getElementById('workItemActionModal');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div id="workItemActionModal" class="modal-bg"><div class="modal"><div class="row"><div><h3 id="workItemActionTitle" style="margin:0">مركز العمل</h3><div class="muted">تظهر فقط الإجراءات المسموحة للحالة الحالية.</div></div><button class="btn" onclick="closeWorkItemActionPanel()">×</button></div><div id="workItemActionButtons" class="task-actions-wrap" style="margin-top:14px"></div></div></div>`);return document.getElementById('workItemActionModal')}
function closeWorkItemActionPanel(){document.getElementById('workItemActionModal')?.classList.remove('show')}
async function openWorkItemActionPanel(id,title){const m=ensureWorkItemActionModal(),b=document.getElementById('workItemActionButtons');document.getElementById('workItemActionTitle').textContent=title||displayText('مركز العمل');b.innerHTML=`<span class="muted">${displayText('جارٍ تحميل الإجراءات...')}</span>`;m.classList.add('show');const {data,error}=await sb.rpc('get_work_item_actions',{p_work_item_id:id});if(error){b.innerHTML=`<span class="red">${esc(error.message)}</span>`;return}const actions=data||[];b.innerHTML=actions.length?actions.map(x=>`<button class="btn ${['APPROVE_COMPLETION','APPROVE_PAYMENT_SUPERVISOR','APPROVE_PAYMENT_CFO','EXECUTE_PAYMENT','REGISTER_ACCOUNTING','FINALIZE_POSTING','COMPLETE'].includes(x.action_key)?'success':''}" onclick="runWorkItemAction('${id}','${x.action_key}')">${esc(workcenterActionLabel(x.action_key))}</button>`).join(''):`<span class="muted">${displayText('لا توجد إجراءات متاحة لك في الحالة الحالية.')}</span>`}
function chooseProfileForWorkcenter(promptText){const list=(profiles||[]).filter(x=>x.active!==false);const msg=list.map((x,i)=>`${i+1}. ${x.full_name} — ${ROLE_LABEL[x.role]||x.role}`).join('\n');const n=prompt(`${promptText}\n${msg}`);if(!n)return null;const idx=Number(n)-1;return list[idx]?.id||null}
function collectWorkcenterPayload(action){let v;if(action==='COMMENT'){v=prompt(displayText('اكتب التعليق'));return v===null?null:{body:v,comment_type:'Comment'}}if(action==='PROGRESS_UPDATE'){v=prompt(displayText('اكتب تحديث التقدم'));return v===null?null:{note:v}}if(['REQUEST_CLARIFICATION','REPORT_BLOCKER','RETURN_REWORK','REJECT_EXTENSION','REQUEST_EXTENSION_INFO','REQUEST_JUSTIFICATION'].includes(action)){v=prompt(displayText('اكتب السبب / الملاحظة'));return v===null?null:{reason:v,note:v}}if(action==='REQUEST_EXTENSION'){const d=prompt(displayText('تاريخ التسليم المطلوب YYYY-MM-DD'));if(!d)return null;const t=prompt(displayText('وقت التسليم HH:MM'),'17:00');if(!t)return null;const j=prompt(displayText('سبب طلب التمديد'));if(j===null)return null;return {requested_due_date:d,requested_due_time:t,justification:j}}if(action==='REASSIGN'){const id=chooseProfileForWorkcenter(displayText('اختر رقم الموظف الجديد'));if(!id)return null;const reason=prompt(displayText('سبب إعادة الإسناد'));if(reason===null)return null;return {new_owner_id:id,reason}}if(action==='CHANGE_REVIEWER'){const id=chooseProfileForWorkcenter(displayText('اختر رقم المراجع الجديد'));if(!id)return null;const reason=prompt(displayText('سبب تغيير المراجع'));if(reason===null)return null;return {reviewer_id:id,reason}}if(action==='CHANGE_DUE'){const d=prompt(displayText('تاريخ التسليم الجديد YYYY-MM-DD'));if(!d)return null;const t=prompt(displayText('وقت التسليم الجديد HH:MM'),'17:00');if(!t)return null;const reason=prompt(displayText('سبب تغيير الموعد'));if(reason===null)return null;return {due_date:d,due_time:t,reason}}if(action==='CHANGE_PRIORITY'){v=prompt(displayText('الأولوية الجديدة'));return v===null?null:{priority:v}}if(action==='APPROVE_EXTENSION'){v=prompt(displayText('ملاحظة الاعتماد (اختياري)'))||'';return {note:v}}if(action==='COMPLETE'||action==='SUBMIT_FOR_REVIEW'){v=prompt(displayText('تبرير التأخير إن وجد (اختياري)'))||'';return {justification:v}}return {}}
async function runWorkItemAction(id,action){const payload=collectWorkcenterPayload(action);if(payload===null)return;if(!confirm(`${displayText('تأكيد')}: ${workcenterActionLabel(action)}؟`))return;const {error}=await sb.rpc('perform_work_item_action',{p_work_item_id:id,p_action:action,p_payload:payload});if(error){alert(error.message);return}closeWorkItemActionPanel();await loadWorkflowCenter(workflowScope);}
'''
s=s.replace(anchor,js+'\n'+anchor,1)
p.write_text(s,encoding='utf-8')
