-- Sanam Finance Portal - Workflow Engine V3
-- Additive migration. Existing task/payment workflows remain authoritative.

create table if not exists public.workflow_instances (
  id uuid primary key default gen_random_uuid(),
  workflow_type text not null,
  source_entity_type text not null,
  source_entity_id text not null,
  status text not null default 'Active' check (status in ('Active','Completed','Cancelled','On Hold')),
  current_step_key text,
  created_by uuid references public.profiles(id),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workflow_type, source_entity_type, source_entity_id)
);

create table if not exists public.workflow_steps (
  id uuid primary key default gen_random_uuid(),
  workflow_instance_id uuid not null references public.workflow_instances(id) on delete cascade,
  step_key text not null,
  step_order integer not null,
  name text not null,
  assignee_role text,
  assignee_id uuid references public.profiles(id),
  reviewer_id uuid references public.profiles(id),
  status text not null default 'Waiting' check (status in ('Waiting','Ready','In Progress','Pending Review','Completed','Blocked','Cancelled')),
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  completed_by uuid references public.profiles(id),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workflow_instance_id, step_key)
);

create table if not exists public.work_items (
  id uuid primary key default gen_random_uuid(),
  workflow_instance_id uuid not null references public.workflow_instances(id) on delete cascade,
  workflow_step_id uuid references public.workflow_steps(id) on delete cascade,
  item_type text not null,
  source_entity_type text not null,
  source_entity_id text not null,
  title text not null,
  assignee_role text,
  assignee_id uuid references public.profiles(id),
  reviewer_id uuid references public.profiles(id),
  status text not null default 'Waiting' check (status in ('Waiting','Ready','In Progress','Pending Review','Completed','Blocked','Cancelled')),
  priority text,
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  completed_by uuid references public.profiles(id),
  performance_credit boolean not null default true,
  performance_units numeric(10,2) not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workflow_instance_id, item_type)
);

create table if not exists public.work_item_events (
  id bigint generated by default as identity primary key,
  work_item_id uuid not null references public.work_items(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists workflow_instances_source_idx on public.workflow_instances(source_entity_type, source_entity_id);
create index if not exists workflow_steps_instance_order_idx on public.workflow_steps(workflow_instance_id, step_order);
create index if not exists work_items_assignee_status_idx on public.work_items(assignee_id, status, due_at);
create index if not exists work_items_source_idx on public.work_items(source_entity_type, source_entity_id);
create index if not exists work_item_events_item_created_idx on public.work_item_events(work_item_id, created_at);

alter table public.workflow_instances enable row level security;
alter table public.workflow_steps enable row level security;
alter table public.work_items enable row level security;
alter table public.work_item_events enable row level security;

insert into public.finance_settings(setting_key,setting_value,updated_by,updated_at)
values('workflow_v3_enabled','false'::jsonb,null,now())
on conflict(setting_key) do nothing;

create or replace function private.workflow_v3_enabled()
returns boolean language sql stable security definer set search_path='public','private','pg_temp' as $$
  select coalesce((select setting_value::text::boolean from public.finance_settings where setting_key='workflow_v3_enabled'),false);
$$;

create or replace function private.workflow_user_for_role(p_role text)
returns uuid language sql stable security definer set search_path='public','private','pg_temp' as $$
  select id from public.profiles where active=true and role=p_role order by created_at,id limit 1;
$$;

create or replace function private.workflow_can_view_instance(p_instance_id uuid)
returns boolean language sql stable security definer set search_path='public','private','pg_temp' as $$
  select private.current_role() in ('CFO','Supervisor')
    or exists(select 1 from public.work_items w where w.workflow_instance_id=p_instance_id and (w.assignee_id=auth.uid() or w.reviewer_id=auth.uid()));
$$;

drop policy if exists workflow_instances_select on public.workflow_instances;
create policy workflow_instances_select on public.workflow_instances for select to authenticated using (private.workflow_can_view_instance(id));
drop policy if exists workflow_steps_select on public.workflow_steps;
create policy workflow_steps_select on public.workflow_steps for select to authenticated using (private.workflow_can_view_instance(workflow_instance_id));
drop policy if exists work_items_select on public.work_items;
create policy work_items_select on public.work_items for select to authenticated using (private.current_role() in ('CFO','Supervisor') or assignee_id=auth.uid() or reviewer_id=auth.uid());
drop policy if exists work_item_events_select on public.work_item_events;
create policy work_item_events_select on public.work_item_events for select to authenticated using (exists(select 1 from public.work_items w where w.id=work_item_id and (private.current_role() in ('CFO','Supervisor') or w.assignee_id=auth.uid() or w.reviewer_id=auth.uid())));

revoke insert,update,delete on public.workflow_instances,public.workflow_steps,public.work_items,public.work_item_events from anon,authenticated;
grant select on public.workflow_instances,public.workflow_steps,public.work_items,public.work_item_events to authenticated;

create or replace function private.upsert_workflow_step(
  p_instance uuid,p_key text,p_order integer,p_name text,p_role text,p_assignee uuid,p_reviewer uuid,
  p_status text,p_due_at timestamptz,p_started_at timestamptz,p_completed_at timestamptz,p_completed_by uuid,p_metadata jsonb default '{}'::jsonb
) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare v_step uuid;
begin
  insert into public.workflow_steps(workflow_instance_id,step_key,step_order,name,assignee_role,assignee_id,reviewer_id,status,due_at,started_at,completed_at,completed_by,metadata)
  values(p_instance,p_key,p_order,p_name,p_role,p_assignee,p_reviewer,p_status,p_due_at,p_started_at,p_completed_at,p_completed_by,coalesce(p_metadata,'{}'::jsonb))
  on conflict(workflow_instance_id,step_key) do update set
    step_order=excluded.step_order,name=excluded.name,assignee_role=excluded.assignee_role,assignee_id=excluded.assignee_id,reviewer_id=excluded.reviewer_id,
    status=excluded.status,due_at=excluded.due_at,started_at=coalesce(public.workflow_steps.started_at,excluded.started_at),
    completed_at=excluded.completed_at,completed_by=excluded.completed_by,metadata=public.workflow_steps.metadata||excluded.metadata,updated_at=now()
  returning id into v_step;
  return v_step;
end $$;

create or replace function private.upsert_work_item(
  p_instance uuid,p_step uuid,p_type text,p_source_type text,p_source_id text,p_title text,p_role text,p_assignee uuid,p_reviewer uuid,
  p_status text,p_priority text,p_due_at timestamptz,p_started_at timestamptz,p_completed_at timestamptz,p_completed_by uuid,
  p_credit boolean default true,p_units numeric default 1,p_metadata jsonb default '{}'::jsonb
) returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare v_id uuid; v_old_status text;
begin
  select status into v_old_status from public.work_items where workflow_instance_id=p_instance and item_type=p_type;
  insert into public.work_items(workflow_instance_id,workflow_step_id,item_type,source_entity_type,source_entity_id,title,assignee_role,assignee_id,reviewer_id,status,priority,due_at,started_at,completed_at,completed_by,performance_credit,performance_units,metadata)
  values(p_instance,p_step,p_type,p_source_type,p_source_id,p_title,p_role,p_assignee,p_reviewer,p_status,p_priority,p_due_at,p_started_at,p_completed_at,p_completed_by,p_credit,coalesce(p_units,1),coalesce(p_metadata,'{}'::jsonb))
  on conflict(workflow_instance_id,item_type) do update set
    workflow_step_id=excluded.workflow_step_id,title=excluded.title,assignee_role=excluded.assignee_role,assignee_id=excluded.assignee_id,reviewer_id=excluded.reviewer_id,
    status=excluded.status,priority=excluded.priority,due_at=excluded.due_at,started_at=coalesce(public.work_items.started_at,excluded.started_at),
    completed_at=excluded.completed_at,completed_by=excluded.completed_by,performance_credit=excluded.performance_credit,performance_units=excluded.performance_units,
    metadata=public.work_items.metadata||excluded.metadata,updated_at=now()
  returning id into v_id;
  if v_old_status is distinct from p_status then
    insert into public.work_item_events(work_item_id,actor_id,event_type,details)
    values(v_id,coalesce(p_completed_by,auth.uid()),'STATUS_CHANGED',jsonb_build_object('from',v_old_status,'to',p_status));
  end if;
  return v_id;
end $$;

create or replace function private.credit_work_item_completion(p_work_item_id uuid)
returns void language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare w public.work_items%rowtype; v_key text;
begin
  select * into w from public.work_items where id=p_work_item_id;
  if not found or w.status<>'Completed' or not w.performance_credit or w.completed_by is null then return; end if;
  if w.source_entity_type='task' then return; end if;
  v_key:='WORKFLOW_V3:'||w.id::text||':COMPLETED';
  insert into public.finance_activity_log(employee_id,activity_type,source_entity_type,source_entity_id,event_key,activity_date,occurred_at,sla_status,details)
  values(w.completed_by,w.item_type,w.source_entity_type,w.source_entity_id,v_key,(coalesce(w.completed_at,now()) at time zone 'Asia/Riyadh')::date,coalesce(w.completed_at,now()),
    case when w.due_at is null then null when coalesce(w.completed_at,now())<=w.due_at then 'On Time' else 'Late' end,
    jsonb_build_object('work_item_id',w.id,'workflow_instance_id',w.workflow_instance_id,'title',w.title,'performance_units',w.performance_units))
  on conflict(event_key) do nothing;
end $$;

create or replace function private.ensure_payment_workflow_v3(p_payment_id uuid)
returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare p public.payments%rowtype; v_instance uuid; v_sup uuid; v_cfo uuid; v_bank uuid; v_gl uuid; v_step uuid; v_item uuid; v_status text; v_current text; v_title text;
begin
  if not private.workflow_v3_enabled() then return null; end if;
  select * into p from public.payments where id=p_payment_id;
  if not found then return null; end if;
  v_sup:=private.workflow_user_for_role('Supervisor'); v_cfo:=private.workflow_user_for_role('CFO'); v_bank:=private.workflow_user_for_role('BankAccountant'); v_gl:=private.workflow_user_for_role('GLAccountant');
  v_title:='دفعة '||coalesce(p.beneficiary,'')||' — '||coalesce(p.company,'');
  insert into public.workflow_instances(workflow_type,source_entity_type,source_entity_id,status,current_step_key,created_by,metadata)
  values('PAYMENT','payment',p.id::text,case when p.posted_at is not null then 'Completed' else 'Active' end,null,p.requested_by,jsonb_build_object('beneficiary',p.beneficiary,'company',p.company,'amount',p.amount))
  on conflict(workflow_type,source_entity_type,source_entity_id) do update set status=excluded.status,metadata=public.workflow_instances.metadata||excluded.metadata,updated_at=now()
  returning id into v_instance;

  v_status:=case when p.supervisor_approved_at is not null or p.supervisor_status='موافق' then 'Completed' else 'Ready' end;
  v_step:=private.upsert_workflow_step(v_instance,'SUPERVISOR_APPROVAL',10,'مراجعة واعتماد المشرف','Supervisor',v_sup,v_cfo,v_status,null,null,p.supervisor_approved_at,p.supervisor_approved_by,'{}');
  v_item:=private.upsert_work_item(v_instance,v_step,'PAYMENT_SUPERVISOR_APPROVAL','payment',p.id::text,v_title||' — اعتماد المشرف','Supervisor',v_sup,v_cfo,v_status,p.priority,null,null,p.supervisor_approved_at,p.supervisor_approved_by,true,1,'{}'); perform private.credit_work_item_completion(v_item);

  v_status:=case when p.cfo_approved_at is not null or p.cfo_status='موافق' then 'Completed' when p.supervisor_approved_at is not null or p.supervisor_status='موافق' then 'Ready' else 'Waiting' end;
  v_step:=private.upsert_workflow_step(v_instance,'CFO_APPROVAL',20,'اعتماد المدير المالي','CFO',v_cfo,null,v_status,null,null,p.cfo_approved_at,p.cfo_approved_by,'{}');
  v_item:=private.upsert_work_item(v_instance,v_step,'PAYMENT_CFO_APPROVAL','payment',p.id::text,v_title||' — اعتماد المدير المالي','CFO',v_cfo,null,v_status,p.priority,null,null,p.cfo_approved_at,p.cfo_approved_by,true,1,'{}'); perform private.credit_work_item_completion(v_item);

  v_status:=case when p.executed_at is not null then 'Completed' when p.cfo_approved_at is not null or p.cfo_status='موافق' then 'Ready' else 'Waiting' end;
  v_step:=private.upsert_workflow_step(v_instance,'BANK_EXECUTION',30,'تنفيذ العملية البنكية','BankAccountant',v_bank,v_sup,v_status,null,null,p.executed_at,p.executed_by,'{}');
  v_item:=private.upsert_work_item(v_instance,v_step,'PAYMENT_BANK_EXECUTION','payment',p.id::text,v_title||' — تنفيذ بنكي','BankAccountant',v_bank,v_sup,v_status,p.priority,null,null,p.executed_at,p.executed_by,true,1,'{}'); perform private.credit_work_item_completion(v_item);

  v_status:=case when p.accounting_registered_at is not null then 'Completed' when p.executed_at is not null then 'Ready' else 'Waiting' end;
  v_step:=private.upsert_workflow_step(v_instance,'ACCOUNTING_REGISTRATION',40,'التسجيل المحاسبي','GLAccountant',v_gl,v_sup,v_status,case when p.executed_at is null then null else p.executed_at+interval '48 hours' end,null,p.accounting_registered_at,p.accounting_registered_by,'{}');
  v_item:=private.upsert_work_item(v_instance,v_step,'PAYMENT_ACCOUNTING_REGISTRATION','payment',p.id::text,v_title||' — تسجيل محاسبي','GLAccountant',v_gl,v_sup,v_status,p.priority,case when p.executed_at is null then null else p.executed_at+interval '48 hours' end,null,p.accounting_registered_at,p.accounting_registered_by,true,1,'{}'); perform private.credit_work_item_completion(v_item);

  v_status:=case when p.posted_at is not null then 'Completed' when p.accounting_registered_at is not null then 'Ready' else 'Waiting' end;
  v_step:=private.upsert_workflow_step(v_instance,'POSTING_FINALIZATION',50,'الترحيل والإقفال','GLAccountant',v_gl,v_sup,v_status,null,null,p.posted_at,p.posted_by,'{}');
  v_item:=private.upsert_work_item(v_instance,v_step,'PAYMENT_POSTING_FINALIZATION','payment',p.id::text,v_title||' — ترحيل وإقفال','GLAccountant',v_gl,v_sup,v_status,p.priority,null,null,p.posted_at,p.posted_by,true,1,'{}'); perform private.credit_work_item_completion(v_item);

  select step_key into v_current from public.workflow_steps where workflow_instance_id=v_instance and status not in ('Completed','Cancelled') order by step_order limit 1;
  update public.workflow_instances set current_step_key=v_current,status=case when p.posted_at is not null then 'Completed' else 'Active' end,completed_at=case when p.posted_at is not null then p.posted_at else null end,updated_at=now() where id=v_instance;
  return v_instance;
end $$;

create or replace function private.ensure_task_workflow_v3(p_task_id uuid)
returns uuid language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare t public.tasks%rowtype; v_instance uuid; v_step uuid; v_item uuid; v_status text; v_due timestamptz;
begin
  if not private.workflow_v3_enabled() then return null; end if;
  select * into t from public.tasks where id=p_task_id;
  if not found then return null; end if;
  v_status:=case t.status when 'مكتمل' then 'Completed' when 'بانتظار المراجعة' then 'Pending Review' when 'قيد التنفيذ' then 'In Progress' else 'Ready' end;
  v_due:=private.task_deadline(t.due_date,t.due_time);
  insert into public.workflow_instances(workflow_type,source_entity_type,source_entity_id,status,current_step_key,created_by,metadata)
  values('TASK','task',t.id::text,case when t.status='مكتمل' then 'Completed' else 'Active' end,'TASK_EXECUTION',t.created_by,jsonb_build_object('frequency',t.frequency,'output',t.output))
  on conflict(workflow_type,source_entity_type,source_entity_id) do update set status=excluded.status,metadata=public.workflow_instances.metadata||excluded.metadata,updated_at=now()
  returning id into v_instance;
  v_step:=private.upsert_workflow_step(v_instance,'TASK_EXECUTION',10,t.name,null,t.owner_id,t.reviewer_id,v_status,v_due,t.started_at,case when t.status='مكتمل' then coalesce(t.completed_at,t.reviewed_at) else null end,case when t.status='مكتمل' then coalesce(t.reviewed_by,t.owner_id) else null end,jsonb_build_object('task_status',t.status));
  v_item:=private.upsert_work_item(v_instance,v_step,'MANUAL_TASK','task',t.id::text,t.name,null,t.owner_id,t.reviewer_id,v_status,t.priority,v_due,t.started_at,case when t.status='مكتمل' then coalesce(t.completed_at,t.reviewed_at) else null end,case when t.status='مكتمل' then t.owner_id else null end,true,1,jsonb_build_object('task_status',t.status));
  if t.status='مكتمل' then update public.workflow_instances set completed_at=coalesce(t.completed_at,t.reviewed_at,now()),current_step_key=null where id=v_instance; end if;
  return v_instance;
end $$;

create or replace function private.workflow_payment_sync_trigger()
returns trigger language plpgsql security definer set search_path='public','private','pg_temp' as $$ begin perform private.ensure_payment_workflow_v3(new.id); return new; end $$;

drop trigger if exists trg_workflow_v3_payment_sync on public.payments;
create trigger trg_workflow_v3_payment_sync after insert or update of supervisor_status,cfo_status,status,supervisor_approved_at,cfo_approved_at,executed_at,accounting_registered_at,posted_at on public.payments for each row execute function private.workflow_payment_sync_trigger();

create or replace function private.workflow_task_sync_trigger()
returns trigger language plpgsql security definer set search_path='public','private','pg_temp' as $$ begin perform private.ensure_task_workflow_v3(new.id); return new; end $$;

drop trigger if exists trg_workflow_v3_task_sync on public.tasks;
create trigger trg_workflow_v3_task_sync after insert or update of owner_id,reviewer_id,status,due_date,due_time,priority,started_at,completed_at,review_requested_at,reviewed_at on public.tasks for each row execute function private.workflow_task_sync_trigger();

create or replace function public.get_my_work_queue(p_scope text default 'ACTIVE')
returns table(work_item_id uuid,workflow_instance_id uuid,item_type text,source_entity_type text,source_entity_id text,title text,status text,priority text,due_at timestamptz,started_at timestamptz,completed_at timestamptz,assignee_id uuid,assignee_name text,reviewer_id uuid,reviewer_name text,current_step_key text)
language sql stable security definer set search_path='public','private','pg_temp' as $$
 select w.id,w.workflow_instance_id,w.item_type,w.source_entity_type,w.source_entity_id,w.title,w.status,w.priority,w.due_at,w.started_at,w.completed_at,w.assignee_id,a.full_name,w.reviewer_id,r.full_name,i.current_step_key
 from public.work_items w join public.workflow_instances i on i.id=w.workflow_instance_id left join public.profiles a on a.id=w.assignee_id left join public.profiles r on r.id=w.reviewer_id
 where (private.current_role() in ('CFO','Supervisor') or w.assignee_id=auth.uid() or w.reviewer_id=auth.uid())
   and (case upper(coalesce(p_scope,'ACTIVE')) when 'COMPLETED_TODAY' then w.status='Completed' and (w.completed_at at time zone 'Asia/Riyadh')::date=(now() at time zone 'Asia/Riyadh')::date when 'ALL' then true else w.status not in ('Completed','Cancelled') end)
 order by case w.status when 'In Progress' then 1 when 'Ready' then 2 when 'Pending Review' then 3 when 'Blocked' then 4 else 5 end,w.due_at nulls last,w.created_at;
$$;

grant execute on function public.get_my_work_queue(text) to authenticated;

create or replace function public.get_workflow_timeline(p_source_entity_type text,p_source_entity_id text)
returns table(event_time timestamptz,event_type text,actor_name text,title text,details jsonb)
language sql stable security definer set search_path='public','private','pg_temp' as $$
 with wi as(select id from public.workflow_instances where source_entity_type=p_source_entity_type and source_entity_id=p_source_entity_id and private.workflow_can_view_instance(id))
 select e.created_at,e.event_type,p.full_name,w.title,e.details from public.work_item_events e join public.work_items w on w.id=e.work_item_id left join public.profiles p on p.id=e.actor_id where w.workflow_instance_id in(select id from wi)
 order by e.created_at;
$$;

grant execute on function public.get_workflow_timeline(text,text) to authenticated;

create or replace function public.get_workflow_v3_performance(p_date_from date default null,p_date_to date default null)
returns table(user_id uuid,full_name text,role text,completed_items integer,manual_tasks integer,transaction_items integer,on_time_items integer,late_items integer,on_time_rate numeric,total_units numeric)
language sql stable security definer set search_path='public','private','pg_temp' as $$
 with ctx as(select coalesce(p_date_from,(now() at time zone 'Asia/Riyadh')::date) d1,coalesce(p_date_to,(now() at time zone 'Asia/Riyadh')::date) d2,private.current_role() role,auth.uid() uid),
 people as(select p.* from public.profiles p,ctx c where p.active=true and (c.role in ('CFO','Supervisor') or p.id=c.uid)),
 x as(select pe.id,count(w.id) filter(where w.status='Completed')::int completed,count(w.id) filter(where w.status='Completed' and w.source_entity_type='task')::int manual,count(w.id) filter(where w.status='Completed' and w.source_entity_type<>'task')::int txn,count(w.id) filter(where w.status='Completed' and (w.due_at is null or w.completed_at<=w.due_at))::int ontime,count(w.id) filter(where w.status='Completed' and w.due_at is not null and w.completed_at>w.due_at)::int late,coalesce(sum(w.performance_units) filter(where w.status='Completed'),0) units from people pe cross join ctx c left join public.work_items w on w.completed_by=pe.id and (w.completed_at at time zone 'Asia/Riyadh')::date between c.d1 and c.d2 group by pe.id)
 select pe.id,pe.full_name,pe.role,x.completed,x.manual,x.txn,x.ontime,x.late,case when x.completed=0 then 0 else round(x.ontime*100.0/x.completed,1) end,x.units from people pe join x on x.id=pe.id order by pe.role,pe.full_name;
$$;

grant execute on function public.get_workflow_v3_performance(date,date) to authenticated;

create or replace function public.sync_workflow_v3_existing()
returns jsonb language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare v_p integer:=0; v_t integer:=0; r record;
begin
 if private.current_role()<>'CFO' then raise exception 'Only CFO can synchronize Workflow V3'; end if;
 if not private.workflow_v3_enabled() then raise exception 'Workflow V3 is disabled'; end if;
 for r in select id from public.payments loop perform private.ensure_payment_workflow_v3(r.id); v_p:=v_p+1; end loop;
 for r in select id from public.tasks where due_date>=coalesce((select trim(both '"' from setting_value::text)::date from public.finance_settings where setting_key='task_management_v2_go_live_date'),'2026-09-17'::date) loop perform private.ensure_task_workflow_v3(r.id); v_t:=v_t+1; end loop;
 return jsonb_build_object('payments',v_p,'tasks',v_t);
end $$;

grant execute on function public.sync_workflow_v3_existing() to authenticated;

create or replace function public.set_workflow_v3_enabled(p_enabled boolean,p_reason text default null)
returns void language plpgsql security definer set search_path='public','private','pg_temp' as $$
begin
 if private.current_role()<>'CFO' then raise exception 'Only CFO can change Workflow V3 state'; end if;
 insert into public.finance_settings(setting_key,setting_value,updated_by,updated_at) values('workflow_v3_enabled',to_jsonb(p_enabled),auth.uid(),now()) on conflict(setting_key) do update set setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
 insert into public.audit_log(actor_id,action,entity_type,entity_id,details) values(auth.uid(),'SET_WORKFLOW_V3_STATE','system','workflow_v3',jsonb_build_object('enabled',p_enabled,'reason',nullif(trim(coalesce(p_reason,'')),'')));
end $$;

grant execute on function public.set_workflow_v3_enabled(boolean,text) to authenticated;
